In [1]:
# Historical data crawl

In [1]:
import BigBull

In [2]:
# DB connection setting
conn_string = 'postgresql+psycopg2://daesikkim@localhost:5432/db_goldspoon'
db = BigBull.StockDB(conn_string, BigBull.__meta)

In [3]:
# Crawler Settings 
stock_crawler = BigBull.StockCodeCrawler(db)
hist_crawler = BigBull.HistoryCrawler(db)
finance_crawler = BigBull.CompanyInformationCrawler(db)

In [5]:
# Crawl Stocks info 
stock_crawler.save_stock_code()

kospi: 1435

ValueError: not enough values to unpack (expected 2, got 1)

In [4]:
# Crawl Historical data 
stock_ls = [i for i in db.load_all_stock_code()]
names, codes = zip(*stock_ls)

In [6]:
count = 0
for name in names:
    hist_crawler.save_history_of(name, hard_mode=True)
    count += 1 
    print(f"---- {name} crawled / {count/len(names)*100}% ----")

삼성전자(005930)의 history 작업을 시작합니다.
인터섹션이 있습니다.

KeyboardInterrupt:

In [5]:
# update DB for historical data 
count = 0 
for name in names:
    hist_crawler.save_history_of(name, start_date="2018-4-16")
    count +=1 
    print(f'---- {name} crawled / {count} / {len(names)}----')

삼성전자(005930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성전자 crawled / 1 / 2713----
SK하이닉스(000660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK하이닉스 crawled / 2 / 2713----
삼성바이오로직스(207940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성바이오로직스 crawled / 3 / 2713----
삼성전자우(005935)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성전자우 crawled / 4 / 2713----
셀트리온(068270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 셀트리온 crawled / 5 / 2713----
현대차(005380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대차 crawled / 6 / 2713----
POSCO(005490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- POSCO crawled / 7 / 2713----
LG화학(051910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG화학 crawled / 8 / 2713----
삼성물산(028260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성물산 crawled / 9 / 2713----
NAVER(035420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NAVER crawled / 10 / 2713----
KB금융(105560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KB금융 crawled / 11 / 2713----
현대모비스(012330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대모비스 crawled / 12 / 2713----
삼성생명(032830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성생명 crawled / 13 / 2713----
한국전력(015760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국전력 crawled / 14 / 2713----
신한지주(055550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한지주 crawled / 15 / 2713----
SK(034730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK crawled / 16 / 2713----
LG생활건강(051900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG생활건강 crawled / 17 / 2713----
아모레퍼시픽(090430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아모레퍼시픽 crawled / 18 / 2713----
SK이노베이션(096770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK이노베이션 crawled / 19 / 2713----
SK텔레콤(017670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK텔레콤 crawled / 20 / 2713----
삼성에스디에스(018260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성에스디에스 crawled / 21 / 2713----
LG전자(066570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG전자 crawled / 22 / 2713----
LG(003550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG crawled / 23 / 2713----
롯데케미칼(011170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데케미칼 crawled / 24 / 2713----
KT&G(033780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KT&G crawled / 25 / 2713----
S-Oil(010950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- S-Oil crawled / 26 / 2713----
삼성SDI(006400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성SDI crawled / 27 / 2713----
하나금융지주(086790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나금융지주 crawled / 28 / 2713----
기아차(000270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 기아차 crawled / 29 / 2713----
삼성화재(000810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성화재 crawled / 30 / 2713----
넷마블게임즈(251270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넷마블게임즈 crawled / 31 / 2713----
아모레G(002790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아모레G crawled / 32 / 2713----
우리은행(000030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리은행 crawled / 33 / 2713----
카카오(035720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 카카오 crawled / 34 / 2713----
LG디스플레이(034220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG디스플레이 crawled / 35 / 2713----
기업은행(024110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 기업은행 crawled / 36 / 2713----
현대중공업(009540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대중공업 crawled / 37 / 2713----
고려아연(010130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고려아연 crawled / 38 / 2713----
엔씨소프트(036570)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔씨소프트 crawled / 39 / 2713----
삼성전기(009150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성전기 crawled / 40 / 2713----
이마트(139480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이마트 crawled / 41 / 2713----
KT(030200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KT crawled / 42 / 2713----
롯데쇼핑(023530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데쇼핑 crawled / 43 / 2713----
현대중공업지주(267250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대중공업지주 crawled / 44 / 2713----
현대제철(004020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대제철 crawled / 45 / 2713----
코웨이(021240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코웨이 crawled / 46 / 2713----
현대글로비스(086280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대글로비스 crawled / 47 / 2713----
한국타이어(161390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국타이어 crawled / 48 / 2713----
한미약품(128940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한미약품 crawled / 49 / 2713----
한온시스템(018880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한온시스템 crawled / 50 / 2713----
미래에셋대우(006800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋대우 crawled / 51 / 2713----
한미사이언스(008930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한미사이언스 crawled / 52 / 2713----
강원랜드(035250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 강원랜드 crawled / 53 / 2713----
GS(078930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GS crawled / 54 / 2713----
KODEX 200(069500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 200 crawled / 55 / 2713----
LG유플러스(032640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG유플러스 crawled / 56 / 2713----
한화생명(088350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화생명 crawled / 57 / 2713----
오리온(271560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오리온 crawled / 58 / 2713----
한화케미칼(009830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화케미칼 crawled / 59 / 2713----
CJ제일제당(097950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ제일제당 crawled / 60 / 2713----
현대건설(000720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대건설 crawled / 61 / 2713----
한국가스공사(036460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국가스공사 crawled / 62 / 2713----
CJ(001040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ crawled / 63 / 2713----
롯데지주(004990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데지주 crawled / 64 / 2713----
한국항공우주(047810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국항공우주 crawled / 65 / 2713----
한국금융지주(071050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국금융지주 crawled / 66 / 2713----
효성(004800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 효성 crawled / 67 / 2713----
DB손해보험(005830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DB손해보험 crawled / 68 / 2713----
삼성카드(029780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성카드 crawled / 69 / 2713----
OCI(010060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- OCI crawled / 70 / 2713----
신세계(004170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신세계 crawled / 71 / 2713----
호텔신라(008770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 호텔신라 crawled / 72 / 2713----
NH투자증권(005940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NH투자증권 crawled / 73 / 2713----
KCC(002380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KCC crawled / 74 / 2713----
현대차2우B(005387)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대차2우B crawled / 75 / 2713----
에스원(012750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스원 crawled / 76 / 2713----
삼성엔지니어링(028050)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성엔지니어링 crawled / 77 / 2713----
한샘(009240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한샘 crawled / 78 / 2713----
BNK금융지주(138930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- BNK금융지주 crawled / 79 / 2713----
현대산업(012630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대산업 crawled / 80 / 2713----
현대해상(001450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대해상 crawled / 81 / 2713----
삼성증권(016360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성증권 crawled / 82 / 2713----
대한항공(003490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한항공 crawled / 83 / 2713----
아이엔지생명(079440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이엔지생명 crawled / 84 / 2713----
두산밥캣(241560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두산밥캣 crawled / 85 / 2713----
맥쿼리인프라(088980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 맥쿼리인프라 crawled / 86 / 2713----
BGF리테일(282330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- BGF리테일 crawled / 87 / 2713----
CJ대한통운(000120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ대한통운 crawled / 88 / 2713----
유한양행(000100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유한양행 crawled / 89 / 2713----
삼성중공업(010140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성중공업 crawled / 90 / 2713----
TIGER 200(102110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 crawled / 91 / 2713----
LG이노텍(011070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG이노텍 crawled / 92 / 2713----
금호석유(011780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금호석유 crawled / 93 / 2713----
대우조선해양(042660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대우조선해양 crawled / 94 / 2713----
포스코대우(047050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포스코대우 crawled / 95 / 2713----
한화(000880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화 crawled / 96 / 2713----
대림산업(000210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대림산업 crawled / 97 / 2713----
GS리테일(007070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GS리테일 crawled / 98 / 2713----
동서(026960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동서 crawled / 99 / 2713----
오뚜기(007310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오뚜기 crawled / 100 / 2713----
팬오션(028670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팬오션 crawled / 101 / 2713----
녹십자(006280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 녹십자 crawled / 102 / 2713----
메리츠종금증권(008560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메리츠종금증권 crawled / 103 / 2713----
GS건설(006360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GS건설 crawled / 104 / 2713----
키움증권(039490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 키움증권 crawled / 105 / 2713----
대웅제약(069620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대웅제약 crawled / 106 / 2713----
KODEX 레버리지(122630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 레버리지 crawled / 107 / 2713----
대우건설(047040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대우건설 crawled / 108 / 2713----
쌍용양회(003410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쌍용양회 crawled / 109 / 2713----
메리츠화재(000060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메리츠화재 crawled / 110 / 2713----
현대차우(005385)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대차우 crawled / 111 / 2713----
LS(006260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LS crawled / 112 / 2713----
만도(204320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 만도 crawled / 113 / 2713----
제일기획(030000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제일기획 crawled / 114 / 2713----
현대백화점(069960)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대백화점 crawled / 115 / 2713----
두산(000150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두산 crawled / 116 / 2713----
현대엘리베이(017800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대엘리베이 crawled / 117 / 2713----
한전KPS(051600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한전KPS crawled / 118 / 2713----
메리츠금융지주(138040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메리츠금융지주 crawled / 119 / 2713----
DGB금융지주(139130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DGB금융지주 crawled / 120 / 2713----
녹십자홀딩스(005250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 녹십자홀딩스 crawled / 121 / 2713----
농심(004370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 농심 crawled / 122 / 2713----
현대미포조선(010620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대미포조선 crawled / 123 / 2713----
대한유화(006650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한유화 crawled / 124 / 2713----
아모레퍼시픽우(090435)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아모레퍼시픽우 crawled / 125 / 2713----
LS산전(010120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LS산전 crawled / 126 / 2713----
롯데정밀화학(004000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데정밀화학 crawled / 127 / 2713----
한올바이오파마(009420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한올바이오파마 crawled / 128 / 2713----
두산인프라코어(042670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두산인프라코어 crawled / 129 / 2713----
롯데하이마트(071840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데하이마트 crawled / 130 / 2713----
현대건설기계(267270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대건설기계 crawled / 131 / 2713----
한국타이어월드와이드(000240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국타이어월드와이드 crawled / 132 / 2713----
한국콜마(161890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국콜마 crawled / 133 / 2713----
코오롱인더(120110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱인더 crawled / 134 / 2713----
영진약품(003520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영진약품 crawled / 135 / 2713----
더존비즈온(012510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 더존비즈온 crawled / 136 / 2713----
LG화학우(051915)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG화학우 crawled / 137 / 2713----
일진머티리얼즈(020150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일진머티리얼즈 crawled / 138 / 2713----
영풍(000670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영풍 crawled / 139 / 2713----
두산중공업(034020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두산중공업 crawled / 140 / 2713----
오리온홀딩스(001800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오리온홀딩스 crawled / 141 / 2713----
CJ CGV(079160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ CGV crawled / 142 / 2713----
LG생활건강우(051905)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG생활건강우 crawled / 143 / 2713----
휠라코리아(081660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휠라코리아 crawled / 144 / 2713----
GKL(114090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GKL crawled / 145 / 2713----
현대상선(011200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대상선 crawled / 146 / 2713----
현대그린푸드(005440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대그린푸드 crawled / 147 / 2713----
하이트진로(000080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이트진로 crawled / 148 / 2713----
코스맥스(192820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코스맥스 crawled / 149 / 2713----
KODEX 코스닥150 레버리지(233740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 코스닥150 레버리지 crawled / 150 / 2713----
한화테크윈(012450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화테크윈 crawled / 151 / 2713----
현대위아(011210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대위아 crawled / 152 / 2713----
현대로템(064350)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대로템 crawled / 153 / 2713----
SKC(011790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SKC crawled / 154 / 2713----
부광약품(003000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부광약품 crawled / 155 / 2713----
락앤락(115390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 락앤락 crawled / 156 / 2713----
태광산업(003240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태광산업 crawled / 157 / 2713----
코리안리(003690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코리안리 crawled / 158 / 2713----
SK네트웍스(001740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK네트웍스 crawled / 159 / 2713----
파미셀(005690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파미셀 crawled / 160 / 2713----
KBSTAR 200(148020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200 crawled / 161 / 2713----
동양생명(082640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양생명 crawled / 162 / 2713----
하나투어(039130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나투어 crawled / 163 / 2713----
잇츠한불(226320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 잇츠한불 crawled / 164 / 2713----
종근당(185750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 종근당 crawled / 165 / 2713----
한진칼(180640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한진칼 crawled / 166 / 2713----
NHN엔터테인먼트(181710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NHN엔터테인먼트 crawled / 167 / 2713----
이노션(214320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이노션 crawled / 168 / 2713----
롯데칠성(005300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데칠성 crawled / 169 / 2713----
대웅(003090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대웅 crawled / 170 / 2713----
BGF(027410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- BGF crawled / 171 / 2713----
현대홈쇼핑(057050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대홈쇼핑 crawled / 172 / 2713----
SK케미칼(285130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK케미칼 crawled / 173 / 2713----
제주항공(089590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제주항공 crawled / 174 / 2713----
KODEX 삼성그룹(102780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 삼성그룹 crawled / 175 / 2713----
넥센타이어(002350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥센타이어 crawled / 176 / 2713----
영원무역(111770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영원무역 crawled / 177 / 2713----
KODEX 코스닥 150(229200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 코스닥 150 crawled / 178 / 2713----
KODEX 단기채권(153130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 단기채권 crawled / 179 / 2713----
동원시스템즈(014820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동원시스템즈 crawled / 180 / 2713----
애경산업(018250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 애경산업 crawled / 181 / 2713----
동원산업(006040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동원산업 crawled / 182 / 2713----
대한전선(001440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한전선 crawled / 183 / 2713----
SPC삼립(005610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SPC삼립 crawled / 184 / 2713----
풍산(103140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 풍산 crawled / 185 / 2713----
한전기술(052690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한전기술 crawled / 186 / 2713----
LG상사(001120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG상사 crawled / 187 / 2713----
아시아나항공(020560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아시아나항공 crawled / 188 / 2713----
휴켐스(069260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴켐스 crawled / 189 / 2713----
KBSTAR 국고채3년선물인버스(282000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 국고채3년선물인버스 crawled / 190 / 2713----
동아에스티(170900)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동아에스티 crawled / 191 / 2713----
다우기술(023590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 다우기술 crawled / 192 / 2713----
LIG넥스원(079550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LIG넥스원 crawled / 193 / 2713----
AK홀딩스(006840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- AK홀딩스 crawled / 194 / 2713----
금호타이어(073240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금호타이어 crawled / 195 / 2713----
인스코비(006490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인스코비 crawled / 196 / 2713----
JB금융지주(175330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JB금융지주 crawled / 197 / 2713----
진에어(272450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진에어 crawled / 198 / 2713----
ARIRANG 200(152100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 200 crawled / 199 / 2713----
지역난방공사(071320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지역난방공사 crawled / 200 / 2713----
필룩스(033180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 필룩스 crawled / 201 / 2713----
동국제강(001230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동국제강 crawled / 202 / 2713----
후성(093370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 후성 crawled / 203 / 2713----
JW중외제약(001060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JW중외제약 crawled / 204 / 2713----
신세계인터내셔날(031430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신세계인터내셔날 crawled / 205 / 2713----
삼양사(145990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼양사 crawled / 206 / 2713----
한일시멘트(003300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한일시멘트 crawled / 207 / 2713----
한세실업(105630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한세실업 crawled / 208 / 2713----
SK가스(018670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK가스 crawled / 209 / 2713----
세아베스틸(001430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세아베스틸 crawled / 210 / 2713----
KODEX 단기채권PLUS(214980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 단기채권PLUS crawled / 211 / 2713----
미래에셋생명(085620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋생명 crawled / 212 / 2713----
TIGER 단기통안채(157450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 단기통안채 crawled / 213 / 2713----
쿠쿠홈시스(284740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쿠쿠홈시스 crawled / 214 / 2713----
아이에스동서(010780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이에스동서 crawled / 215 / 2713----
대상(001680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대상 crawled / 216 / 2713----
한화손해보험(000370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화손해보험 crawled / 217 / 2713----
덴티움(145720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덴티움 crawled / 218 / 2713----
롯데관광개발(032350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데관광개발 crawled / 219 / 2713----
유안타증권(003470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유안타증권 crawled / 220 / 2713----
KOSEF 200(069660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 200 crawled / 221 / 2713----
동아쏘시오홀딩스(000640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동아쏘시오홀딩스 crawled / 222 / 2713----
일양약품(007570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일양약품 crawled / 223 / 2713----
LF(093050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LF crawled / 224 / 2713----
한솔케미칼(014680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔케미칼 crawled / 225 / 2713----
태영건설(009410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태영건설 crawled / 226 / 2713----
한섬(020000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한섬 crawled / 227 / 2713----
경동나비엔(009450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경동나비엔 crawled / 228 / 2713----
현대일렉트릭(267260)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대일렉트릭 crawled / 229 / 2713----
동원F&B(049770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동원F&B crawled / 230 / 2713----
한국콜마홀딩스(024720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국콜마홀딩스 crawled / 231 / 2713----
삼양홀딩스(000070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼양홀딩스 crawled / 232 / 2713----
롯데푸드(002270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데푸드 crawled / 233 / 2713----
KINDEX 200(105190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 200 crawled / 234 / 2713----
에이프로젠 KIC(007460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이프로젠 KIC crawled / 235 / 2713----
에스엘(005850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스엘 crawled / 236 / 2713----
롯데제과(280360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데제과 crawled / 237 / 2713----
영원무역홀딩스(009970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영원무역홀딩스 crawled / 238 / 2713----
한국토지신탁(034830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국토지신탁 crawled / 239 / 2713----
LG전자우(066575)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG전자우 crawled / 240 / 2713----
LG하우시스(108670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG하우시스 crawled / 241 / 2713----
송원산업(004430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 송원산업 crawled / 242 / 2713----
TIGER 단기채권액티브(272580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 단기채권액티브 crawled / 243 / 2713----
KODEX 인버스(114800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 인버스 crawled / 244 / 2713----
한미반도체(042700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한미반도체 crawled / 245 / 2713----
쌍용차(003620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쌍용차 crawled / 246 / 2713----
대신증권(003540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신증권 crawled / 247 / 2713----
KODEX MSCI Korea TR(278540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX MSCI Korea TR crawled / 248 / 2713----
NICE(034310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NICE crawled / 249 / 2713----
F&F(007700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- F&F crawled / 250 / 2713----
삼진제약(005500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼진제약 crawled / 251 / 2713----
대교(019680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대교 crawled / 252 / 2713----
대한해운(005880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한해운 crawled / 253 / 2713----
남해화학(025860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남해화학 crawled / 254 / 2713----
DB하이텍(000990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DB하이텍 crawled / 255 / 2713----
신도리코(029530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신도리코 crawled / 256 / 2713----
미래에셋대우2우B(00680K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋대우2우B crawled / 257 / 2713----
JW홀딩스(096760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JW홀딩스 crawled / 258 / 2713----
코오롱(002020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱 crawled / 259 / 2713----
한국자산신탁(123890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국자산신탁 crawled / 260 / 2713----
CJ헬로(037560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ헬로 crawled / 261 / 2713----
빙그레(005180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 빙그레 crawled / 262 / 2713----
삼양식품(003230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼양식품 crawled / 263 / 2713----
신풍제약(019170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신풍제약 crawled / 264 / 2713----
고려제강(002240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고려제강 crawled / 265 / 2713----
제이준코스메틱(025620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이준코스메틱 crawled / 266 / 2713----
TIGER 코스닥150(232080)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스닥150 crawled / 267 / 2713----
화승엔터프라이즈(241590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화승엔터프라이즈 crawled / 268 / 2713----
스카이라이프(053210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스카이라이프 crawled / 269 / 2713----
삼성화재우(000815)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성화재우 crawled / 270 / 2713----
씨에스윈드(112610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨에스윈드 crawled / 271 / 2713----
S&T모티브(064960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- S&T모티브 crawled / 272 / 2713----
광주은행(192530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 광주은행 crawled / 273 / 2713----
풀무원(017810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 풀무원 crawled / 274 / 2713----
쿠쿠홀딩스(192400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쿠쿠홀딩스 crawled / 275 / 2713----
신세계푸드(031440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신세계푸드 crawled / 276 / 2713----
동성제약(002210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동성제약 crawled / 277 / 2713----
현대리바트(079430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대리바트 crawled / 278 / 2713----
KODEX 200TR(278530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 200TR crawled / 279 / 2713----
폴루스바이오팜(007630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 폴루스바이오팜 crawled / 280 / 2713----
삼화콘덴서(001820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼화콘덴서 crawled / 281 / 2713----
한국단자(025540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국단자 crawled / 282 / 2713----
신영증권(001720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신영증권 crawled / 283 / 2713----
KODEX 종합채권(AA-이상)액티브(273130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 종합채권(AA-이상)액티브 crawled / 284 / 2713----
일동제약(249420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일동제약 crawled / 285 / 2713----
한라홀딩스(060980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한라홀딩스 crawled / 286 / 2713----
보령제약(003850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 보령제약 crawled / 287 / 2713----
세아홀딩스(058650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세아홀딩스 crawled / 288 / 2713----
한화투자증권(003530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화투자증권 crawled / 289 / 2713----
광동제약(009290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 광동제약 crawled / 290 / 2713----
농심홀딩스(072710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 농심홀딩스 crawled / 291 / 2713----
무학(033920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 무학 crawled / 292 / 2713----
한독(002390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한독 crawled / 293 / 2713----
현대에이치씨엔(126560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대에이치씨엔 crawled / 294 / 2713----
제일약품(271980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제일약품 crawled / 295 / 2713----
유나이티드제약(033270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유나이티드제약 crawled / 296 / 2713----
남양유업(003920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남양유업 crawled / 297 / 2713----
신한 레버리지 WTI원유 선물 ETN(H)(500019)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 레버리지 WTI원유 선물 ETN(H) crawled / 298 / 2713----
SBS(034120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SBS crawled / 299 / 2713----
환인제약(016580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 환인제약 crawled / 300 / 2713----
엔에스쇼핑(138250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔에스쇼핑 crawled / 301 / 2713----
유양디앤유(011690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유양디앤유 crawled / 302 / 2713----
JW생명과학(234080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JW생명과학 crawled / 303 / 2713----
세아제강(003030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세아제강 crawled / 304 / 2713----
삼천리(004690)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼천리 crawled / 305 / 2713----
SK디앤디(210980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK디앤디 crawled / 306 / 2713----
SK디스커버리(006120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK디스커버리 crawled / 307 / 2713----
동양(001520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양 crawled / 308 / 2713----
애경유화(161000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 애경유화 crawled / 309 / 2713----
세방전지(004490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세방전지 crawled / 310 / 2713----
화승인더(006060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화승인더 crawled / 311 / 2713----
팜스코(036580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팜스코 crawled / 312 / 2713----
에이블씨엔씨(078520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이블씨엔씨 crawled / 313 / 2713----
율촌화학(008730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 율촌화학 crawled / 314 / 2713----
유니드(014830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니드 crawled / 315 / 2713----
한국쉘석유(002960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국쉘석유 crawled / 316 / 2713----
아주캐피탈(033660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아주캐피탈 crawled / 317 / 2713----
케이씨텍(281820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이씨텍 crawled / 318 / 2713----
서울가스(017390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서울가스 crawled / 319 / 2713----
해태제과식품(101530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 해태제과식품 crawled / 320 / 2713----
이연제약(102460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이연제약 crawled / 321 / 2713----
삼익THK(004380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼익THK crawled / 322 / 2713----
동양네트웍스(030790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양네트웍스 crawled / 323 / 2713----
STX(011810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- STX crawled / 324 / 2713----
나노메딕스(074610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나노메딕스 crawled / 325 / 2713----
무림P&P(009580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 무림P&P crawled / 326 / 2713----
E1(017940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- E1 crawled / 327 / 2713----
롯데손해보험(000400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데손해보험 crawled / 328 / 2713----
티웨이홀딩스(004870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티웨이홀딩스 crawled / 329 / 2713----
우리종금(010050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리종금 crawled / 330 / 2713----
대덕전자(008060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대덕전자 crawled / 331 / 2713----
SBS미디어홀딩스(101060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SBS미디어홀딩스 crawled / 332 / 2713----
경방(000050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경방 crawled / 333 / 2713----
에이프로젠제약(003060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이프로젠제약 crawled / 334 / 2713----
부산가스(015350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부산가스 crawled / 335 / 2713----
대원제약(003220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대원제약 crawled / 336 / 2713----
세원셀론텍(091090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세원셀론텍 crawled / 337 / 2713----
휴비스(079980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴비스 crawled / 338 / 2713----
한솔제지(213500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔제지 crawled / 339 / 2713----
한신공영(004960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한신공영 crawled / 340 / 2713----
풍산홀딩스(005810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 풍산홀딩스 crawled / 341 / 2713----
S-Oil우(010955)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- S-Oil우 crawled / 342 / 2713----
종근당홀딩스(001630)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 종근당홀딩스 crawled / 343 / 2713----
두산엔진(082740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두산엔진 crawled / 344 / 2713----
코스모화학(005420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코스모화학 crawled / 345 / 2713----
경보제약(214390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경보제약 crawled / 346 / 2713----
흥국화재(000540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 흥국화재 crawled / 347 / 2713----
서흥(008490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서흥 crawled / 348 / 2713----
한화3우B(00088K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화3우B crawled / 349 / 2713----
선진(136490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 선진 crawled / 350 / 2713----
아세아시멘트(183190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아세아시멘트 crawled / 351 / 2713----
금호산업(002990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금호산업 crawled / 352 / 2713----
광주신세계(037710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 광주신세계 crawled / 353 / 2713----
넥센(005720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥센 crawled / 354 / 2713----
SK증권(001510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK증권 crawled / 355 / 2713----
신영증권우(001725)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신영증권우 crawled / 356 / 2713----
퍼시스(016800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 퍼시스 crawled / 357 / 2713----
카프로(006380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 카프로 crawled / 358 / 2713----
국도화학(007690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국도화학 crawled / 359 / 2713----
한세예스24홀딩스(016450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한세예스24홀딩스 crawled / 360 / 2713----
동화약품(000020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동화약품 crawled / 361 / 2713----
아모레G우(002795)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아모레G우 crawled / 362 / 2713----
한국유리(002000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국유리 crawled / 363 / 2713----
TRUE 코스피 양매도 ETN(570019)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 코스피 양매도 ETN crawled / 364 / 2713----
맵스리얼티1(094800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 맵스리얼티1 crawled / 365 / 2713----
한진중공업(097230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한진중공업 crawled / 366 / 2713----
용평리조트(070960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 용평리조트 crawled / 367 / 2713----
대덕GDS(004130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대덕GDS crawled / 368 / 2713----
KODEX 국채선물10년인버스(176950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 국채선물10년인버스 crawled / 369 / 2713----
KODEX 200선물인버스2X(252670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 200선물인버스2X crawled / 370 / 2713----
KODEX KRX300(292190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX KRX300 crawled / 371 / 2713----
사조산업(007160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 사조산업 crawled / 372 / 2713----
교보증권(030610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 교보증권 crawled / 373 / 2713----
대상홀딩스(084690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대상홀딩스 crawled / 374 / 2713----
조선내화(000480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조선내화 crawled / 375 / 2713----
아이마켓코리아(122900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이마켓코리아 crawled / 376 / 2713----
모토닉(009680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모토닉 crawled / 377 / 2713----
디티알오토모티브(007340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디티알오토모티브 crawled / 378 / 2713----
KG케미칼(001390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KG케미칼 crawled / 379 / 2713----
코스맥스비티아이(044820)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코스맥스비티아이 crawled / 380 / 2713----
토니모리(214420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 토니모리 crawled / 381 / 2713----
유진투자증권(001200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유진투자증권 crawled / 382 / 2713----
알보젠코리아(002250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알보젠코리아 crawled / 383 / 2713----
일성신약(003120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일성신약 crawled / 384 / 2713----
KBSTAR 단기통안채(196230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 단기통안채 crawled / 385 / 2713----
KTB투자증권(030210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KTB투자증권 crawled / 386 / 2713----
AJ네트웍스(095570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- AJ네트웍스 crawled / 387 / 2713----
IHQ(003560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- IHQ crawled / 388 / 2713----
한국철강(104700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국철강 crawled / 389 / 2713----
코리아오토글라스(152330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코리아오토글라스 crawled / 390 / 2713----
ARIRANG 고배당주(161510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 고배당주 crawled / 391 / 2713----
해성디에스(195870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 해성디에스 crawled / 392 / 2713----
자화전자(033240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 자화전자 crawled / 393 / 2713----
두산우(000155)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두산우 crawled / 394 / 2713----
KBSTAR 코스닥150(270810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 코스닥150 crawled / 395 / 2713----
미원에스씨(268280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미원에스씨 crawled / 396 / 2713----
KBSTAR 코스닥150선물레버리지(278240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 코스닥150선물레버리지 crawled / 397 / 2713----
현대차투자증권(001500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대차투자증권 crawled / 398 / 2713----
파워 200(152870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파워 200 crawled / 399 / 2713----
알루코(001780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알루코 crawled / 400 / 2713----
TIGER 글로벌4차산업혁신기술(합성 H)(275980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 글로벌4차산업혁신기술(합성 H) crawled / 401 / 2713----
케이씨(029460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이씨 crawled / 402 / 2713----
한화갤러리아타임월드(027390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화갤러리아타임월드 crawled / 403 / 2713----
삼양패키징(272550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼양패키징 crawled / 404 / 2713----
동성코퍼레이션(102260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동성코퍼레이션 crawled / 405 / 2713----
신세계 I&C(035510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신세계 I&C crawled / 406 / 2713----
한솔테크닉스(004710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔테크닉스 crawled / 407 / 2713----
TIGER 200 IT(139260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 IT crawled / 408 / 2713----
삼영무역(002810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼영무역 crawled / 409 / 2713----
신성이엔지(011930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신성이엔지 crawled / 410 / 2713----
벽산(007210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 벽산 crawled / 411 / 2713----
KPX케미칼(025000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KPX케미칼 crawled / 412 / 2713----
코오롱플라스틱(138490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱플라스틱 crawled / 413 / 2713----
AJ렌터카(068400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- AJ렌터카 crawled / 414 / 2713----
신대양제지(016590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신대양제지 crawled / 415 / 2713----
코스모신소재(005070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코스모신소재 crawled / 416 / 2713----
동부제철(016380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동부제철 crawled / 417 / 2713----
대한제분(001130)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한제분 crawled / 418 / 2713----
아세아(002030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아세아 crawled / 419 / 2713----
삼일제약(000520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼일제약 crawled / 420 / 2713----
TIGER 중국소비테마(150460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 중국소비테마 crawled / 421 / 2713----
진흥기업(002780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진흥기업 crawled / 422 / 2713----
KPX홀딩스(092230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KPX홀딩스 crawled / 423 / 2713----
한진(002320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한진 crawled / 424 / 2713----
한국화장품(123690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국화장품 crawled / 425 / 2713----
GS글로벌(001250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GS글로벌 crawled / 426 / 2713----
한국카본(017960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국카본 crawled / 427 / 2713----
STX엔진(077970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- STX엔진 crawled / 428 / 2713----
신라교역(004970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신라교역 crawled / 429 / 2713----
대원강업(000430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대원강업 crawled / 430 / 2713----
일진다이아(081000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일진다이아 crawled / 431 / 2713----
아세아제지(002310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아세아제지 crawled / 432 / 2713----
세방(004360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세방 crawled / 433 / 2713----
일진홀딩스(015860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일진홀딩스 crawled / 434 / 2713----
일신방직(003200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일신방직 crawled / 435 / 2713----
S&T중공업(003570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- S&T중공업 crawled / 436 / 2713----
조광피혁(004700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조광피혁 crawled / 437 / 2713----
코오롱글로벌(003070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱글로벌 crawled / 438 / 2713----
아남전자(008700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아남전자 crawled / 439 / 2713----
예스코(015360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 예스코 crawled / 440 / 2713----
TIGER 차이나CSI300(192090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 차이나CSI300 crawled / 441 / 2713----
경인양행(012610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경인양행 crawled / 442 / 2713----
TIGER 차이나CSI300레버리지(합성)(204480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 차이나CSI300레버리지(합성) crawled / 443 / 2713----
부국증권(001270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부국증권 crawled / 444 / 2713----
KISCO홀딩스(001940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KISCO홀딩스 crawled / 445 / 2713----
현대상사(011760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대상사 crawled / 446 / 2713----
LS네트웍스(000680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LS네트웍스 crawled / 447 / 2713----
삼영전자(005680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼영전자 crawled / 448 / 2713----
현대시멘트(006390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대시멘트 crawled / 449 / 2713----
코라오홀딩스(900140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코라오홀딩스 crawled / 450 / 2713----
한국주철관(000970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국주철관 crawled / 451 / 2713----
명문제약(017180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 명문제약 crawled / 452 / 2713----
웅진씽크빅(095720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웅진씽크빅 crawled / 453 / 2713----
한국금융지주우(071055)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국금융지주우 crawled / 454 / 2713----
현대약품(004310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대약품 crawled / 455 / 2713----
대신증권우(003545)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신증권우 crawled / 456 / 2713----
대한제강(084010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한제강 crawled / 457 / 2713----
한솔홀딩스(004150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔홀딩스 crawled / 458 / 2713----
TIGER 경기방어(139280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 경기방어 crawled / 459 / 2713----
S&T홀딩스(036530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- S&T홀딩스 crawled / 460 / 2713----
KODEX 코스피(226490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 코스피 crawled / 461 / 2713----
웅진(016880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웅진 crawled / 462 / 2713----
하이트진로홀딩스(000140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이트진로홀딩스 crawled / 463 / 2713----
KODEX 코스닥150선물인버스(251340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 코스닥150선물인버스 crawled / 464 / 2713----
서연이화(200880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서연이화 crawled / 465 / 2713----
태림포장(011280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태림포장 crawled / 466 / 2713----
KBSTAR KRX300(292050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR KRX300 crawled / 467 / 2713----
삼성제약(001360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성제약 crawled / 468 / 2713----
LS전선아시아(229640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LS전선아시아 crawled / 469 / 2713----
크라운해태홀딩스(005740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크라운해태홀딩스 crawled / 470 / 2713----
핸즈코퍼레이션(143210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 핸즈코퍼레이션 crawled / 471 / 2713----
아이콘트롤스(039570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이콘트롤스 crawled / 472 / 2713----
코리아써키트(007810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코리아써키트 crawled / 473 / 2713----
강남제비스코(000860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 강남제비스코 crawled / 474 / 2713----
사조동아원(008040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 사조동아원 crawled / 475 / 2713----
한국화장품제조(003350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국화장품제조 crawled / 476 / 2713----
삼호(001880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼호 crawled / 477 / 2713----
유니퀘스트(077500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니퀘스트 crawled / 478 / 2713----
현대차3우B(005389)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대차3우B crawled / 479 / 2713----
현대EP(089470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대EP crawled / 480 / 2713----
제이에스코퍼레이션(194370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이에스코퍼레이션 crawled / 481 / 2713----
NPC(004250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NPC crawled / 482 / 2713----
대한제당(001790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한제당 crawled / 483 / 2713----
디와이파워(210540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디와이파워 crawled / 484 / 2713----
신원(009270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신원 crawled / 485 / 2713----
동아타이어(282690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동아타이어 crawled / 486 / 2713----
노루홀딩스(000320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 노루홀딩스 crawled / 487 / 2713----
삼광글라스(005090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼광글라스 crawled / 488 / 2713----
오리엔트바이오(002630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오리엔트바이오 crawled / 489 / 2713----
웅진에너지(103130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웅진에너지 crawled / 490 / 2713----
KSS해운(044450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KSS해운 crawled / 491 / 2713----
동부건설(005960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동부건설 crawled / 492 / 2713----
삼익악기(002450)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼익악기 crawled / 493 / 2713----
대성산업(128820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대성산업 crawled / 494 / 2713----
신성통상(005390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신성통상 crawled / 495 / 2713----
한국패러랠(168490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국패러랠 crawled / 496 / 2713----
성창기업지주(000180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성창기업지주 crawled / 497 / 2713----
KINDEX 중국본토CSI300(168580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 중국본토CSI300 crawled / 498 / 2713----
미원상사(002840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미원상사 crawled / 499 / 2713----
두산건설(011160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두산건설 crawled / 500 / 2713----
디피씨(026890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디피씨 crawled / 501 / 2713----
이수화학(005950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이수화학 crawled / 502 / 2713----
삼화페인트(000390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼화페인트 crawled / 503 / 2713----
유수홀딩스(000700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유수홀딩스 crawled / 504 / 2713----
경동도시가스(267290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경동도시가스 crawled / 505 / 2713----
화성산업(002460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화성산업 crawled / 506 / 2713----
KINDEX 베트남VN30(합성)(245710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 베트남VN30(합성) crawled / 507 / 2713----
일진전기(103590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일진전기 crawled / 508 / 2713----
BYC(001460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- BYC crawled / 509 / 2713----
동일산업(004890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동일산업 crawled / 510 / 2713----
대동공업(000490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대동공업 crawled / 511 / 2713----
TIGER 헬스케어(143860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 헬스케어 crawled / 512 / 2713----
휴니드(005870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴니드 crawled / 513 / 2713----
세진중공업(075580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세진중공업 crawled / 514 / 2713----
광전자(017900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 광전자 crawled / 515 / 2713----
샘표식품(248170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 샘표식품 crawled / 516 / 2713----
이월드(084680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이월드 crawled / 517 / 2713----
도화엔지니어링(002150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 도화엔지니어링 crawled / 518 / 2713----
퍼스텍(010820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 퍼스텍 crawled / 519 / 2713----
세이브존I&C(067830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세이브존I&C crawled / 520 / 2713----
CJ제일제당 우(097955)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ제일제당 우 crawled / 521 / 2713----
SK이노베이션우(096775)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK이노베이션우 crawled / 522 / 2713----
DB금융투자(016610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DB금융투자 crawled / 523 / 2713----
쌍방울(102280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쌍방울 crawled / 524 / 2713----
모나리자(012690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모나리자 crawled / 525 / 2713----
사조대림(003960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 사조대림 crawled / 526 / 2713----
지엠비코리아(013870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지엠비코리아 crawled / 527 / 2713----
대우부품(009320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대우부품 crawled / 528 / 2713----
NH투자증권우(005945)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NH투자증권우 crawled / 529 / 2713----
태경산업(015890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태경산업 crawled / 530 / 2713----
현대비앤지스틸(004560)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대비앤지스틸 crawled / 531 / 2713----
엔케이(085310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔케이 crawled / 532 / 2713----
디아이씨(092200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디아이씨 crawled / 533 / 2713----
남광토건(001260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남광토건 crawled / 534 / 2713----
일진디스플(020760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일진디스플 crawled / 535 / 2713----
유화증권(003460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유화증권 crawled / 536 / 2713----
SG세계물산(004060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SG세계물산 crawled / 537 / 2713----
크라운제과(264900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크라운제과 crawled / 538 / 2713----
상신브레이크(041650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 상신브레이크 crawled / 539 / 2713----
CJ우(001045)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ우 crawled / 540 / 2713----
보락(002760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 보락 crawled / 541 / 2713----
동아지질(028100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동아지질 crawled / 542 / 2713----
대성에너지(117580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대성에너지 crawled / 543 / 2713----
진원생명과학(011000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진원생명과학 crawled / 544 / 2713----
팀스(134790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팀스 crawled / 545 / 2713----
일동홀딩스(000230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일동홀딩스 crawled / 546 / 2713----
텔코웨어(078000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 텔코웨어 crawled / 547 / 2713----
포스코강판(058430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포스코강판 crawled / 548 / 2713----
KODEX 증권(102970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 증권 crawled / 549 / 2713----
노루페인트(090350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 노루페인트 crawled / 550 / 2713----
세아특수강(019440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세아특수강 crawled / 551 / 2713----
디와이(013570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디와이 crawled / 552 / 2713----
세종공업(033530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세종공업 crawled / 553 / 2713----
SH에너지화학(002360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SH에너지화학 crawled / 554 / 2713----
대한화섬(003830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한화섬 crawled / 555 / 2713----
계룡건설(013580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 계룡건설 crawled / 556 / 2713----
한라(014790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한라 crawled / 557 / 2713----
태평양물산(007980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태평양물산 crawled / 558 / 2713----
디아이(003160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디아이 crawled / 559 / 2713----
이수페타시스(007660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이수페타시스 crawled / 560 / 2713----
깨끗한나라(004540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 깨끗한나라 crawled / 561 / 2713----
백광산업(001340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 백광산업 crawled / 562 / 2713----
진양홀딩스(100250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진양홀딩스 crawled / 563 / 2713----
DB(012030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DB crawled / 564 / 2713----
광명전기(017040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 광명전기 crawled / 565 / 2713----
코오롱머티리얼(144620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱머티리얼 crawled / 566 / 2713----
LG우(003555)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG우 crawled / 567 / 2713----
경농(002100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경농 crawled / 568 / 2713----
백산(035150)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 백산 crawled / 569 / 2713----
KBSTAR 단기국공채액티브(272560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 단기국공채액티브 crawled / 570 / 2713----
화승알앤에이(013520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화승알앤에이 crawled / 571 / 2713----
제주은행(006220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제주은행 crawled / 572 / 2713----
우리들제약(004720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리들제약 crawled / 573 / 2713----
효성ITX(094280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 효성ITX crawled / 574 / 2713----
서연(007860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서연 crawled / 575 / 2713----
YG PLUS(037270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- YG PLUS crawled / 576 / 2713----
디씨엠(024090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디씨엠 crawled / 577 / 2713----
대경기계(015590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대경기계 crawled / 578 / 2713----
지투알(035000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지투알 crawled / 579 / 2713----
KEC(092220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KEC crawled / 580 / 2713----
신세계건설(034300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신세계건설 crawled / 581 / 2713----
TIGER 코스닥150 레버리지(233160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스닥150 레버리지 crawled / 582 / 2713----
한국공항(005430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국공항 crawled / 583 / 2713----
TIGER 코스피(277630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스피 crawled / 584 / 2713----
인디에프(014990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인디에프 crawled / 585 / 2713----
제일파마홀딩스(002620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제일파마홀딩스 crawled / 586 / 2713----
TBH글로벌(084870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TBH글로벌 crawled / 587 / 2713----
종근당바이오(063160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 종근당바이오 crawled / 588 / 2713----
성신양회(004980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성신양회 crawled / 589 / 2713----
STX중공업(071970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- STX중공업 crawled / 590 / 2713----
삼성전기우(009155)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성전기우 crawled / 591 / 2713----
황금에스티(032560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 황금에스티 crawled / 592 / 2713----
DRB동일(004840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DRB동일 crawled / 593 / 2713----
삼성SDI우(006405)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성SDI우 crawled / 594 / 2713----
금강공업(014280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금강공업 crawled / 595 / 2713----
미창석유(003650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미창석유 crawled / 596 / 2713----
미래산업(025560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래산업 crawled / 597 / 2713----
화신(010690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화신 crawled / 598 / 2713----
골든브릿지증권(001290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 골든브릿지증권 crawled / 599 / 2713----
무림페이퍼(009200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 무림페이퍼 crawled / 600 / 2713----
아비스타(090370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아비스타 crawled / 601 / 2713----
KODEX 선진국MSCI World(251350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 선진국MSCI World crawled / 602 / 2713----
삼성물산우B(02826K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성물산우B crawled / 603 / 2713----
조흥(002600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조흥 crawled / 604 / 2713----
일신석재(007110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일신석재 crawled / 605 / 2713----
대림씨엔에스(004440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대림씨엔에스 crawled / 606 / 2713----
선도전기(007610)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 선도전기 crawled / 607 / 2713----
계양전기(012200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 계양전기 crawled / 608 / 2713----
한국ANKOR유전(152550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국ANKOR유전 crawled / 609 / 2713----
KODEX 단기변동금리부채권액티브(273140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 단기변동금리부채권액티브 crawled / 610 / 2713----
삼양통상(002170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼양통상 crawled / 611 / 2713----
삼성 KTOP30 ETN(530013)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 KTOP30 ETN crawled / 612 / 2713----
KOSEF 미국달러선물 레버리지(합성)(225800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 미국달러선물 레버리지(합성) crawled / 613 / 2713----
인천도시가스(034590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인천도시가스 crawled / 614 / 2713----
비상교육(100220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비상교육 crawled / 615 / 2713----
흥아해운(003280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 흥아해운 crawled / 616 / 2713----
테이팩스(055490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 테이팩스 crawled / 617 / 2713----
TIGER KRX300(292160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER KRX300 crawled / 618 / 2713----
대성홀딩스(016710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대성홀딩스 crawled / 619 / 2713----
우신시스템(017370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우신시스템 crawled / 620 / 2713----
기신정기(092440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 기신정기 crawled / 621 / 2713----
삼부토건(001470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼부토건 crawled / 622 / 2713----
성보화학(003080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성보화학 crawled / 623 / 2713----
동양물산(002900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양물산 crawled / 624 / 2713----
한세엠케이(069640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한세엠케이 crawled / 625 / 2713----
고려개발(004200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고려개발 crawled / 626 / 2713----
삼원강재(023000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼원강재 crawled / 627 / 2713----
천일고속(000650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 천일고속 crawled / 628 / 2713----
국제약품(002720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국제약품 crawled / 629 / 2713----
KODEX 200가치저변동(223190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 200가치저변동 crawled / 630 / 2713----
현대코퍼레이션홀딩스(227840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대코퍼레이션홀딩스 crawled / 631 / 2713----
SIMPAC(009160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SIMPAC crawled / 632 / 2713----
동양철관(008970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양철관 crawled / 633 / 2713----
성지건설(005980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성지건설 crawled / 634 / 2713----
사조오양(006090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 사조오양 crawled / 635 / 2713----
두올(016740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두올 crawled / 636 / 2713----
SG충방(001380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SG충방 crawled / 637 / 2713----
한솔홈데코(025750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔홈데코 crawled / 638 / 2713----
남선알미늄(008350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남선알미늄 crawled / 639 / 2713----
신영와코루(005800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신영와코루 crawled / 640 / 2713----
미원화학(134380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미원화학 crawled / 641 / 2713----
삼호개발(010960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼호개발 crawled / 642 / 2713----
삼성 레버리지 인도 Nifty50 선물 ETN(H)(530026)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 레버리지 인도 Nifty50 선물 ETN(H) crawled / 643 / 2713----
새론오토모티브(075180)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 새론오토모티브 crawled / 644 / 2713----
삼화전기(009470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼화전기 crawled / 645 / 2713----
KINDEX 단기통안채(190620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 단기통안채 crawled / 646 / 2713----
세원정공(021820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세원정공 crawled / 647 / 2713----
동일방직(001530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동일방직 crawled / 648 / 2713----
호전실업(111110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 호전실업 crawled / 649 / 2713----
대림산업우(000215)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대림산업우 crawled / 650 / 2713----
써니전자(004770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 써니전자 crawled / 651 / 2713----
TIGER 200선물레버리지(267770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200선물레버리지 crawled / 652 / 2713----
영흥철강(012160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영흥철강 crawled / 653 / 2713----
KC그린홀딩스(009440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KC그린홀딩스 crawled / 654 / 2713----
TIGER 코스피중형주(277650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스피중형주 crawled / 655 / 2713----
대원전선(006340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대원전선 crawled / 656 / 2713----
극동유화(014530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 극동유화 crawled / 657 / 2713----
HANARO 200(293180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- HANARO 200 crawled / 658 / 2713----
신일산업(002700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신일산업 crawled / 659 / 2713----
화천기공(000850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화천기공 crawled / 660 / 2713----
TIGER 200선물인버스2X(252710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200선물인버스2X crawled / 661 / 2713----
KGP(109070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KGP crawled / 662 / 2713----
KODEX 은행(091170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 은행 crawled / 663 / 2713----
한국제지(002300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국제지 crawled / 664 / 2713----
삼성 인도 Nifty50 선물 ETN(H)(530024)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 인도 Nifty50 선물 ETN(H) crawled / 665 / 2713----
사조씨푸드(014710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 사조씨푸드 crawled / 666 / 2713----
유유제약(000220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유유제약 crawled / 667 / 2713----
조광페인트(004910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조광페인트 crawled / 668 / 2713----
삼화왕관(004450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼화왕관 crawled / 669 / 2713----
대현(016090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대현 crawled / 670 / 2713----
유니온머티리얼(047400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니온머티리얼 crawled / 671 / 2713----
대구백화점(006370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대구백화점 crawled / 672 / 2713----
KODEX 200 중소형(226980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 200 중소형 crawled / 673 / 2713----
참엔지니어링(009310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 참엔지니어링 crawled / 674 / 2713----
한신기계(011700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한신기계 crawled / 675 / 2713----
보해양조(000890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 보해양조 crawled / 676 / 2713----
KODEX 미국달러선물레버리지(261250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국달러선물레버리지 crawled / 677 / 2713----
삼성 레버리지 WTI원유 선물 ETN(530031)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 레버리지 WTI원유 선물 ETN crawled / 678 / 2713----
한전산업(130660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한전산업 crawled / 679 / 2713----
대유에이텍(002880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대유에이텍 crawled / 680 / 2713----
에넥스(011090)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에넥스 crawled / 681 / 2713----
윌비스(008600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 윌비스 crawled / 682 / 2713----
동원(003580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동원 crawled / 683 / 2713----
동방아그로(007590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동방아그로 crawled / 684 / 2713----
신흥(004080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신흥 crawled / 685 / 2713----
KTcs(058850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KTcs crawled / 686 / 2713----
KODEX MSCI Korea(156080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX MSCI Korea crawled / 687 / 2713----
한진중공업홀딩스(003480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한진중공업홀딩스 crawled / 688 / 2713----
S&TC(100840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- S&TC crawled / 689 / 2713----
TIGER 미국S&P500선물(H)(143850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국S&P500선물(H) crawled / 690 / 2713----
미원홀딩스(107590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미원홀딩스 crawled / 691 / 2713----
다스코(058730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 다스코 crawled / 692 / 2713----
한미글로벌(053690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한미글로벌 crawled / 693 / 2713----
ARIRANG 단기채권액티브(278620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 단기채권액티브 crawled / 694 / 2713----
금호석유우(011785)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금호석유우 crawled / 695 / 2713----
금양(001570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금양 crawled / 696 / 2713----
가온전선(000500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 가온전선 crawled / 697 / 2713----
형지엘리트(093240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 형지엘리트 crawled / 698 / 2713----
평화산업(090080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 평화산업 crawled / 699 / 2713----
KOSEF 단기자금(130730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 단기자금 crawled / 700 / 2713----
경동인베스트(012320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경동인베스트 crawled / 701 / 2713----
대창(012800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대창 crawled / 702 / 2713----
동일고무벨트(163560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동일고무벨트 crawled / 703 / 2713----
한양증권(001750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한양증권 crawled / 704 / 2713----
CJ씨푸드(011150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ씨푸드 crawled / 705 / 2713----
대영포장(014160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대영포장 crawled / 706 / 2713----
케이티스(058860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이티스 crawled / 707 / 2713----
대교우B(019685)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대교우B crawled / 708 / 2713----
인지컨트롤스(023800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인지컨트롤스 crawled / 709 / 2713----
인터지스(129260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인터지스 crawled / 710 / 2713----
우진(105840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우진 crawled / 711 / 2713----
조선선재(120030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조선선재 crawled / 712 / 2713----
대림B&Co(005750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대림B&Co crawled / 713 / 2713----
평화홀딩스(010770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 평화홀딩스 crawled / 714 / 2713----
대창단조(015230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대창단조 crawled / 715 / 2713----
동성화학(005190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동성화학 crawled / 716 / 2713----
삼성출판사(068290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성출판사 crawled / 717 / 2713----
삼성공조(006660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성공조 crawled / 718 / 2713----
샘표(007540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 샘표 crawled / 719 / 2713----
KPX그린케미칼(083420)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KPX그린케미칼 crawled / 720 / 2713----
우성사료(006980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우성사료 crawled / 721 / 2713----
KBSTAR KQ고배당(270800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR KQ고배당 crawled / 722 / 2713----
영보화학(014440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영보화학 crawled / 723 / 2713----
TIGER 원유선물Enhanced(H)(130680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 원유선물Enhanced(H) crawled / 724 / 2713----
삼정펄프(009770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼정펄프 crawled / 725 / 2713----
마니커(027740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마니커 crawled / 726 / 2713----
화인베스틸(133820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화인베스틸 crawled / 727 / 2713----
SK우(03473K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK우 crawled / 728 / 2713----
한농화성(011500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한농화성 crawled / 729 / 2713----
키위미디어그룹(012170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 키위미디어그룹 crawled / 730 / 2713----
대원화성(024890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대원화성 crawled / 731 / 2713----
삼성 인버스 인도 Nifty50 선물 ETN(H)(530025)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 인버스 인도 Nifty50 선물 ETN(H) crawled / 732 / 2713----
수출포장(002200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 수출포장 crawled / 733 / 2713----
한창(005110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한창 crawled / 734 / 2713----
CS홀딩스(000590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CS홀딩스 crawled / 735 / 2713----
일성건설(013360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일성건설 crawled / 736 / 2713----
휴스틸(005010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴스틸 crawled / 737 / 2713----
이건산업(008250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이건산업 crawled / 738 / 2713----
세화아이엠씨(145210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세화아이엠씨 crawled / 739 / 2713----
DSR(155660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DSR crawled / 740 / 2713----
유성기업(002920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유성기업 crawled / 741 / 2713----
DSR제강(069730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DSR제강 crawled / 742 / 2713----
KOSEF 미국달러선물(138230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 미국달러선물 crawled / 743 / 2713----
선창산업(002820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 선창산업 crawled / 744 / 2713----
NI스틸(008260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NI스틸 crawled / 745 / 2713----
대신증권2우B(003547)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신증권2우B crawled / 746 / 2713----
고려산업(002140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고려산업 crawled / 747 / 2713----
우리들휴브레인(118000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리들휴브레인 crawled / 748 / 2713----
KB KQ 우량주30 ETN(580007)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KB KQ 우량주30 ETN crawled / 749 / 2713----
동남합성(023450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동남합성 crawled / 750 / 2713----
방림(003610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 방림 crawled / 751 / 2713----
수산중공업(017550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 수산중공업 crawled / 752 / 2713----
KINDEX S&P아시아TOP50(277540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX S&P아시아TOP50 crawled / 753 / 2713----
서울식품(004410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서울식품 crawled / 754 / 2713----
KCTC(009070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KCTC crawled / 755 / 2713----
코오롱인더우(120115)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱인더우 crawled / 756 / 2713----
유니켐(011330)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니켐 crawled / 757 / 2713----
조일알미늄(018470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조일알미늄 crawled / 758 / 2713----
영화금속(012280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영화금속 crawled / 759 / 2713----
백광소재(014580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 백광소재 crawled / 760 / 2713----
KBSTAR 국고채3년(114100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 국고채3년 crawled / 761 / 2713----
페이퍼코리아(001020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 페이퍼코리아 crawled / 762 / 2713----
신송홀딩스(006880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신송홀딩스 crawled / 763 / 2713----
금비(008870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금비 crawled / 764 / 2713----
신한 레버리지 천연가스 선물 ETN(H)(500031)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 레버리지 천연가스 선물 ETN(H) crawled / 765 / 2713----
영풍제지(006740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영풍제지 crawled / 766 / 2713----
대림통상(006570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대림통상 crawled / 767 / 2713----
TIGER 200동일가중(252000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200동일가중 crawled / 768 / 2713----
이구산업(025820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이구산업 crawled / 769 / 2713----
ARIRANG 코스피50(122090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 코스피50 crawled / 770 / 2713----
대호에이엘(069460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대호에이엘 crawled / 771 / 2713----
한익스프레스(014130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한익스프레스 crawled / 772 / 2713----
KR모터스(000040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KR모터스 crawled / 773 / 2713----
만호제강(001080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 만호제강 crawled / 774 / 2713----
사조해표(079660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 사조해표 crawled / 775 / 2713----
KC코트렐(119650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KC코트렐 crawled / 776 / 2713----
아티스(101140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아티스 crawled / 777 / 2713----
GS우(078935)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GS우 crawled / 778 / 2713----
KBSTAR 200선물인버스2X(252420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200선물인버스2X crawled / 779 / 2713----
KBSTAR 중소형고배당(281990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 중소형고배당 crawled / 780 / 2713----
삼성 레버리지 천연가스 선물 ETN(530037)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 레버리지 천연가스 선물 ETN crawled / 781 / 2713----
조비(001550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조비 crawled / 782 / 2713----
한국종합기술(023350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국종합기술 crawled / 783 / 2713----
미래에셋대우우(006805)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋대우우 crawled / 784 / 2713----
두산2우B(000157)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두산2우B crawled / 785 / 2713----
한국내화(010040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국내화 crawled / 786 / 2713----
우진플라임(049800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우진플라임 crawled / 787 / 2713----
TIGER 차이나HSCEI(245360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 차이나HSCEI crawled / 788 / 2713----
남성(004270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남성 crawled / 789 / 2713----
한국프랜지(010100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국프랜지 crawled / 790 / 2713----
대유플러스(000300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대유플러스 crawled / 791 / 2713----
미래아이앤지(007120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래아이앤지 crawled / 792 / 2713----
진도(088790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진도 crawled / 793 / 2713----
SJM(123700)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SJM crawled / 794 / 2713----
유니온(000910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니온 crawled / 795 / 2713----
KBSTAR 중장기국공채액티브(272570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 중장기국공채액티브 crawled / 796 / 2713----
신한 WTI원유 선물 ETN(H)(500015)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 WTI원유 선물 ETN(H) crawled / 797 / 2713----
SJM홀딩스(025530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SJM홀딩스 crawled / 798 / 2713----
까뮤이앤씨(013700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 까뮤이앤씨 crawled / 799 / 2713----
동원금속(018500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동원금속 crawled / 800 / 2713----
에이엔피(015260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이엔피 crawled / 801 / 2713----
KODEX 중국본토 A50(169950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 중국본토 A50 crawled / 802 / 2713----
KODEX China H(099140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX China H crawled / 803 / 2713----
한국석유(004090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국석유 crawled / 804 / 2713----
KINDEX 중장기국공채액티브(272910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 중장기국공채액티브 crawled / 805 / 2713----
대한방직(001070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한방직 crawled / 806 / 2713----
부국증권우(001275)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부국증권우 crawled / 807 / 2713----
KBSTAR 고배당(266160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 고배당 crawled / 808 / 2713----
동양피스톤(092780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양피스톤 crawled / 809 / 2713----
KB KTOP30 ETN(580006)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KB KTOP30 ETN crawled / 810 / 2713----
신한 K200 USD 선물 바이셀 ETN(500001)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 K200 USD 선물 바이셀 ETN crawled / 811 / 2713----
키다리스튜디오(020120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 키다리스튜디오 crawled / 812 / 2713----
ARIRANG KRX300(292750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG KRX300 crawled / 813 / 2713----
에쓰씨엔지니어링(023960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에쓰씨엔지니어링 crawled / 814 / 2713----
한창제지(009460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한창제지 crawled / 815 / 2713----
모나미(005360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모나미 crawled / 816 / 2713----
QV Big Vol ETN(550001)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV Big Vol ETN crawled / 817 / 2713----
동양고속(084670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양고속 crawled / 818 / 2713----
국동(005320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국동 crawled / 819 / 2713----
태양금속(004100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태양금속 crawled / 820 / 2713----
동국실업(001620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동국실업 crawled / 821 / 2713----
문배철강(008420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 문배철강 crawled / 822 / 2713----
롯데지주우(00499K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데지주우 crawled / 823 / 2713----
덕성(004830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덕성 crawled / 824 / 2713----
제일연마(001560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제일연마 crawled / 825 / 2713----
한국특수형강(007280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국특수형강 crawled / 826 / 2713----
베트남개발1(096300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 베트남개발1 crawled / 827 / 2713----
ARIRANG 코스피(227830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 코스피 crawled / 828 / 2713----
KODEX 필수소비재(266410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 필수소비재 crawled / 829 / 2713----
KB KQ Monthly Best 11 ETN(580004)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KB KQ Monthly Best 11 ETN crawled / 830 / 2713----
KODEX 골드선물(H)(132030)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 골드선물(H) crawled / 831 / 2713----
와이비로드(010600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이비로드 crawled / 832 / 2713----
태경화학(006890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태경화학 crawled / 833 / 2713----
부국철강(026940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부국철강 crawled / 834 / 2713----
롯데칠성우(005305)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 롯데칠성우 crawled / 835 / 2713----
KODEX China H 레버리지(H)(204450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX China H 레버리지(H) crawled / 836 / 2713----
이화산업(000760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이화산업 crawled / 837 / 2713----
삼화전자(011230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼화전자 crawled / 838 / 2713----
서원(021050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서원 crawled / 839 / 2713----
TIGER 200IT레버리지(243880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200IT레버리지 crawled / 840 / 2713----
동방(004140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동방 crawled / 841 / 2713----
KODEX 국고채3년(114260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 국고채3년 crawled / 842 / 2713----
갤럭시아에스엠(011420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 갤럭시아에스엠 crawled / 843 / 2713----
WISCOM(024070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- WISCOM crawled / 844 / 2713----
콤텍시스템(031820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 콤텍시스템 crawled / 845 / 2713----
주연테크(044380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 주연테크 crawled / 846 / 2713----
원림(005820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원림 crawled / 847 / 2713----
한일철강(002220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한일철강 crawled / 848 / 2713----
KBSTAR 중기우량회사채(136340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 중기우량회사채 crawled / 849 / 2713----
QV WISE 배당 ETN(550002)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV WISE 배당 ETN crawled / 850 / 2713----
혜인(003010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 혜인 crawled / 851 / 2713----
SK케미칼우(28513K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK케미칼우 crawled / 852 / 2713----
이아이디(093230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이아이디 crawled / 853 / 2713----
하이스틸(071090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이스틸 crawled / 854 / 2713----
금호전기(001210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금호전기 crawled / 855 / 2713----
KODEX 중국본토CSI300(283580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 중국본토CSI300 crawled / 856 / 2713----
ARIRANG 단기유동성(190160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 단기유동성 crawled / 857 / 2713----
남영비비안(002070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남영비비안 crawled / 858 / 2713----
유한양행우(000105)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유한양행우 crawled / 859 / 2713----
MH에탄올(023150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- MH에탄올 crawled / 860 / 2713----
유엔젤(072130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유엔젤 crawled / 861 / 2713----
유화증권우(003465)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유화증권우 crawled / 862 / 2713----
덕양산업(024900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덕양산업 crawled / 863 / 2713----
KODEX 고배당(279530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 고배당 crawled / 864 / 2713----
TIGER 차이나CSI300인버스(합성)(217780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 차이나CSI300인버스(합성) crawled / 865 / 2713----
인팩(023810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인팩 crawled / 866 / 2713----
코아스(071950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코아스 crawled / 867 / 2713----
TIGER 농산물선물Enhanced(H)(137610)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 농산물선물Enhanced(H) crawled / 868 / 2713----
성문전자(014910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성문전자 crawled / 869 / 2713----
범양건영(002410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 범양건영 crawled / 870 / 2713----
KBSTAR 모멘텀밸류(252720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 모멘텀밸류 crawled / 871 / 2713----
LG하우시스우(108675)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- LG하우시스우 crawled / 872 / 2713----
ARIRANG 우량회사채50 1년(239660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 우량회사채50 1년 crawled / 873 / 2713----
동일제강(002690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동일제강 crawled / 874 / 2713----
성안(011300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성안 crawled / 875 / 2713----
대양금속(009190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대양금속 crawled / 876 / 2713----
KB Monthly Best 11 ETN(580003)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KB Monthly Best 11 ETN crawled / 877 / 2713----
금호에이치티(214330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금호에이치티 crawled / 878 / 2713----
화천기계(010660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화천기계 crawled / 879 / 2713----
세하(027970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세하 crawled / 880 / 2713----
세우글로벌(013000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세우글로벌 crawled / 881 / 2713----
대동전자(008110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대동전자 crawled / 882 / 2713----
KBSTAR 중국본토대형주CSI100(174360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 중국본토대형주CSI100 crawled / 883 / 2713----
TCC동양(002710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TCC동양 crawled / 884 / 2713----
QV 바이오 TOP5 ETN(550014)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 바이오 TOP5 ETN crawled / 885 / 2713----
부산산업(011390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부산산업 crawled / 886 / 2713----
TIGER 인버스(123310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 인버스 crawled / 887 / 2713----
바다로19호(155900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바다로19호 crawled / 888 / 2713----
경인전자(009140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경인전자 crawled / 889 / 2713----
SMART KRX300(292500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SMART KRX300 crawled / 890 / 2713----
TIGER 미국MSCI리츠(합성 H)(182480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국MSCI리츠(합성 H) crawled / 891 / 2713----
지코(010580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지코 crawled / 892 / 2713----
케이탑리츠(145270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이탑리츠 crawled / 893 / 2713----
호텔신라우(008775)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 호텔신라우 crawled / 894 / 2713----
티에이치엔(019180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티에이치엔 crawled / 895 / 2713----
KOSEF 국고채3년(114470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 국고채3년 crawled / 896 / 2713----
한국전자홀딩스(006200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국전자홀딩스 crawled / 897 / 2713----
KINDEX 삼성그룹섹터가중(108450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 삼성그룹섹터가중 crawled / 898 / 2713----
TIGER 국채3년(114820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 국채3년 crawled / 899 / 2713----
KODEX 배당성장(211900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 배당성장 crawled / 900 / 2713----
신한 레버리지 다우존스지수 선물 ETN(H)(500020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 레버리지 다우존스지수 선물 ETN(H) crawled / 901 / 2713----
메디플란트(015540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메디플란트 crawled / 902 / 2713----
한솔로지스틱스(009180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔로지스틱스 crawled / 903 / 2713----
엔케이물산(009810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔케이물산 crawled / 904 / 2713----
파워 단기채(226810)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파워 단기채 crawled / 905 / 2713----
미래에셋 전기전자 Core5 ETN(520004)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 전기전자 Core5 ETN crawled / 906 / 2713----
동원수산(030720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동원수산 crawled / 907 / 2713----
한성기업(003680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한성기업 crawled / 908 / 2713----
KODEX 삼성그룹밸류(213610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 삼성그룹밸류 crawled / 909 / 2713----
QV 레버리지 WTI원유 선물 ETN(H)(550042)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 레버리지 WTI원유 선물 ETN(H) crawled / 910 / 2713----
진양산업(003780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진양산업 crawled / 911 / 2713----
QV 2차전지 테마 ETN(550020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 2차전지 테마 ETN crawled / 912 / 2713----
KBSTAR 200선물레버리지(252400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200선물레버리지 crawled / 913 / 2713----
삼아알미늄(006110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼아알미늄 crawled / 914 / 2713----
TIGER 반도체(091230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 반도체 crawled / 915 / 2713----
ARIRANG 신흥국MSCI(합성 H)(195980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 신흥국MSCI(합성 H) crawled / 916 / 2713----
신풍제지(002870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신풍제지 crawled / 917 / 2713----
삼성 레버리지 China A50 선물 ETN(H)(530023)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 레버리지 China A50 선물 ETN(H) crawled / 918 / 2713----
삼영화학(003720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼영화학 crawled / 919 / 2713----
QV 하드웨어 TOP5 ETN(550009)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 하드웨어 TOP5 ETN crawled / 920 / 2713----
신한 USD K200 선물 바이셀 ETN(500002)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 USD K200 선물 바이셀 ETN crawled / 921 / 2713----
남양유업우(003925)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남양유업우 crawled / 922 / 2713----
씨아이테크(004920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨아이테크 crawled / 923 / 2713----
KBSTAR 모멘텀로우볼(252730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 모멘텀로우볼 crawled / 924 / 2713----
TIGER 우선주(261140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 우선주 crawled / 925 / 2713----
TIGER 200 에너지화학(139250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 에너지화학 crawled / 926 / 2713----
TIGER 배당성장(211560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-16 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 배당성장 crawled / 927 / 2713----
FOCUS ESG리더스(285690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- FOCUS ESG리더스 crawled / 928 / 2713----
세기상사(002420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세기상사 crawled / 929 / 2713----
전방(000950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 전방 crawled / 930 / 2713----
TIGER 유로스탁스50(합성 H)(195930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 유로스탁스50(합성 H) crawled / 931 / 2713----
신한(005450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 crawled / 932 / 2713----
TIGER 단기선진하이일드(합성 H)(182490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 단기선진하이일드(합성 H) crawled / 933 / 2713----
TIGER 일본TOPIX(합성 H)(195920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 일본TOPIX(합성 H) crawled / 934 / 2713----
체시스(033250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 체시스 crawled / 935 / 2713----
하이골드12호(172580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이골드12호 crawled / 936 / 2713----
이스타코(015020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이스타코 crawled / 937 / 2713----
BYC우(001465)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- BYC우 crawled / 938 / 2713----
넥센타이어1우B(002355)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥센타이어1우B crawled / 939 / 2713----
TIGER 로우볼(174350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 로우볼 crawled / 940 / 2713----
미래에셋 레버리지 S&P500 ETN(H)(590010)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 레버리지 S&P500 ETN(H) crawled / 941 / 2713----
미래에셋 에너지화학 Core5 ETN(520006)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 에너지화학 Core5 ETN crawled / 942 / 2713----
삼성 바이오 테마주 ETN(530005)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 바이오 테마주 ETN crawled / 943 / 2713----
삼성 화학 테마주 ETN(530012)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 화학 테마주 ETN crawled / 944 / 2713----
TIGER 베타플러스(170350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 베타플러스 crawled / 945 / 2713----
ARIRANG 단기우량채권(263190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 단기우량채권 crawled / 946 / 2713----
미래에셋 미국 항공우주 ETN(H)(590009)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미국 항공우주 ETN(H) crawled / 947 / 2713----
유안타증권우(003475)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유안타증권우 crawled / 948 / 2713----
KOSEF 통안채1년(122260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 통안채1년 crawled / 949 / 2713----
미래에셋 레버리지 원유선물혼합 ETN(H)(520009)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 레버리지 원유선물혼합 ETN(H) crawled / 950 / 2713----
하나니켈1호(099340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나니켈1호 crawled / 951 / 2713----
트러스제7호(140890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 트러스제7호 crawled / 952 / 2713----
KODEX 미국S&P500선물(H)(219480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국S&P500선물(H) crawled / 953 / 2713----
태원물산(001420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태원물산 crawled / 954 / 2713----
미래에셋 Q150 Core5 ETN(520013)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 Q150 Core5 ETN crawled / 955 / 2713----
미래에셋 미디어엔터 Core5 ETN(520014)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미디어엔터 Core5 ETN crawled / 956 / 2713----
TIGER 코스닥150IT(261060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스닥150IT crawled / 957 / 2713----
KOSEF 미국달러선물 인버스2X(합성)(230480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 미국달러선물 인버스2X(합성) crawled / 958 / 2713----
QV 에너지 TOP5 ETN(550005)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 에너지 TOP5 ETN crawled / 959 / 2713----
부산주공(005030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부산주공 crawled / 960 / 2713----
미래에셋 원자재 선물 ETN(H)(520003)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 원자재 선물 ETN(H) crawled / 961 / 2713----
삼성 K200 Call 1807-02 ETN(530035)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 K200 Call 1807-02 ETN crawled / 962 / 2713----
TRUE 위안화 중국5년국채 ETN(570007)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 위안화 중국5년국채 ETN crawled / 963 / 2713----
TIGER 레버리지(123320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 레버리지 crawled / 964 / 2713----
신한 구리 선물 ETN(H)(500018)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 구리 선물 ETN(H) crawled / 965 / 2713----
삼성 K200 Call 1811-01 ETN(530039)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 K200 Call 1811-01 ETN crawled / 966 / 2713----
모두투어리츠(204210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모두투어리츠 crawled / 967 / 2713----
TIGER 코스닥150선물인버스(250780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스닥150선물인버스 crawled / 968 / 2713----
신한 다우존스지수 선물 ETN(H)(500009)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 다우존스지수 선물 ETN(H) crawled / 969 / 2713----
한국주강(025890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국주강 crawled / 970 / 2713----
대신 2X 니켈선물 ETN(H)(510007)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 2X 니켈선물 ETN(H) crawled / 971 / 2713----
한솔PNS(010420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔PNS crawled / 972 / 2713----
신한 인버스 천연가스 선물 ETN(H)(500022)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 천연가스 선물 ETN(H) crawled / 973 / 2713----
KODEX MSCI밸류(275290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX MSCI밸류 crawled / 974 / 2713----
미래에셋 원유선물혼합 ETN(H)(520010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 원유선물혼합 ETN(H) crawled / 975 / 2713----
진양화학(051630)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진양화학 crawled / 976 / 2713----
미래에셋 차이나 대표주 15 ETN(H)(520002)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 0
총 0개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 0
---- 미래에셋 차이나 대표주 15 ETN(H) crawled / 977 / 2713----
미래에셋 일본 대형주 ETN(H)(590005)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 일본 대형주 ETN(H) crawled / 978 / 2713----
삼성 China A50 선물 ETN(H)(530014)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 China A50 선물 ETN(H) crawled / 979 / 2713----
QV 화학 TOP5 ETN(550013)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 화학 TOP5 ETN crawled / 980 / 2713----
신화실업(001770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신화실업 crawled / 981 / 2713----
KOSEF 200선물레버리지(253250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 200선물레버리지 crawled / 982 / 2713----
미래에셋 일본 중형주 ETN(H)(590006)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 일본 중형주 ETN(H) crawled / 983 / 2713----
세방우(004365)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세방우 crawled / 984 / 2713----
KODEX 은선물(H)(144600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 은선물(H) crawled / 985 / 2713----
미래에셋 미국 대형주 ETN(H)(590007)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미국 대형주 ETN(H) crawled / 986 / 2713----
QV 소프트웨어 TOP5 ETN(550008)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 소프트웨어 TOP5 ETN crawled / 987 / 2713----
신한 인버스 2X WTI원유 선물 ETN(H)(500027)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 2X WTI원유 선물 ETN(H) crawled / 988 / 2713----
TIGER 화학(157520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 화학 crawled / 989 / 2713----
삼성 미국 대형 성장주 ETN(H)(530015)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미국 대형 성장주 ETN(H) crawled / 990 / 2713----
미래에셋 미국 중형주 ETN(H)(590008)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미국 중형주 ETN(H) crawled / 991 / 2713----
원익QnC(074600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원익QnC crawled / 992 / 2713----
QV KTOP30 ETN(550026)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV KTOP30 ETN crawled / 993 / 2713----
QV 전기차 테마 ETN(550019)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 전기차 테마 ETN crawled / 994 / 2713----
하이트론(019490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이트론 crawled / 995 / 2713----
TIGER 200에너지화학레버리지(243890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200에너지화학레버리지 crawled / 996 / 2713----
QV 대체에너지 테마 ETN(550029)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 대체에너지 테마 ETN crawled / 997 / 2713----
TREX 200(108590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TREX 200 crawled / 998 / 2713----
삼성 미국 중소형 성장주 ETN(H)(530017)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미국 중소형 성장주 ETN(H) crawled / 999 / 2713----
삼성 미국 대형 가치주 ETN(H)(530016)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미국 대형 가치주 ETN(H) crawled / 1000 / 2713----
TRUE 목표변동성20 코스피선물 ETN(570005)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 목표변동성20 코스피선물 ETN crawled / 1001 / 2713----
SK디스커버리우(006125)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK디스커버리우 crawled / 1002 / 2713----
KB 우량주 Monthly Best 11 ETN(580005)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KB 우량주 Monthly Best 11 ETN crawled / 1003 / 2713----
삼성 미국 중소형 가치주 ETN(H)(530018)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미국 중소형 가치주 ETN(H) crawled / 1004 / 2713----
KOSEF 200 선물(152280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 200 선물 crawled / 1005 / 2713----
FOCUS KRX300(292730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- FOCUS KRX300 crawled / 1006 / 2713----
코오롱우(002025)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱우 crawled / 1007 / 2713----
ARIRANG 고배당저변동50(251590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 고배당저변동50 crawled / 1008 / 2713----
KINDEX 인도네시아MSCI(합성)(256440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 인도네시아MSCI(합성) crawled / 1009 / 2713----
TRUE 다우존스 지속가능경영 코리아 ETN(570015)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 다우존스 지속가능경영 코리아 ETN crawled / 1010 / 2713----
삼성 미국 대형 성장주 ETN(530019)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미국 대형 성장주 ETN crawled / 1011 / 2713----
KODEX KTOP30(229720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX KTOP30 crawled / 1012 / 2713----
청호컴넷(012600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 청호컴넷 crawled / 1013 / 2713----
일정실업(008500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일정실업 crawled / 1014 / 2713----
ARIRANG 중형주저변동50(266550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 중형주저변동50 crawled / 1015 / 2713----
하이골드3호(153360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이골드3호 crawled / 1016 / 2713----
삼성 Cushing 에너지인프라 MLP ETN(530032)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 Cushing 에너지인프라 MLP ETN crawled / 1017 / 2713----
미래에셋 중국 심천 100 ETN(590018)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 중국 심천 100 ETN crawled / 1018 / 2713----
TRUE 섹터탑픽 ETN(570008)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 섹터탑픽 ETN crawled / 1019 / 2713----
TRUE 빅5 동일가중 ETN(570003)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 빅5 동일가중 ETN crawled / 1020 / 2713----
미래에셋 일본 바이백 ETN(H)(590002)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 일본 바이백 ETN(H) crawled / 1021 / 2713----
신한 천연가스 선물 ETN(H)(500021)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 천연가스 선물 ETN(H) crawled / 1022 / 2713----
KODEX MSCI KOREA ESG유니버설(289040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX MSCI KOREA ESG유니버설 crawled / 1023 / 2713----
삼성 미국 중소형 성장주 ETN(530021)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미국 중소형 성장주 ETN crawled / 1024 / 2713----
삼성 Alerian 에너지인프라 MLP ETN(530033)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 Alerian 에너지인프라 MLP ETN crawled / 1025 / 2713----
삼성 미국 대형 가치주 ETN(530020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미국 대형 가치주 ETN crawled / 1026 / 2713----
삼성 인버스 2X WTI원유 선물 ETN(530036)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 인버스 2X WTI원유 선물 ETN crawled / 1027 / 2713----
미래에셋 유럽 중형주 ETN(H)(590004)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 유럽 중형주 ETN(H) crawled / 1028 / 2713----
QV 자동차 TOP5 ETN(550011)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 자동차 TOP5 ETN crawled / 1029 / 2713----
미래에셋 유럽 대형주 ETN(H)(590003)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 유럽 대형주 ETN(H) crawled / 1030 / 2713----
KODEX 모멘텀Plus(244620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 모멘텀Plus crawled / 1031 / 2713----
신한 인버스 옥수수 선물 ETN(H)(500014)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 옥수수 선물 ETN(H) crawled / 1032 / 2713----
삼성 미국 중소형 가치주 ETN(530022)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미국 중소형 가치주 ETN crawled / 1033 / 2713----
신한 인버스 2X 은 선물 ETN(H)(500030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 2X 은 선물 ETN(H) crawled / 1034 / 2713----
미래에셋 미국 고배당주 ETN(H)(590017)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미국 고배당주 ETN(H) crawled / 1035 / 2713----
QV 고령화 테마 ETN(550023)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 고령화 테마 ETN crawled / 1036 / 2713----
QV 롱숏 K150 매수 로우볼 매도 ETN(550004)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 롱숏 K150 매수 로우볼 매도 ETN crawled / 1037 / 2713----
QV OLED 테마 ETN(550030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV OLED 테마 ETN crawled / 1038 / 2713----
KODEX 미국S&P고배당커버드콜(합성 H)(276970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국S&P고배당커버드콜(합성 H) crawled / 1039 / 2713----
미래에셋 호주 ASX200 ETN(H)(520012)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 호주 ASX200 ETN(H) crawled / 1040 / 2713----
KTOP 코스피50(168300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KTOP 코스피50 crawled / 1041 / 2713----
신한 금 선물 ETN(H)(500016)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 금 선물 ETN(H) crawled / 1042 / 2713----
TRUE 인버스 엔선물 ETN(570012)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 인버스 엔선물 ETN crawled / 1043 / 2713----
KINDEX 중기국고채(114460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 중기국고채 crawled / 1044 / 2713----
QV 수자원 테마 ETN(550024)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 수자원 테마 ETN crawled / 1045 / 2713----
TRUE 코리아프리미어 ETN(570009)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 코리아프리미어 ETN crawled / 1046 / 2713----
ARIRANG ESG우수기업(278420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG ESG우수기업 crawled / 1047 / 2713----
마이다스 200커버드콜5%OTM(137930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마이다스 200커버드콜5%OTM crawled / 1048 / 2713----
KINDEX 골드선물 레버리지(합성 H)(225130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 골드선물 레버리지(합성 H) crawled / 1049 / 2713----
미래에셋 미국 헬스케어 ETN(H)(590016)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미국 헬스케어 ETN(H) crawled / 1050 / 2713----
대신 인버스 철광석 선물 ETN(H)(510009)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 인버스 철광석 선물 ETN(H) crawled / 1051 / 2713----
신한 인버스 2X 천연가스 선물 ETN(H)(500032)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 2X 천연가스 선물 ETN(H) crawled / 1052 / 2713----
QV 핀테크 테마 ETN(550021)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 핀테크 테마 ETN crawled / 1053 / 2713----
KINDEX 중국본토CSI300레버리지(합성)(219900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 중국본토CSI300레버리지(합성) crawled / 1054 / 2713----
KODEX 반도체(091160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 반도체 crawled / 1055 / 2713----
KODEX 글로벌4차산업로보틱스(합성)(276990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 글로벌4차산업로보틱스(합성) crawled / 1056 / 2713----
QV 레버리지 S&P500 ETN(550044)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 레버리지 S&P500 ETN crawled / 1057 / 2713----
TIGER 미국다우존스30(245340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국다우존스30 crawled / 1058 / 2713----
마이티 코스피고배당(211210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마이티 코스피고배당 crawled / 1059 / 2713----
TIGER 생활필수품(152180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 생활필수품 crawled / 1060 / 2713----
TRUE 인버스 유로선물 ETN(570014)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 인버스 유로선물 ETN crawled / 1061 / 2713----
신한 인버스 달러인덱스 선물 ETN(H)(500012)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 달러인덱스 선물 ETN(H) crawled / 1062 / 2713----
파워 코스피100(140950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파워 코스피100 crawled / 1063 / 2713----
대신 2X 아연선물 ETN(H)(510005)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 2X 아연선물 ETN(H) crawled / 1064 / 2713----
미래에셋 미국 시니어론 100 ETN(H)(520020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미국 시니어론 100 ETN(H) crawled / 1065 / 2713----
삼성 인버스 2X 천연가스 선물 ETN(530038)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 인버스 2X 천연가스 선물 ETN crawled / 1066 / 2713----
마이티 200커버드콜ATM레버리지(292340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마이티 200커버드콜ATM레버리지 crawled / 1067 / 2713----
KODEX 200동일가중(252650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 200동일가중 crawled / 1068 / 2713----
신한 은 선물 ETN(H)(500017)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 은 선물 ETN(H) crawled / 1069 / 2713----
신한 콩 선물 ETN(H)(500023)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 콩 선물 ETN(H) crawled / 1070 / 2713----
QV 인버스 레버리지 10년 국채선물 ETN(550047)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 인버스 레버리지 10년 국채선물 ETN crawled / 1071 / 2713----
KODEX 배당성장채권혼합(237370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 배당성장채권혼합 crawled / 1072 / 2713----
신한 인버스 콩 선물 ETN(H)(500024)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 콩 선물 ETN(H) crawled / 1073 / 2713----
삼성 증권 테마주 ETN(530009)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 증권 테마주 ETN crawled / 1074 / 2713----
하이트진로2우B(000087)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이트진로2우B crawled / 1075 / 2713----
QV 제약 TOP5 ETN(550015)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 제약 TOP5 ETN crawled / 1076 / 2713----
미래에셋 글로벌 리츠 ETN(H)(590012)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 글로벌 리츠 ETN(H) crawled / 1077 / 2713----
미래에셋 미국 시니어론 100 ETN(520021)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미국 시니어론 100 ETN crawled / 1078 / 2713----
KODEX 퀄리티Plus(244660)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 퀄리티Plus crawled / 1079 / 2713----
TRUE 유로선물 ETN(570013)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 유로선물 ETN crawled / 1080 / 2713----
삼성 미디어 테마주 ETN(530008)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 미디어 테마주 ETN crawled / 1081 / 2713----
TIGER 미국나스닥100(133690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국나스닥100 crawled / 1082 / 2713----
파워 스마트밸류(275540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파워 스마트밸류 crawled / 1083 / 2713----
캔서롭(180400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 캔서롭 crawled / 1084 / 2713----
TIGER 소프트웨어(157490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 소프트웨어 crawled / 1085 / 2713----
대덕GDS우(004135)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대덕GDS우 crawled / 1086 / 2713----
TIGER 가격조정(217790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 가격조정 crawled / 1087 / 2713----
신한 달러인덱스 선물 ETN(H)(500011)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 달러인덱스 선물 ETN(H) crawled / 1088 / 2713----
KOSEF 코스닥150선물(291610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 코스닥150선물 crawled / 1089 / 2713----
QV 내수소비 TOP5 ETN(550006)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 내수소비 TOP5 ETN crawled / 1090 / 2713----
QV 스마트리밸런싱 250/3 ETN(550003)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 스마트리밸런싱 250/3 ETN crawled / 1091 / 2713----
TIGER 증권(157500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 증권 crawled / 1092 / 2713----
QV 건설 TOP5 ETN(550016)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 건설 TOP5 ETN crawled / 1093 / 2713----
KODEX 헬스케어(266420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 헬스케어 crawled / 1094 / 2713----
KOSEF 국고채10년(148070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 국고채10년 crawled / 1095 / 2713----
KODEX 건설(117700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 건설 crawled / 1096 / 2713----
신한 인버스 WTI원유 선물 ETN(H)(500003)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 WTI원유 선물 ETN(H) crawled / 1097 / 2713----
삼성 온라인쇼핑 테마주 ETN(530011)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 온라인쇼핑 테마주 ETN crawled / 1098 / 2713----
QV 조선 TOP5 ETN(550007)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 조선 TOP5 ETN crawled / 1099 / 2713----
KOSEF 코스닥150선물레버리지(291630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 코스닥150선물레버리지 crawled / 1100 / 2713----
KODEX 미국달러선물(261240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국달러선물 crawled / 1101 / 2713----
KODEX 코스피100(237350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 코스피100 crawled / 1102 / 2713----
파워 고배당저변동성(192720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파워 고배당저변동성 crawled / 1103 / 2713----
미래에셋 미국 리츠 ETN(H)(590013)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 미국 리츠 ETN(H) crawled / 1104 / 2713----
대신 철광석 선물 ETN(H)(510008)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 철광석 선물 ETN(H) crawled / 1105 / 2713----
QV 인버스 레버리지 S&P500 ETN(550045)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 인버스 레버리지 S&P500 ETN crawled / 1106 / 2713----
하이골드8호(159650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이골드8호 crawled / 1107 / 2713----
녹십자홀딩스2우(005257)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 녹십자홀딩스2우 crawled / 1108 / 2713----
TRUE 엔선물 ETN(570010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 엔선물 ETN crawled / 1109 / 2713----
QV 운송 TOP5 ETN(550010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 운송 TOP5 ETN crawled / 1110 / 2713----
국보(001140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국보 crawled / 1111 / 2713----
신한 브렌트원유 선물 ETN(H)(500004)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 브렌트원유 선물 ETN(H) crawled / 1112 / 2713----
대상우(001685)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대상우 crawled / 1113 / 2713----
신한 인버스 은 선물 ETN(H)(500007)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 은 선물 ETN(H) crawled / 1114 / 2713----
TIGER 200커버드콜ATM(289480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200커버드콜ATM crawled / 1115 / 2713----
QV 사물인터넷 테마 ETN(550022)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 사물인터넷 테마 ETN crawled / 1116 / 2713----
QV 스마트리밸런싱 260/4 ETN(550033)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 스마트리밸런싱 260/4 ETN crawled / 1117 / 2713----
TRUE 인버스 유로스탁스50 ETN(H)(570004)의 history 작업을 시작합니다.
DB에 TRUE 인버스 유로스탁스50 ETN(H)의 데이터가 아무것도 없습니다.
TRUE 인버스 유로스탁스50 ETN(H)(570004)는 더이상 유효한 종목이 아닌거 같습니다?
---- TRUE 인버스 유로스탁스50 ETN(H) crawled / 1118 / 2713----
신한 인버스 금 선물 ETN(H)(500006)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 금 선물 ETN(H) crawled / 1119 / 2713----
QV 항공우주 테마 ETN(550031)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 항공우주 테마 ETN crawled / 1120 / 2713----
진양폴리(010640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진양폴리 crawled / 1121 / 2713----
TIGER 경기방어채권혼합(237440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 경기방어채권혼합 crawled / 1122 / 2713----
KBSTAR 채권혼합(183700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 채권혼합 crawled / 1123 / 2713----
신한 인버스 구리 선물 ETN(H)(500008)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 구리 선물 ETN(H) crawled / 1124 / 2713----
QV HMR 테마 ETN(550025)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV HMR 테마 ETN crawled / 1125 / 2713----
신한 인버스 브렌트원유 선물 ETN(H)(500005)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 브렌트원유 선물 ETN(H) crawled / 1126 / 2713----
TIGER 200 건설(139220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 건설 crawled / 1127 / 2713----
에이리츠(140910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이리츠 crawled / 1128 / 2713----
KODEX 에너지화학(117460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 에너지화학 crawled / 1129 / 2713----
TRUE 인버스 차이나H ETN(H)(570006)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 인버스 차이나H ETN(H) crawled / 1130 / 2713----
한화케미칼우(009835)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화케미칼우 crawled / 1131 / 2713----
삼양사우(145995)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼양사우 crawled / 1132 / 2713----
대한항공우(003495)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한항공우 crawled / 1133 / 2713----
흥국 S&P코리아로우볼(215620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 흥국 S&P코리아로우볼 crawled / 1134 / 2713----
신한 레버리지 은 선물 ETN(H)(500029)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 레버리지 은 선물 ETN(H) crawled / 1135 / 2713----
넥센우(005725)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥센우 crawled / 1136 / 2713----
ARIRANG 주도업종(280920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 주도업종 crawled / 1137 / 2713----
TIGER 코스닥150바이오테크(261070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스닥150바이오테크 crawled / 1138 / 2713----
KOSEF 블루칩(104520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 블루칩 crawled / 1139 / 2713----
TIGER KRX100(091210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER KRX100 crawled / 1140 / 2713----
QV 농업 테마 ETN(550027)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 농업 테마 ETN crawled / 1141 / 2713----
TIGER 미국달러선물인버스2X(261120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국달러선물인버스2X crawled / 1142 / 2713----
KBSTAR 5대그룹주(105780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 5대그룹주 crawled / 1143 / 2713----
삼성 모멘텀 탑픽 ETN(530003)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 모멘텀 탑픽 ETN crawled / 1144 / 2713----
신한 옥수수 선물 ETN(H)(500013)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 옥수수 선물 ETN(H) crawled / 1145 / 2713----
삼양홀딩스우(000075)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼양홀딩스우 crawled / 1146 / 2713----
신한 인버스 2X 다우존스지수 선물 ETN(H)(500028)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 2X 다우존스지수 선물 ETN(H) crawled / 1147 / 2713----
QV 방위산업 테마 ETN(550032)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 방위산업 테마 ETN crawled / 1148 / 2713----
TRUE 레버리지 엔선물 ETN(570011)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 레버리지 엔선물 ETN crawled / 1149 / 2713----
ARIRANG 미국S&P500(H)(269540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 미국S&P500(H) crawled / 1150 / 2713----
미래에셋 인버스 S&P500 ETN(H)(590011)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 인버스 S&P500 ETN(H) crawled / 1151 / 2713----
TIGER 모멘텀(147970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 모멘텀 crawled / 1152 / 2713----
TIGER 이머징마켓MSCI레버리지(합성 H)(225060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 이머징마켓MSCI레버리지(합성 H) crawled / 1153 / 2713----
TIGER 미국S&P500레버리지(합성 H)(225040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국S&P500레버리지(합성 H) crawled / 1154 / 2713----
ARIRANG 고배당주채권혼합(251600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 고배당주채권혼합 crawled / 1155 / 2713----
KOSEF 고배당(104530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 고배당 crawled / 1156 / 2713----
KBSTAR 주식혼합(183710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 주식혼합 crawled / 1157 / 2713----
QV 의료 TOP5 ETN(550012)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 의료 TOP5 ETN crawled / 1158 / 2713----
삼성 레저 테마주 ETN(530007)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 레저 테마주 ETN crawled / 1159 / 2713----
TIGER 인도니프티50레버리지(합성)(236350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 인도니프티50레버리지(합성) crawled / 1160 / 2713----
KODEX 밸류Plus(244670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 밸류Plus crawled / 1161 / 2713----
SMART 선진국MSCI World(합성 H)(208470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SMART 선진국MSCI World(합성 H) crawled / 1162 / 2713----
삼성 인버스 China A50 선물 ETN(H)(530002)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 인버스 China A50 선물 ETN(H) crawled / 1163 / 2713----
TIGER 우량가치(227570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 우량가치 crawled / 1164 / 2713----
삼성 화장품 테마주 ETN(530004)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 화장품 테마주 ETN crawled / 1165 / 2713----
신한 인버스 다우존스지수 선물 ETN(H)(500010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 다우존스지수 선물 ETN(H) crawled / 1166 / 2713----
KODEX IT소프트웨어(266360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX IT소프트웨어 crawled / 1167 / 2713----
ARIRANG 바벨 채권(190150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 바벨 채권 crawled / 1168 / 2713----
NPC우(004255)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NPC우 crawled / 1169 / 2713----
KINDEX 밸류대형(143460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 밸류대형 crawled / 1170 / 2713----
KINDEX 레버리지(152500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 레버리지 crawled / 1171 / 2713----
SK증권우(001515)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK증권우 crawled / 1172 / 2713----
삼성 음식료 테마주 ETN(530006)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 음식료 테마주 ETN crawled / 1173 / 2713----
KODEX MSCI퀄리티(275300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX MSCI퀄리티 crawled / 1174 / 2713----
KODEX 바이오(244580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 바이오 crawled / 1175 / 2713----
TIGER 유로스탁스배당30(245350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 유로스탁스배당30 crawled / 1176 / 2713----
TIGER 일본니케이225(241180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 일본니케이225 crawled / 1177 / 2713----
KINDEX 코스닥(합성)(251890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 코스닥(합성) crawled / 1178 / 2713----
QV CHINEXT ETN(H)(550018)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV CHINEXT ETN(H) crawled / 1179 / 2713----
대신 WTI원유 선물 ETN(H)(510001)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 WTI원유 선물 ETN(H) crawled / 1180 / 2713----
신풍제약우(019175)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신풍제약우 crawled / 1181 / 2713----
미래에셋 인버스 미디어엔터 Core5 ETN(520015)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 인버스 미디어엔터 Core5 ETN crawled / 1182 / 2713----
KBSTAR 헬스케어(253280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 헬스케어 crawled / 1183 / 2713----
한국유리우(002005)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국유리우 crawled / 1184 / 2713----
TIGER 대만TAIEX선물(H)(253990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 대만TAIEX선물(H) crawled / 1185 / 2713----
KODEX 철강(117680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 철강 crawled / 1186 / 2713----
미래에셋 인버스 원유선물혼합 ETN(H)(520011)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 인버스 원유선물혼합 ETN(H) crawled / 1187 / 2713----
KOSEF 배당바이백Plus(260200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 배당바이백Plus crawled / 1188 / 2713----
KOSEF 저PBR가중(260270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 저PBR가중 crawled / 1189 / 2713----
KOSEF KRX100(100910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF KRX100 crawled / 1190 / 2713----
KOSEF 인도Nifty50(합성)(200250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 인도Nifty50(합성) crawled / 1191 / 2713----
KOSEF 미국달러선물인버스(139660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 미국달러선물인버스 crawled / 1192 / 2713----
KODEX 보험(140700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 보험 crawled / 1193 / 2713----
KODEX IT하드웨어(266370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX IT하드웨어 crawled / 1194 / 2713----
TIGER 200 헬스케어(227540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 헬스케어 crawled / 1195 / 2713----
한화투자증권우(003535)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화투자증권우 crawled / 1196 / 2713----
ARIRANG 스마트베타 Value(222180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 스마트베타 Value crawled / 1197 / 2713----
TIGER 미국달러선물레버리지(261110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국달러선물레버리지 crawled / 1198 / 2713----
코리아써우(007815)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코리아써우 crawled / 1199 / 2713----
KODEX 기계장비(102960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 기계장비 crawled / 1200 / 2713----
태영건설우(009415)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태영건설우 crawled / 1201 / 2713----
KODEX 성장투자(247790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 성장투자 crawled / 1202 / 2713----
미래에셋 인버스 에너지화학 Core5 ETN(520007)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 인버스 에너지화학 Core5 ETN crawled / 1203 / 2713----
KODEX 경기소비재(266390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 경기소비재 crawled / 1204 / 2713----
일양약품우(007575)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일양약품우 crawled / 1205 / 2713----
KODEX 자동차(091180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 자동차 crawled / 1206 / 2713----
TIGER 중소형성장(292130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 중소형성장 crawled / 1207 / 2713----
신한 MSCI 인도네시아 선물 ETN(H)(500025)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 MSCI 인도네시아 선물 ETN(H) crawled / 1208 / 2713----
TIGER 글로벌자원생산기업(합성 H)(276000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 글로벌자원생산기업(합성 H) crawled / 1209 / 2713----
KOSEF 200선물인버스2X(253230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 200선물인버스2X crawled / 1210 / 2713----
TIGER 코스피고배당(210780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스피고배당 crawled / 1211 / 2713----
TIGER 미디어컨텐츠(228810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미디어컨텐츠 crawled / 1212 / 2713----
KBSTAR 차이나HSCEI(H)(250730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 차이나HSCEI(H) crawled / 1213 / 2713----
KOSEF 코스피100(153270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 코스피100 crawled / 1214 / 2713----
TIGER 화장품(228790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 화장품 crawled / 1215 / 2713----
KBSTAR 지주회사(283930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 지주회사 crawled / 1216 / 2713----
태양금속우(004105)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태양금속우 crawled / 1217 / 2713----
ARIRANG 차이나H 레버리지(합성 H)(204420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 차이나H 레버리지(합성 H) crawled / 1218 / 2713----
TIGER 미국나스닥바이오(203780)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국나스닥바이오 crawled / 1219 / 2713----
TRUE 레버리지 S&P500 선물 ETN(H)(570022)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 레버리지 S&P500 선물 ETN(H) crawled / 1220 / 2713----
TIGER S&P글로벌헬스케어(합성)(248270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER S&P글로벌헬스케어(합성) crawled / 1221 / 2713----
TIGER 대형성장(292100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 대형성장 crawled / 1222 / 2713----
TRUE 레버리지 유로스탁스50 ETN(H)(570026)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 레버리지 유로스탁스50 ETN(H) crawled / 1223 / 2713----
TIGER MSCI KOREA ESG유니버설(289250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER MSCI KOREA ESG유니버설 crawled / 1224 / 2713----
KBSTAR V&S셀렉트밸류(234310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR V&S셀렉트밸류 crawled / 1225 / 2713----
KINDEX 러시아MSCI(합성)(265690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 러시아MSCI(합성) crawled / 1226 / 2713----
KOSEF 코스닥150선물인버스(291620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 코스닥150선물인버스 crawled / 1227 / 2713----
KODEX 최소변동성(279540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 최소변동성 crawled / 1228 / 2713----
KODEX 턴어라운드투자(247800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 턴어라운드투자 crawled / 1229 / 2713----
TRUE 코스피 커버드콜 ETN B(570020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 코스피 커버드콜 ETN B crawled / 1230 / 2713----
TIGER MSCI KOREA ESG리더스(289260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER MSCI KOREA ESG리더스 crawled / 1231 / 2713----
서울식품우(004415)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서울식품우 crawled / 1232 / 2713----
KBSTAR 미국장기국채선물인버스2X(합성 H)(267500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 미국장기국채선물인버스2X(합성 H) crawled / 1233 / 2713----
QV 레버리지 10년 국채선물 ETN(550046)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 레버리지 10년 국채선물 ETN crawled / 1234 / 2713----
TRUE 코스피 커버드풋 ETN B(570021)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 코스피 커버드풋 ETN B crawled / 1235 / 2713----
TIGER 중소형(292120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 중소형 crawled / 1236 / 2713----
KBSTAR 미국S&P원유생산기업(합성 H)(219390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 미국S&P원유생산기업(합성 H) crawled / 1237 / 2713----
TIGER 중소형가치(292140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 중소형가치 crawled / 1238 / 2713----
TIGER 미국S&P500선물인버스(H)(225030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 미국S&P500선물인버스(H) crawled / 1239 / 2713----
KBSTAR 수출주(140570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 수출주 crawled / 1240 / 2713----
TIGER 일본TOPIX헬스케어(합성)(248260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 일본TOPIX헬스케어(합성) crawled / 1241 / 2713----
KODEX MSCI모멘텀(275280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX MSCI모멘텀 crawled / 1242 / 2713----
미래에셋 인버스 전기전자 Core5 ETN(520005)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 인버스 전기전자 Core5 ETN crawled / 1243 / 2713----
TRUE 인버스 유로스탁스50 ETN(H) B(570025)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 인버스 유로스탁스50 ETN(H) B crawled / 1244 / 2713----
TIGER 대형가치(292110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 대형가치 crawled / 1245 / 2713----
KODEX S&P글로벌인프라(합성)(269420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX S&P글로벌인프라(합성) crawled / 1246 / 2713----
TIGER S&P글로벌인프라(합성)(269370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER S&P글로벌인프라(합성) crawled / 1247 / 2713----
TIGER 200커버드콜5%OTM(166400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200커버드콜5%OTM crawled / 1248 / 2713----
마이티 코스피100(159800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마이티 코스피100 crawled / 1249 / 2713----
TIGER 200 경기소비재(139290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 경기소비재 crawled / 1250 / 2713----
한화우(000885)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화우 crawled / 1251 / 2713----
KODEX 200미국채혼합(284430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 200미국채혼합 crawled / 1252 / 2713----
TRUE 인버스 2X 유로스탁스50 ETN(H)(570027)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 인버스 2X 유로스탁스50 ETN(H) crawled / 1253 / 2713----
KBSTAR 미국장기국채선물레버리지(합성 H)(267490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 미국장기국채선물레버리지(합성 H) crawled / 1254 / 2713----
TRUE 코스피 타겟볼20 ETN(570024)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 코스피 타겟볼20 ETN crawled / 1255 / 2713----
QV 인버스 레버리지 WTI원유 선물 ETN(H)(550043)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 인버스 레버리지 WTI원유 선물 ETN(H) crawled / 1256 / 2713----
유유제약1우(000225)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유유제약1우 crawled / 1257 / 2713----
TIGER TOP10(292150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER TOP10 crawled / 1258 / 2713----
KINDEX 스마트모멘텀(272220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 스마트모멘텀 crawled / 1259 / 2713----
KODEX 미국S&P에너지(합성)(218420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국S&P에너지(합성) crawled / 1260 / 2713----
KODEX 가치투자(247780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 가치투자 crawled / 1261 / 2713----
대신 니켈선물 ETN(H)(510003)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 니켈선물 ETN(H) crawled / 1262 / 2713----
TRUE 인버스 2X S&P500 선물 ETN(H)(570023)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TRUE 인버스 2X S&P500 선물 ETN(H) crawled / 1263 / 2713----
KINDEX 미국4차산업인터넷(합성 H)(280320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 미국4차산업인터넷(합성 H) crawled / 1264 / 2713----
KBSTAR 헬스케어채권혼합(253290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 헬스케어채권혼합 crawled / 1265 / 2713----
KODEX 미국S&P IT(합성)(200020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국S&P IT(합성) crawled / 1266 / 2713----
KINDEX 일본TOPIX인버스(합성 H)(205720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 일본TOPIX인버스(합성 H) crawled / 1267 / 2713----
신한 인버스 MSCI 인도네시아 선물 ETN(H)(500026)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 인버스 MSCI 인도네시아 선물 ETN(H) crawled / 1268 / 2713----
KODEX 미국S&P산업재(합성)(200030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국S&P산업재(합성) crawled / 1269 / 2713----
ARIRANG 미국나스닥기술주(287180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 미국나스닥기술주 crawled / 1270 / 2713----
KBSTAR 200선물인버스(252410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200선물인버스 crawled / 1271 / 2713----
ARIRANG 200선물레버리지(253150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 200선물레버리지 crawled / 1272 / 2713----
삼성 KQ150 Call 1901-01 ETN(530041)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 KQ150 Call 1901-01 ETN crawled / 1273 / 2713----
KINDEX 일본TOPIX레버리지(H)(196030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 일본TOPIX레버리지(H) crawled / 1274 / 2713----
KINDEX 스마트밸류(272230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 스마트밸류 crawled / 1275 / 2713----
대한제당우(001795)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한제당우 crawled / 1276 / 2713----
대원전선우(006345)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대원전선우 crawled / 1277 / 2713----
KINDEX 멕시코MSCI(합성)(291130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 멕시코MSCI(합성) crawled / 1278 / 2713----
TIGER 구리실물(160580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 구리실물 crawled / 1279 / 2713----
KODEX China H선물인버스(H)(291660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX China H선물인버스(H) crawled / 1280 / 2713----
KINDEX 일본Nikkei225(H)(238720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 일본Nikkei225(H) crawled / 1281 / 2713----
TIGER 유로스탁스레버리지(합성 H)(225050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 유로스탁스레버리지(합성 H) crawled / 1282 / 2713----
KINDEX 인버스(145670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 인버스 crawled / 1283 / 2713----
삼성 건축자재 테마주 ETN(530010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 건축자재 테마주 ETN crawled / 1284 / 2713----
TIGER 차이나항셍25(117690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 차이나항셍25 crawled / 1285 / 2713----
QV 미국 IT TOP5 ETN(H)(550041)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV 미국 IT TOP5 ETN(H) crawled / 1286 / 2713----
TREX 펀더멘탈 200(145850)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TREX 펀더멘탈 200 crawled / 1287 / 2713----
ARIRANG 미국다우존스고배당주(합성 H)(213630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 미국다우존스고배당주(합성 H) crawled / 1288 / 2713----
KBSTAR 글로벌4차산업IT(합성 H)(276650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 글로벌4차산업IT(합성 H) crawled / 1289 / 2713----
대신 아연선물 ETN(H)(510002)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 아연선물 ETN(H) crawled / 1290 / 2713----
TIGER 코스닥150로우볼(267300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스닥150로우볼 crawled / 1291 / 2713----
삼성 KQ150 Call 1901-02 ETN(530042)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 KQ150 Call 1901-02 ETN crawled / 1292 / 2713----
동북아13호(083380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동북아13호 crawled / 1293 / 2713----
동북아12호(083370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동북아12호 crawled / 1294 / 2713----
QV K200 Put 1904-01 ETN(550050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV K200 Put 1904-01 ETN crawled / 1295 / 2713----
TIGER 현대차그룹+펀더멘털(138540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 현대차그룹+펀더멘털 crawled / 1296 / 2713----
KOSEF 200선물인버스(253240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 200선물인버스 crawled / 1297 / 2713----
KODEX MSCI EM선물(H)(291890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX MSCI EM선물(H) crawled / 1298 / 2713----
QV K200 C-SP 1804-01 ETN(550034)의 history 작업을 시작합니다.
DB에 QV K200 C-SP 1804-01 ETN의 데이터가 아무것도 없습니다.
QV K200 C-SP 1804-01 ETN(550034)는 더이상 유효한 종목이 아닌거 같습니다?
---- QV K200 C-SP 1804-01 ETN crawled / 1299 / 2713----
KBSTAR 200건설(287300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200건설 crawled / 1300 / 2713----
KODEX 일본TOPIX100(101280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 일본TOPIX100 crawled / 1301 / 2713----
TIGER 200 생활소비재(227560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 생활소비재 crawled / 1302 / 2713----
삼성 KQ150 Call 1901-03 ETN(530043)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 KQ150 Call 1901-03 ETN crawled / 1303 / 2713----
ARIRANG 코스피100동일가중(141240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 코스피100동일가중 crawled / 1304 / 2713----
KBSTAR 200IT(285000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200IT crawled / 1305 / 2713----
QV K200 Condor 1805-01 ETN(550040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV K200 Condor 1805-01 ETN crawled / 1306 / 2713----
KODEX 미국달러선물인버스2X(261260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국달러선물인버스2X crawled / 1307 / 2713----
TIGER KTOP30(228820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER KTOP30 crawled / 1308 / 2713----
KODEX 3대농산물선물(H)(271060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 3대농산물선물(H) crawled / 1309 / 2713----
QV K200 C-SP 1805-01 ETN(550038)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV K200 C-SP 1805-01 ETN crawled / 1310 / 2713----
KBSTAR 코스닥150선물인버스(275750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 코스닥150선물인버스 crawled / 1311 / 2713----
미래에셋 K200 Call 1809-01 ETN(520022)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 K200 Call 1809-01 ETN crawled / 1312 / 2713----
TIGER 여행레저(228800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 여행레저 crawled / 1313 / 2713----
TIGER 원유선물인버스(H)(217770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 원유선물인버스(H) crawled / 1314 / 2713----
KOSEF 국고채10년레버리지(167860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KOSEF 국고채10년레버리지 crawled / 1315 / 2713----
미래에셋 K200 Call 1809-02 ETN(520023)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋 K200 Call 1809-02 ETN crawled / 1316 / 2713----
KBSTAR 200산업재(287320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200산업재 crawled / 1317 / 2713----
KBSTAR 200에너지화학(284990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200에너지화학 crawled / 1318 / 2713----
삼성 K200 Put 1903-01 ETN(530050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 K200 Put 1903-01 ETN crawled / 1319 / 2713----
삼성 KQ150 Put 1901-01 ETN(530044)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 KQ150 Put 1901-01 ETN crawled / 1320 / 2713----
KBSTAR 차이나H선물인버스(H)(291680)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 차이나H선물인버스(H) crawled / 1321 / 2713----
KBSTAR ESG사회책임투자(290130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR ESG사회책임투자 crawled / 1322 / 2713----
KINDEX 삼성그룹동일가중(131890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 삼성그룹동일가중 crawled / 1323 / 2713----
크라운해태홀딩스우(005745)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크라운해태홀딩스우 crawled / 1324 / 2713----
삼성 KQ150 Call 1903-01 ETN(530046)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 KQ150 Call 1903-01 ETN crawled / 1325 / 2713----
KBSTAR 200고배당커버드콜ATM(290080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200고배당커버드콜ATM crawled / 1326 / 2713----
KODEX WTI원유선물(H)(261220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX WTI원유선물(H) crawled / 1327 / 2713----
삼성 K200 Call 1903-01 ETN(530048)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 K200 Call 1903-01 ETN crawled / 1328 / 2713----
삼성 K200 Call 1807-01 ETN(530034)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 K200 Call 1807-01 ETN crawled / 1329 / 2713----
KINDEX 배당성장(211260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 배당성장 crawled / 1330 / 2713----
삼성 K200 Put 1903-02 ETN(530051)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 K200 Put 1903-02 ETN crawled / 1331 / 2713----
삼성 KQ150 Put 1901-02 ETN(530045)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 KQ150 Put 1901-02 ETN crawled / 1332 / 2713----
QV K200 P-SP 1805-01 ETN(550039)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV K200 P-SP 1805-01 ETN crawled / 1333 / 2713----
QV K200 P-SP 1804-01 ETN(550035)의 history 작업을 시작합니다.
DB에 QV K200 P-SP 1804-01 ETN의 데이터가 아무것도 없습니다.
QV K200 P-SP 1804-01 ETN(550035)는 더이상 유효한 종목이 아닌거 같습니다?
---- QV K200 P-SP 1804-01 ETN crawled / 1334 / 2713----
TIGER 지속배당(266140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 지속배당 crawled / 1335 / 2713----
SK네트웍스우(001745)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK네트웍스우 crawled / 1336 / 2713----
QV K200 Condor 1804-01 ETN(550037)의 history 작업을 시작합니다.
DB에 QV K200 Condor 1804-01 ETN의 데이터가 아무것도 없습니다.
QV K200 Condor 1804-01 ETN(550037)는 더이상 유효한 종목이 아닌거 같습니다?
---- QV K200 Condor 1804-01 ETN crawled / 1337 / 2713----
QV K200 Call 1904-01 ETN(550048)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV K200 Call 1904-01 ETN crawled / 1338 / 2713----
삼성 KQ150 Call 1903-02 ETN(530047)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 KQ150 Call 1903-02 ETN crawled / 1339 / 2713----
KODEX 심천ChiNext(합성)(256750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 심천ChiNext(합성) crawled / 1340 / 2713----
대신 인버스 아연선물 ETN(H)(510004)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 인버스 아연선물 ETN(H) crawled / 1341 / 2713----
신한 K200 C-SP 1812-01 ETN(500033)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한 K200 C-SP 1812-01 ETN crawled / 1342 / 2713----
ARIRANG 글로벌MSCI(합성 H)(189400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 글로벌MSCI(합성 H) crawled / 1343 / 2713----
삼성 K200 Call 1903-02 ETN(530049)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 K200 Call 1903-02 ETN crawled / 1344 / 2713----
QV K200 Call 1904-02 ETN(550049)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- QV K200 Call 1904-02 ETN crawled / 1345 / 2713----
크라운제과우(26490K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크라운제과우 crawled / 1346 / 2713----
KBSTAR 일본TOPIX레버리지(H)(196220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 일본TOPIX레버리지(H) crawled / 1347 / 2713----
KINDEX 미국다우존스리츠(합성 H)(181480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 미국다우존스리츠(합성 H) crawled / 1348 / 2713----
삼성 K200 Call 1811-02 ETN(530040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성 K200 Call 1811-02 ETN crawled / 1349 / 2713----
한진칼우(18064K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한진칼우 crawled / 1350 / 2713----
ARIRANG S&P한국배당성장(222170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG S&P한국배당성장 crawled / 1351 / 2713----
KBSTAR 200경기소비재(287310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200경기소비재 crawled / 1352 / 2713----
ARIRANG S&P글로벌인프라(269530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG S&P글로벌인프라 crawled / 1353 / 2713----
QV K200 Butterfly 1804-01 ETN(550036)의 history 작업을 시작합니다.
DB에 QV K200 Butterfly 1804-01 ETN의 데이터가 아무것도 없습니다.
QV K200 Butterfly 1804-01 ETN(550036)는 더이상 유효한 종목이 아닌거 같습니다?
---- QV K200 Butterfly 1804-01 ETN crawled / 1354 / 2713----
KBSTAR V&S셀렉트밸류채권혼합(241390)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR V&S셀렉트밸류채권혼합 crawled / 1355 / 2713----
금호산업우(002995)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금호산업우 crawled / 1356 / 2713----
KINDEX 골드선물 인버스2X(합성 H)(232590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 골드선물 인버스2X(합성 H) crawled / 1357 / 2713----
하나니켈2호(099350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나니켈2호 crawled / 1358 / 2713----
ARIRANG 국채선물10년(289670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 국채선물10년 crawled / 1359 / 2713----
ARIRANG 스마트베타Quality채권혼합(238670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 스마트베타Quality채권혼합 crawled / 1360 / 2713----
KINDEX 한류(226380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 한류 crawled / 1361 / 2713----
KBSTAR 미국장기국채선물인버스(H)(267450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 미국장기국채선물인버스(H) crawled / 1362 / 2713----
파워 중기국고채(176710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파워 중기국고채 crawled / 1363 / 2713----
대상홀딩스우(084695)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대상홀딩스우 crawled / 1364 / 2713----
동원시스템즈우(014825)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동원시스템즈우 crawled / 1365 / 2713----
KODEX 미국S&P바이오(합성)(185680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국S&P바이오(합성) crawled / 1366 / 2713----
KODEX 운송(140710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 운송 crawled / 1367 / 2713----
KINDEX 필리핀MSCI(합성)(261920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KINDEX 필리핀MSCI(합성) crawled / 1368 / 2713----
KBSTAR 미국장기국채선물(H)(267440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 미국장기국채선물(H) crawled / 1369 / 2713----
ARIRANG 선진국MSCI(합성 H)(195970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 선진국MSCI(합성 H) crawled / 1370 / 2713----
ARIRANG 스마트베타 LowVOL(236460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 스마트베타 LowVOL crawled / 1371 / 2713----
ARIRANG 스마트베타4종결합(244820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 스마트베타4종결합 crawled / 1372 / 2713----
KBSTAR 200철강소재(285020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200철강소재 crawled / 1373 / 2713----
KBSTAR 200생활소비재(287330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200생활소비재 crawled / 1374 / 2713----
KODEX 국채선물10년(152380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 국채선물10년 crawled / 1375 / 2713----
TIGER 200 중공업(139230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 중공업 crawled / 1376 / 2713----
쌍용양회우(003415)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쌍용양회우 crawled / 1377 / 2713----
KBSTAR 우량업종(140580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 우량업종 crawled / 1378 / 2713----
KODEX 구리선물(H)(138910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 구리선물(H) crawled / 1379 / 2713----
KODEX 미국S&P금융(합성)(200040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국S&P금융(합성) crawled / 1380 / 2713----
TREX 중소형가치(097750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TREX 중소형가치 crawled / 1381 / 2713----
KBSTAR 200중공업(285010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200중공업 crawled / 1382 / 2713----
KODEX 미국달러선물인버스(261270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국달러선물인버스 crawled / 1383 / 2713----
TIGER 은행(091220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 은행 crawled / 1384 / 2713----
TIGER LG그룹+펀더멘털(138530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER LG그룹+펀더멘털 crawled / 1385 / 2713----
TIGER 200 금융(139270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 금융 crawled / 1386 / 2713----
TIGER 라틴35(105010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 라틴35 crawled / 1387 / 2713----
ARIRANG 스마트베타 Quality(222200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 스마트베타 Quality crawled / 1388 / 2713----
대신 인버스 니켈선물 ETN(H)(510006)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신 인버스 니켈선물 ETN(H) crawled / 1389 / 2713----
TIGER 삼성그룹펀더멘털(138520)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 삼성그룹펀더멘털 crawled / 1390 / 2713----
TIGER 코스피대형주(277640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 코스피대형주 crawled / 1391 / 2713----
KODEX 독일MSCI(합성)(200050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 독일MSCI(합성) crawled / 1392 / 2713----
CJ씨푸드1우(011155)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ씨푸드1우 crawled / 1393 / 2713----
ARIRANG 스마트베타 Momentum(222190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 스마트베타 Momentum crawled / 1394 / 2713----
KODEX 미국러셀2000(H)(280930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 미국러셀2000(H) crawled / 1395 / 2713----
TIGER 방송통신(098560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 방송통신 crawled / 1396 / 2713----
깨끗한나라우(004545)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 깨끗한나라우 crawled / 1397 / 2713----
SMART 중국본토 중소형 CSI500(합성 H)(220130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SMART 중국본토 중소형 CSI500(합성 H) crawled / 1398 / 2713----
ARIRANG 심천차이넥스트(합성)(256450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 심천차이넥스트(합성) crawled / 1399 / 2713----
KBSTAR 200금융(284980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KBSTAR 200금융 crawled / 1400 / 2713----
동양우(001525)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양우 crawled / 1401 / 2713----
동부제철우(016385)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동부제철우 crawled / 1402 / 2713----
KODEX 골드선물인버스(H)(280940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 골드선물인버스(H) crawled / 1403 / 2713----
TIGER 금은선물(H)(139320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 금은선물(H) crawled / 1404 / 2713----
현대건설우(000725)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대건설우 crawled / 1405 / 2713----
코오롱글로벌우(003075)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱글로벌우 crawled / 1406 / 2713----
계양전기우(012205)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 계양전기우 crawled / 1407 / 2713----
한양증권우(001755)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한양증권우 crawled / 1408 / 2713----
성문전자우(014915)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성문전자우 crawled / 1409 / 2713----
삼성중공우(010145)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼성중공우 crawled / 1410 / 2713----
KODEX 콩선물(H)(138920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX 콩선물(H) crawled / 1411 / 2713----
현대비앤지스틸우(004565)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대비앤지스틸우 crawled / 1412 / 2713----
신원우(009275)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신원우 crawled / 1413 / 2713----
하이트진로홀딩스우(000145)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이트진로홀딩스우 crawled / 1414 / 2713----
흥국화재우(000545)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 흥국화재우 crawled / 1415 / 2713----
JW중외제약우(001065)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JW중외제약우 crawled / 1416 / 2713----
TIGER 200 철강소재(139240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 철강소재 crawled / 1417 / 2713----
TIGER 200 산업재(227550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 200 산업재 crawled / 1418 / 2713----
DB하이텍1우(000995)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DB하이텍1우 crawled / 1419 / 2713----
흥국화재2우B(000547)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 흥국화재2우B crawled / 1420 / 2713----
KODEX WTI원유선물인버스(H)(271050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KODEX WTI원유선물인버스(H) crawled / 1421 / 2713----
덕성우(004835)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덕성우 crawled / 1422 / 2713----
ARIRANG 200선물인버스2X(253160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ARIRANG 200선물인버스2X crawled / 1423 / 2713----
코리아써키트2우B(00781K)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코리아써키트2우B crawled / 1424 / 2713----
금강공업우(014285)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금강공업우 crawled / 1425 / 2713----
TIGER 금속선물(H)(139310)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 금속선물(H) crawled / 1426 / 2713----
노루페인트우(090355)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 노루페인트우 crawled / 1427 / 2713----
JW중외제약2우B(001067)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JW중외제약2우B crawled / 1428 / 2713----
TIGER 자동차(157510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TIGER 자동차 crawled / 1429 / 2713----
성신양회우(004985)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성신양회우 crawled / 1430 / 2713----
유유제약2우B(000227)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유유제약2우B crawled / 1431 / 2713----
동부건설우(005965)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동부건설우 crawled / 1432 / 2713----
노루홀딩스우(000325)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 노루홀딩스우 crawled / 1433 / 2713----
대한제당3우B(001799)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한제당3우B crawled / 1434 / 2713----
동양2우B(001527)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양2우B crawled / 1435 / 2713----
진흥기업우B(002785)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진흥기업우B crawled / 1436 / 2713----
남선알미우(008355)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남선알미우 crawled / 1437 / 2713----
성신양회2우B(004987)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성신양회2우B crawled / 1438 / 2713----
성신양회3우B(004989)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성신양회3우B crawled / 1439 / 2713----
진흥기업2우B(002787)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진흥기업2우B crawled / 1440 / 2713----
동양3우B(001529)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양3우B crawled / 1441 / 2713----
일성건설2우B(013367)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일성건설2우B crawled / 1442 / 2713----
셀트리온헬스케어(091990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 셀트리온헬스케어 crawled / 1443 / 2713----
신라젠(215600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신라젠 crawled / 1444 / 2713----
메디톡스(086900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메디톡스 crawled / 1445 / 2713----
바이로메드(084990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이로메드 crawled / 1446 / 2713----
CJ E&M(130960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ E&M crawled / 1447 / 2713----
에이치엘비(028300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이치엘비 crawled / 1448 / 2713----
펄어비스(263750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 펄어비스 crawled / 1449 / 2713----
셀트리온제약(068760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 셀트리온제약 crawled / 1450 / 2713----
코오롱티슈진(Reg.S)(950160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱티슈진(Reg.S) crawled / 1451 / 2713----
카카오M(016170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 카카오M crawled / 1452 / 2713----
휴젤(145020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴젤 crawled / 1453 / 2713----
스튜디오드래곤(253450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스튜디오드래곤 crawled / 1454 / 2713----
포스코켐텍(003670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포스코켐텍 crawled / 1455 / 2713----
제넥신(095700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제넥신 crawled / 1456 / 2713----
코미팜(041960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코미팜 crawled / 1457 / 2713----
컴투스(078340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 컴투스 crawled / 1458 / 2713----
파라다이스(034230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파라다이스 crawled / 1459 / 2713----
네이처셀(007390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네이처셀 crawled / 1460 / 2713----
SK머티리얼즈(036490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK머티리얼즈 crawled / 1461 / 2713----
나노스(151910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나노스 crawled / 1462 / 2713----
원익IPS(240810)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원익IPS crawled / 1463 / 2713----
안트로젠(065660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 안트로젠 crawled / 1464 / 2713----
CJ오쇼핑(035760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ오쇼핑 crawled / 1465 / 2713----
SKC코오롱PI(178920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SKC코오롱PI crawled / 1466 / 2713----
고영(098460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고영 crawled / 1467 / 2713----
카페24(042000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 카페24 crawled / 1468 / 2713----
차바이오텍(085660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 차바이오텍 crawled / 1469 / 2713----
지트리비앤티(115450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지트리비앤티 crawled / 1470 / 2713----
에스에프에이(056190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스에프에이 crawled / 1471 / 2713----
GS홈쇼핑(028150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GS홈쇼핑 crawled / 1472 / 2713----
텔콘(200230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 텔콘 crawled / 1473 / 2713----
소프트센(032680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 소프트센 crawled / 1474 / 2713----
서울반도체(046890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서울반도체 crawled / 1475 / 2713----
포스코 ICT(022100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포스코 ICT crawled / 1476 / 2713----
솔브레인(036830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 솔브레인 crawled / 1477 / 2713----
더블유게임즈(192080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 더블유게임즈 crawled / 1478 / 2713----
톱텍(108230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 톱텍 crawled / 1479 / 2713----
미래컴퍼니(049950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래컴퍼니 crawled / 1480 / 2713----
텍셀네트컴(038540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 텍셀네트컴 crawled / 1481 / 2713----
제일홀딩스(003380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제일홀딩스 crawled / 1482 / 2713----
메디포스트(078160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메디포스트 crawled / 1483 / 2713----
웹젠(069080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웹젠 crawled / 1484 / 2713----
코오롱생명과학(102940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코오롱생명과학 crawled / 1485 / 2713----
삼천당제약(000250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼천당제약 crawled / 1486 / 2713----
케어젠(214370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케어젠 crawled / 1487 / 2713----
엘앤에프(066970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘앤에프 crawled / 1488 / 2713----
씨젠(096530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨젠 crawled / 1489 / 2713----
콜마비앤에이치(200130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 콜마비앤에이치 crawled / 1490 / 2713----
이오테크닉스(039030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이오테크닉스 crawled / 1491 / 2713----
에코프로(086520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에코프로 crawled / 1492 / 2713----
제이콘텐트리(036420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이콘텐트리 crawled / 1493 / 2713----
티씨케이(064760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티씨케이 crawled / 1494 / 2713----
위메이드(112040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 위메이드 crawled / 1495 / 2713----
에스엠(041510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스엠 crawled / 1496 / 2713----
리노공업(058470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 리노공업 crawled / 1497 / 2713----
에스티팜(237690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스티팜 crawled / 1498 / 2713----
크리스탈(083790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크리스탈 crawled / 1499 / 2713----
동진쎄미켐(005290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동진쎄미켐 crawled / 1500 / 2713----
휴온스(243070)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴온스 crawled / 1501 / 2713----
오스코텍(039200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오스코텍 crawled / 1502 / 2713----
CMG제약(058820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CMG제약 crawled / 1503 / 2713----
휴온스글로벌(084110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴온스글로벌 crawled / 1504 / 2713----
엔지켐생명과학(183490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔지켐생명과학 crawled / 1505 / 2713----
오스템임플란트(048260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오스템임플란트 crawled / 1506 / 2713----
비에이치(090460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비에이치 crawled / 1507 / 2713----
인트론바이오(048530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인트론바이오 crawled / 1508 / 2713----
JYP Ent.(035900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JYP Ent. crawled / 1509 / 2713----
녹십자랩셀(144510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 녹십자랩셀 crawled / 1510 / 2713----
레고켐바이오(141080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 레고켐바이오 crawled / 1511 / 2713----
모두투어(080160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모두투어 crawled / 1512 / 2713----
녹십자셀(031390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 녹십자셀 crawled / 1513 / 2713----
제낙스(065620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제낙스 crawled / 1514 / 2713----
안랩(053800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 안랩 crawled / 1515 / 2713----
NICE평가정보(030190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NICE평가정보 crawled / 1516 / 2713----
프로스테믹스(203690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 프로스테믹스 crawled / 1517 / 2713----
KG이니시스(035600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KG이니시스 crawled / 1518 / 2713----
테스(095610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 테스 crawled / 1519 / 2713----
실리콘웍스(108320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 실리콘웍스 crawled / 1520 / 2713----
에이치엘비생명과학(067630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이치엘비생명과학 crawled / 1521 / 2713----
디오(039840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디오 crawled / 1522 / 2713----
인바디(041830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인바디 crawled / 1523 / 2713----
동국제약(086450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동국제약 crawled / 1524 / 2713----
나스미디어(089600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나스미디어 crawled / 1525 / 2713----
젬백스(082270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 젬백스 crawled / 1526 / 2713----
넥센테크(073070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥센테크 crawled / 1527 / 2713----
이녹스첨단소재(272290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이녹스첨단소재 crawled / 1528 / 2713----
클리오(237880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 클리오 crawled / 1529 / 2713----
에머슨퍼시픽(025980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에머슨퍼시픽 crawled / 1530 / 2713----
대화제약(067080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대화제약 crawled / 1531 / 2713----
매일유업(267980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 매일유업 crawled / 1532 / 2713----
바텍(043150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바텍 crawled / 1533 / 2713----
펩트론(087010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 펩트론 crawled / 1534 / 2713----
테고사이언스(191420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 테고사이언스 crawled / 1535 / 2713----
원익홀딩스(030530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원익홀딩스 crawled / 1536 / 2713----
와이지엔터테인먼트(122870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이지엔터테인먼트 crawled / 1537 / 2713----
JTC(950170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JTC crawled / 1538 / 2713----
메지온(140410)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메지온 crawled / 1539 / 2713----
와이지-원(019210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이지-원 crawled / 1540 / 2713----
파마리서치프로덕트(214450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파마리서치프로덕트 crawled / 1541 / 2713----
에이티젠(182400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이티젠 crawled / 1542 / 2713----
뉴트리바이오텍(222040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 뉴트리바이오텍 crawled / 1543 / 2713----
주성엔지니어링(036930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 주성엔지니어링 crawled / 1544 / 2713----
한국전자금융(063570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국전자금융 crawled / 1545 / 2713----
서부T&D(006730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서부T&D crawled / 1546 / 2713----
바이넥스(053030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이넥스 crawled / 1547 / 2713----
마크로젠(038290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마크로젠 crawled / 1548 / 2713----
인터플렉스(051370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인터플렉스 crawled / 1549 / 2713----
루트로닉(085370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 루트로닉 crawled / 1550 / 2713----
테라젠이텍스(066700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 테라젠이텍스 crawled / 1551 / 2713----
동화기업(025900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동화기업 crawled / 1552 / 2713----
피에스케이(031980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피에스케이 crawled / 1553 / 2713----
JW신약(067290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- JW신약 crawled / 1554 / 2713----
다우데이타(032190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 다우데이타 crawled / 1555 / 2713----
코웰패션(033290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코웰패션 crawled / 1556 / 2713----
한국정보통신(025770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국정보통신 crawled / 1557 / 2713----
유진기업(023410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유진기업 crawled / 1558 / 2713----
파트론(091700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파트론 crawled / 1559 / 2713----
유진테크(084370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유진테크 crawled / 1560 / 2713----
바디텍메드(206640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바디텍메드 crawled / 1561 / 2713----
알테오젠(196170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알테오젠 crawled / 1562 / 2713----
에스티큐브(052020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스티큐브 crawled / 1563 / 2713----
네오팜(092730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네오팜 crawled / 1564 / 2713----
에이스침대(003800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이스침대 crawled / 1565 / 2713----
이베스트투자증권(078020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이베스트투자증권 crawled / 1566 / 2713----
RFHIC(218410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- RFHIC crawled / 1567 / 2713----
게임빌(063080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 게임빌 crawled / 1568 / 2713----
CJ프레시웨이(051500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CJ프레시웨이 crawled / 1569 / 2713----
동원개발(013120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동원개발 crawled / 1570 / 2713----
앱클론(174900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 앱클론 crawled / 1571 / 2713----
덕산네오룩스(213420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덕산네오룩스 crawled / 1572 / 2713----
아트라스BX(023890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아트라스BX crawled / 1573 / 2713----
다원시스(068240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 다원시스 crawled / 1574 / 2713----
클래시스(214150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 클래시스 crawled / 1575 / 2713----
쎌바이오텍(049960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쎌바이오텍 crawled / 1576 / 2713----
넷게임즈(225570)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넷게임즈 crawled / 1577 / 2713----
에스디생명공학(217480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스디생명공학 crawled / 1578 / 2713----
연우(115960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 연우 crawled / 1579 / 2713----
인터로조(119610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인터로조 crawled / 1580 / 2713----
이지바이오(035810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이지바이오 crawled / 1581 / 2713----
휴메딕스(200670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴메딕스 crawled / 1582 / 2713----
대한광통신(010170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한광통신 crawled / 1583 / 2713----
네오위즈(095660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네오위즈 crawled / 1584 / 2713----
성우하이텍(015750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성우하이텍 crawled / 1585 / 2713----
이테크건설(016250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이테크건설 crawled / 1586 / 2713----
리더스코스메틱(016100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 리더스코스메틱 crawled / 1587 / 2713----
아이센스(099190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이센스 crawled / 1588 / 2713----
하나머티리얼즈(166090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나머티리얼즈 crawled / 1589 / 2713----
아모텍(052710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아모텍 crawled / 1590 / 2713----
아미코젠(092040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아미코젠 crawled / 1591 / 2713----
선데이토즈(123420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 선데이토즈 crawled / 1592 / 2713----
원익머트리얼즈(104830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원익머트리얼즈 crawled / 1593 / 2713----
아이리버(060570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이리버 crawled / 1594 / 2713----
메카로(241770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메카로 crawled / 1595 / 2713----
뷰웍스(100120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 뷰웍스 crawled / 1596 / 2713----
삼표시멘트(038500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼표시멘트 crawled / 1597 / 2713----
동구바이오제약(006620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동구바이오제약 crawled / 1598 / 2713----
홈캐스트(064240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 홈캐스트 crawled / 1599 / 2713----
모다이노칩(080420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모다이노칩 crawled / 1600 / 2713----
넥슨지티(041140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥슨지티 crawled / 1601 / 2713----
이수앱지스(086890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이수앱지스 crawled / 1602 / 2713----
바이오리더스(142760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이오리더스 crawled / 1603 / 2713----
씨티케이코스메틱스(260930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨티케이코스메틱스 crawled / 1604 / 2713----
한글과컴퓨터(030520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한글과컴퓨터 crawled / 1605 / 2713----
태웅(044490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태웅 crawled / 1606 / 2713----
세종텔레콤(036630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세종텔레콤 crawled / 1607 / 2713----
AP시스템(265520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- AP시스템 crawled / 1608 / 2713----
쇼박스(086980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쇼박스 crawled / 1609 / 2713----
테크윙(089030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 테크윙 crawled / 1610 / 2713----
우리기술투자(041190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리기술투자 crawled / 1611 / 2713----
와이아이케이(232140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이아이케이 crawled / 1612 / 2713----
아이진(185490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이진 crawled / 1613 / 2713----
대명코퍼레이션(007720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대명코퍼레이션 crawled / 1614 / 2713----
내츄럴엔도텍(168330)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 내츄럴엔도텍 crawled / 1615 / 2713----
아프리카TV(067160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아프리카TV crawled / 1616 / 2713----
NHN한국사이버결제(060250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NHN한국사이버결제 crawled / 1617 / 2713----
코스메카코리아(241710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코스메카코리아 crawled / 1618 / 2713----
SK바이오랜드(052260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK바이오랜드 crawled / 1619 / 2713----
케이엠더블유(032500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이엠더블유 crawled / 1620 / 2713----
경동제약(011040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경동제약 crawled / 1621 / 2713----
하림홀딩스(024660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하림홀딩스 crawled / 1622 / 2713----
SFA반도체(036540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SFA반도체 crawled / 1623 / 2713----
하이록코리아(013030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이록코리아 crawled / 1624 / 2713----
와이솔(122990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이솔 crawled / 1625 / 2713----
성광벤드(014620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성광벤드 crawled / 1626 / 2713----
큐렉소(060280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 큐렉소 crawled / 1627 / 2713----
태광(023160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태광 crawled / 1628 / 2713----
야스(255440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 야스 crawled / 1629 / 2713----
드림시큐리티(203650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 드림시큐리티 crawled / 1630 / 2713----
유니테스트(086390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니테스트 crawled / 1631 / 2713----
케어랩스(263700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케어랩스 crawled / 1632 / 2713----
우리산업(215360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리산업 crawled / 1633 / 2713----
파나진(046210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파나진 crawled / 1634 / 2713----
웨이브일렉트로(095270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웨이브일렉트로 crawled / 1635 / 2713----
비덴트(121800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비덴트 crawled / 1636 / 2713----
코아스템(166480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코아스템 crawled / 1637 / 2713----
에스에프씨(112240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스에프씨 crawled / 1638 / 2713----
제이브이엠(054950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이브이엠 crawled / 1639 / 2713----
슈피겐코리아(192440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 슈피겐코리아 crawled / 1640 / 2713----
위닉스(044340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 위닉스 crawled / 1641 / 2713----
레이언스(228850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 레이언스 crawled / 1642 / 2713----
SKC 솔믹스(057500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SKC 솔믹스 crawled / 1643 / 2713----
한스바이오메드(042520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한스바이오메드 crawled / 1644 / 2713----
에스맥(097780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스맥 crawled / 1645 / 2713----
썸에이지(208640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 썸에이지 crawled / 1646 / 2713----
큐로컴(040350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 큐로컴 crawled / 1647 / 2713----
하림(136480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하림 crawled / 1648 / 2713----
유니셈(036200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니셈 crawled / 1649 / 2713----
바이오톡스텍(086040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이오톡스텍 crawled / 1650 / 2713----
에스티아이(039440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스티아이 crawled / 1651 / 2713----
메가스터디교육(215200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메가스터디교육 crawled / 1652 / 2713----
제노포커스(187420)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제노포커스 crawled / 1653 / 2713----
파크시스템스(140860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파크시스템스 crawled / 1654 / 2713----
코리아나(027050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코리아나 crawled / 1655 / 2713----
지엔코(065060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지엔코 crawled / 1656 / 2713----
코미코(183300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코미코 crawled / 1657 / 2713----
셀루메드(049180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 셀루메드 crawled / 1658 / 2713----
민앤지(214180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 민앤지 crawled / 1659 / 2713----
골프존(215000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 골프존 crawled / 1660 / 2713----
비츠로셀(082920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비츠로셀 crawled / 1661 / 2713----
SM C&C(048550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SM C&C crawled / 1662 / 2713----
아스트(067390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아스트 crawled / 1663 / 2713----
인터파크(108790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인터파크 crawled / 1664 / 2713----
이엠텍(091120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이엠텍 crawled / 1665 / 2713----
에스엠코어(007820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스엠코어 crawled / 1666 / 2713----
넵튠(217270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넵튠 crawled / 1667 / 2713----
엠젠플러스(032790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엠젠플러스 crawled / 1668 / 2713----
바이오니아(064550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이오니아 crawled / 1669 / 2713----
강스템바이오텍(217730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 강스템바이오텍 crawled / 1670 / 2713----
KG모빌리언스(046440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KG모빌리언스 crawled / 1671 / 2713----
대한약품(023910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한약품 crawled / 1672 / 2713----
이엔에프테크놀로지(102710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이엔에프테크놀로지 crawled / 1673 / 2713----
시노펙스(025320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 시노펙스 crawled / 1674 / 2713----
미투온(201490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미투온 crawled / 1675 / 2713----
인콘(083640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인콘 crawled / 1676 / 2713----
동국S&C(100130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동국S&C crawled / 1677 / 2713----
씨티씨바이오(060590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨티씨바이오 crawled / 1678 / 2713----
지니뮤직(043610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지니뮤직 crawled / 1679 / 2713----
유니슨(018000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니슨 crawled / 1680 / 2713----
한양이엔지(045100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한양이엔지 crawled / 1681 / 2713----
인선이엔티(060150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인선이엔티 crawled / 1682 / 2713----
한국기업평가(034950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국기업평가 crawled / 1683 / 2713----
코엔텍(029960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코엔텍 crawled / 1684 / 2713----
지스마트글로벌(114570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지스마트글로벌 crawled / 1685 / 2713----
하이비젼시스템(126700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이비젼시스템 crawled / 1686 / 2713----
코스온(069110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코스온 crawled / 1687 / 2713----
대주전자재료(078600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대주전자재료 crawled / 1688 / 2713----
원풍물산(008290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원풍물산 crawled / 1689 / 2713----
파티게임즈(194510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파티게임즈 crawled / 1690 / 2713----
퓨쳐스트림네트웍스(214270)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 퓨쳐스트림네트웍스 crawled / 1691 / 2713----
넥스트아이(137940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥스트아이 crawled / 1692 / 2713----
뉴파워프라즈마(144960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 뉴파워프라즈마 crawled / 1693 / 2713----
HB테크놀러지(078150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- HB테크놀러지 crawled / 1694 / 2713----
NEW(160550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NEW crawled / 1695 / 2713----
골프존뉴딘(121440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 골프존뉴딘 crawled / 1696 / 2713----
테라세미콘(123100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 테라세미콘 crawled / 1697 / 2713----
에프티이앤이(065160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에프티이앤이 crawled / 1698 / 2713----
알파홀딩스(117670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알파홀딩스 crawled / 1699 / 2713----
와이엠티(251370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이엠티 crawled / 1700 / 2713----
아미노로직스(074430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아미노로직스 crawled / 1701 / 2713----
서진시스템(178320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서진시스템 crawled / 1702 / 2713----
다날(064260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 다날 crawled / 1703 / 2713----
비씨월드제약(200780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비씨월드제약 crawled / 1704 / 2713----
에스피지(058610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스피지 crawled / 1705 / 2713----
CSA 코스믹(083660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CSA 코스믹 crawled / 1706 / 2713----
뉴프라이드(900100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 뉴프라이드 crawled / 1707 / 2713----
ISC(095340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ISC crawled / 1708 / 2713----
진로발효(018120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진로발효 crawled / 1709 / 2713----
브이원텍(251630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 브이원텍 crawled / 1710 / 2713----
코디엠(224060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코디엠 crawled / 1711 / 2713----
안국약품(001540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 안국약품 crawled / 1712 / 2713----
코텍(052330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코텍 crawled / 1713 / 2713----
액션스퀘어(205500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 액션스퀘어 crawled / 1714 / 2713----
대한뉴팜(054670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한뉴팜 crawled / 1715 / 2713----
신흥에스이씨(243840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신흥에스이씨 crawled / 1716 / 2713----
상아프론테크(089980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 상아프론테크 crawled / 1717 / 2713----
금화피에스시(036190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금화피에스시 crawled / 1718 / 2713----
인크로스(216050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인크로스 crawled / 1719 / 2713----
해마로푸드서비스(220630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 해마로푸드서비스 crawled / 1720 / 2713----
케이피엠테크(042040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이피엠테크 crawled / 1721 / 2713----
사람인에이치알(143240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 사람인에이치알 crawled / 1722 / 2713----
서한(011370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서한 crawled / 1723 / 2713----
나이스정보통신(036800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나이스정보통신 crawled / 1724 / 2713----
해덕파워웨이(102210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 해덕파워웨이 crawled / 1725 / 2713----
피앤이솔루션(131390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피앤이솔루션 crawled / 1726 / 2713----
제룡전기(033100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제룡전기 crawled / 1727 / 2713----
예림당(036000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 예림당 crawled / 1728 / 2713----
농우바이오(054050)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 농우바이오 crawled / 1729 / 2713----
인피니트헬스케어(071200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인피니트헬스케어 crawled / 1730 / 2713----
SBI인베스트먼트(019550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SBI인베스트먼트 crawled / 1731 / 2713----
큐리언트(115180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 큐리언트 crawled / 1732 / 2713----
진성티이씨(036890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진성티이씨 crawled / 1733 / 2713----
키이스트(054780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 키이스트 crawled / 1734 / 2713----
엠케이전자(033160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엠케이전자 crawled / 1735 / 2713----
세운메디칼(100700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세운메디칼 crawled / 1736 / 2713----
오상자이엘(053980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오상자이엘 crawled / 1737 / 2713----
다나와(119860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 다나와 crawled / 1738 / 2713----
덱스터(206560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덱스터 crawled / 1739 / 2713----
한국알콜(017890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국알콜 crawled / 1740 / 2713----
KH바텍(060720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KH바텍 crawled / 1741 / 2713----
제이스텍(090470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이스텍 crawled / 1742 / 2713----
삼지전자(037460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼지전자 crawled / 1743 / 2713----
KTH(036030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KTH crawled / 1744 / 2713----
나노신소재(121600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나노신소재 crawled / 1745 / 2713----
현대아이비티(048410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대아이비티 crawled / 1746 / 2713----
에임하이(043580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에임하이 crawled / 1747 / 2713----
유바이오로직스(206650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유바이오로직스 crawled / 1748 / 2713----
엘컴텍(037950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘컴텍 crawled / 1749 / 2713----
유비케어(032620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유비케어 crawled / 1750 / 2713----
알리코제약(260660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알리코제약 crawled / 1751 / 2713----
메디프론(065650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메디프론 crawled / 1752 / 2713----
이노인스트루먼트(215790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이노인스트루먼트 crawled / 1753 / 2713----
오텍(067170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오텍 crawled / 1754 / 2713----
넥스트BT(065170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥스트BT crawled / 1755 / 2713----
유니테크노(241690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니테크노 crawled / 1756 / 2713----
에스에이엠티(031330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스에이엠티 crawled / 1757 / 2713----
에이티넘인베스트(021080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이티넘인베스트 crawled / 1758 / 2713----
아나패스(123860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아나패스 crawled / 1759 / 2713----
지엠피(018290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지엠피 crawled / 1760 / 2713----
휴맥스(115160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴맥스 crawled / 1761 / 2713----
매일홀딩스(005990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 매일홀딩스 crawled / 1762 / 2713----
동국산업(005160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동국산업 crawled / 1763 / 2713----
인터파크홀딩스(035080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인터파크홀딩스 crawled / 1764 / 2713----
액토즈소프트(052790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 액토즈소프트 crawled / 1765 / 2713----
심텍(222800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 심텍 crawled / 1766 / 2713----
예스티(122640)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 예스티 crawled / 1767 / 2713----
SBI핀테크솔루션즈(950110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SBI핀테크솔루션즈 crawled / 1768 / 2713----
경남제약(053950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경남제약 crawled / 1769 / 2713----
팬젠(222110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팬젠 crawled / 1770 / 2713----
SBS콘텐츠허브(046140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SBS콘텐츠허브 crawled / 1771 / 2713----
필링크(064800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 필링크 crawled / 1772 / 2713----
GRT(900290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GRT crawled / 1773 / 2713----
보광산업(225530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 보광산업 crawled / 1774 / 2713----
평화정공(043370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 평화정공 crawled / 1775 / 2713----
조아제약(034940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조아제약 crawled / 1776 / 2713----
엘아이에스(138690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘아이에스 crawled / 1777 / 2713----
동성화인텍(033500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동성화인텍 crawled / 1778 / 2713----
에프엔씨엔터(173940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에프엔씨엔터 crawled / 1779 / 2713----
대아티아이(045390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대아티아이 crawled / 1780 / 2713----
서희건설(035890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서희건설 crawled / 1781 / 2713----
신신제약(002800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신신제약 crawled / 1782 / 2713----
프로텍(053610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 프로텍 crawled / 1783 / 2713----
아이원스(114810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이원스 crawled / 1784 / 2713----
삼아제약(009300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼아제약 crawled / 1785 / 2713----
크루셜텍(114120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크루셜텍 crawled / 1786 / 2713----
지엘팜텍(204840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지엘팜텍 crawled / 1787 / 2713----
디에이치피코리아(131030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디에이치피코리아 crawled / 1788 / 2713----
티케이케미칼(104480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티케이케미칼 crawled / 1789 / 2713----
멀티캠퍼스(067280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 멀티캠퍼스 crawled / 1790 / 2713----
에스트래픽(234300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스트래픽 crawled / 1791 / 2713----
비아트론(141000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비아트론 crawled / 1792 / 2713----
이니텍(053350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이니텍 crawled / 1793 / 2713----
바이온(032980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이온 crawled / 1794 / 2713----
컬러레이(900310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 컬러레이 crawled / 1795 / 2713----
엘오티베큠(083310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘오티베큠 crawled / 1796 / 2713----
젬백스테크놀러지(041590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 젬백스테크놀러지 crawled / 1797 / 2713----
에스텍파마(041910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스텍파마 crawled / 1798 / 2713----
아우딘퓨쳐스(227610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아우딘퓨쳐스 crawled / 1799 / 2713----
한국정보인증(053300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국정보인증 crawled / 1800 / 2713----
네패스(033640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네패스 crawled / 1801 / 2713----
참좋은여행(094850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 참좋은여행 crawled / 1802 / 2713----
알에스오토메이션(140670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알에스오토메이션 crawled / 1803 / 2713----
에프앤리퍼블릭(064090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에프앤리퍼블릭 crawled / 1804 / 2713----
홈센타홀딩스(060560)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 홈센타홀딩스 crawled / 1805 / 2713----
루멘스(038060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 루멘스 crawled / 1806 / 2713----
아스타(246720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아스타 crawled / 1807 / 2713----
모트렉스(118990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모트렉스 crawled / 1808 / 2713----
도이치모터스(067990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 도이치모터스 crawled / 1809 / 2713----
매직마이크로(127160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 매직마이크로 crawled / 1810 / 2713----
다산네트웍스(039560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 다산네트웍스 crawled / 1811 / 2713----
에이프로젠 H&G(109960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이프로젠 H&G crawled / 1812 / 2713----
와이엠씨(155650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이엠씨 crawled / 1813 / 2713----
켐온(217600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 켐온 crawled / 1814 / 2713----
에이치엘사이언스(239610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이치엘사이언스 crawled / 1815 / 2713----
조이시티(067000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조이시티 crawled / 1816 / 2713----
삼양옵틱스(225190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼양옵틱스 crawled / 1817 / 2713----
아이씨디(040910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이씨디 crawled / 1818 / 2713----
닉스테크(222810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 닉스테크 crawled / 1819 / 2713----
삼보모터스(053700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼보모터스 crawled / 1820 / 2713----
삼목에스폼(018310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼목에스폼 crawled / 1821 / 2713----
인탑스(049070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인탑스 crawled / 1822 / 2713----
이크레더블(092130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이크레더블 crawled / 1823 / 2713----
보령메디앙스(014100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 보령메디앙스 crawled / 1824 / 2713----
솔본(035610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 솔본 crawled / 1825 / 2713----
바이오제네틱스(044480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이오제네틱스 crawled / 1826 / 2713----
아가방컴퍼니(013990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아가방컴퍼니 crawled / 1827 / 2713----
SIMPAC Metal(090730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SIMPAC Metal crawled / 1828 / 2713----
오가닉티코스메틱(900300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오가닉티코스메틱 crawled / 1829 / 2713----
한컴MDS(086960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한컴MDS crawled / 1830 / 2713----
아이쓰리시스템(214430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이쓰리시스템 crawled / 1831 / 2713----
텔레칩스(054450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 텔레칩스 crawled / 1832 / 2713----
코나아이(052400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코나아이 crawled / 1833 / 2713----
KG ETS(151860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KG ETS crawled / 1834 / 2713----
슈프리마(236200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 슈프리마 crawled / 1835 / 2713----
티에스이(131290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티에스이 crawled / 1836 / 2713----
유진로봇(056080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유진로봇 crawled / 1837 / 2713----
모다(149940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모다 crawled / 1838 / 2713----
리드코프(012700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 리드코프 crawled / 1839 / 2713----
라이온켐텍(171120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 라이온켐텍 crawled / 1840 / 2713----
로스웰(900260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 로스웰 crawled / 1841 / 2713----
제우스(079370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제우스 crawled / 1842 / 2713----
에스코넥(096630)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스코넥 crawled / 1843 / 2713----
쏠리드(050890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쏠리드 crawled / 1844 / 2713----
양지사(030960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 양지사 crawled / 1845 / 2713----
KCC건설(021320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KCC건설 crawled / 1846 / 2713----
DMS(068790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DMS crawled / 1847 / 2713----
KMH(122450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KMH crawled / 1848 / 2713----
엠씨넥스(097520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엠씨넥스 crawled / 1849 / 2713----
한국전자인증(041460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국전자인증 crawled / 1850 / 2713----
글로벌텍스프리(204620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 글로벌텍스프리 crawled / 1851 / 2713----
덕산하이메탈(077360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덕산하이메탈 crawled / 1852 / 2713----
헝셩그룹(900270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 헝셩그룹 crawled / 1853 / 2713----
우리손에프앤지(073560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리손에프앤지 crawled / 1854 / 2713----
레드로버(060300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 레드로버 crawled / 1855 / 2713----
로보스타(090360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 로보스타 crawled / 1856 / 2713----
데브시스터즈(194480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 데브시스터즈 crawled / 1857 / 2713----
아이디스홀딩스(054800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이디스홀딩스 crawled / 1858 / 2713----
서플러스글로벌(140070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서플러스글로벌 crawled / 1859 / 2713----
제이씨현시스템(033320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이씨현시스템 crawled / 1860 / 2713----
씨엠에스에듀(225330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨엠에스에듀 crawled / 1861 / 2713----
휴비츠(065510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴비츠 crawled / 1862 / 2713----
엠플러스(259630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엠플러스 crawled / 1863 / 2713----
엑세스바이오(950130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엑세스바이오 crawled / 1864 / 2713----
광림(014200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 광림 crawled / 1865 / 2713----
현성바이탈(204990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현성바이탈 crawled / 1866 / 2713----
필옵틱스(161580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 필옵틱스 crawled / 1867 / 2713----
창해에탄올(004650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 창해에탄올 crawled / 1868 / 2713----
풍국주정(023900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 풍국주정 crawled / 1869 / 2713----
투비소프트(079970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 투비소프트 crawled / 1870 / 2713----
메가스터디(072870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메가스터디 crawled / 1871 / 2713----
대유위니아(071460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대유위니아 crawled / 1872 / 2713----
윈스(136540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 윈스 crawled / 1873 / 2713----
유에스티(263770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유에스티 crawled / 1874 / 2713----
피씨엘(241820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피씨엘 crawled / 1875 / 2713----
넥스턴(089140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥스턴 crawled / 1876 / 2713----
이엠코리아(095190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이엠코리아 crawled / 1877 / 2713----
나노엔텍(039860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나노엔텍 crawled / 1878 / 2713----
서울옥션(063170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서울옥션 crawled / 1879 / 2713----
파워로직스(047310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파워로직스 crawled / 1880 / 2713----
팜스웰바이오(043090)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팜스웰바이오 crawled / 1881 / 2713----
국보디자인(066620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국보디자인 crawled / 1882 / 2713----
디앤씨미디어(263720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디앤씨미디어 crawled / 1883 / 2713----
제룡산업(147830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제룡산업 crawled / 1884 / 2713----
토비스(051360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 토비스 crawled / 1885 / 2713----
유지인트(195990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유지인트 crawled / 1886 / 2713----
제이에스티나(026040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이에스티나 crawled / 1887 / 2713----
에스와이패널(109610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스와이패널 crawled / 1888 / 2713----
갤럭시아컴즈(094480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 갤럭시아컴즈 crawled / 1889 / 2713----
감마누(192410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 감마누 crawled / 1890 / 2713----
대호피앤씨(021040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대호피앤씨 crawled / 1891 / 2713----
조이맥스(101730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조이맥스 crawled / 1892 / 2713----
제주반도체(080220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제주반도체 crawled / 1893 / 2713----
해성산업(034810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 해성산업 crawled / 1894 / 2713----
에코마케팅(230360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에코마케팅 crawled / 1895 / 2713----
비츠로테크(042370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비츠로테크 crawled / 1896 / 2713----
싸이맥스(160980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 싸이맥스 crawled / 1897 / 2713----
시공테크(020710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 시공테크 crawled / 1898 / 2713----
아이에이(038880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이에이 crawled / 1899 / 2713----
셀바스AI(108860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 셀바스AI crawled / 1900 / 2713----
기가레인(049080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 기가레인 crawled / 1901 / 2713----
디에스케이(109740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디에스케이 crawled / 1902 / 2713----
대원산업(005710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대원산업 crawled / 1903 / 2713----
MP한강(219550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- MP한강 crawled / 1904 / 2713----
미코(059090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미코 crawled / 1905 / 2713----
보성파워텍(006910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 보성파워텍 crawled / 1906 / 2713----
에버다임(041440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에버다임 crawled / 1907 / 2713----
룽투코리아(060240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 룽투코리아 crawled / 1908 / 2713----
SCI평가정보(036120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SCI평가정보 crawled / 1909 / 2713----
가온미디어(078890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 가온미디어 crawled / 1910 / 2713----
시너지이노베이션(048870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 시너지이노베이션 crawled / 1911 / 2713----
브레인콘텐츠(066980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 브레인콘텐츠 crawled / 1912 / 2713----
상신이디피(091580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 상신이디피 crawled / 1913 / 2713----
옵트론텍(082210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 옵트론텍 crawled / 1914 / 2713----
APS홀딩스(054620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- APS홀딩스 crawled / 1915 / 2713----
중앙백신(072020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 중앙백신 crawled / 1916 / 2713----
부방(014470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부방 crawled / 1917 / 2713----
디엔에프(092070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디엔에프 crawled / 1918 / 2713----
큐캐피탈(016600)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 큐캐피탈 crawled / 1919 / 2713----
알서포트(131370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알서포트 crawled / 1920 / 2713----
대봉엘에스(078140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대봉엘에스 crawled / 1921 / 2713----
대성엘텍(025440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대성엘텍 crawled / 1922 / 2713----
디에스티로봇(090710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디에스티로봇 crawled / 1923 / 2713----
정산애강(022220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 정산애강 crawled / 1924 / 2713----
비즈니스온(138580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비즈니스온 crawled / 1925 / 2713----
한일진공(123840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한일진공 crawled / 1926 / 2713----
남화토건(091590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 남화토건 crawled / 1927 / 2713----
네오위즈홀딩스(042420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네오위즈홀딩스 crawled / 1928 / 2713----
오로라(039830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오로라 crawled / 1929 / 2713----
삼보판지(023600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼보판지 crawled / 1930 / 2713----
포스코엠텍(009520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포스코엠텍 crawled / 1931 / 2713----
캠시스(050110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 캠시스 crawled / 1932 / 2713----
디티앤씨(187220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디티앤씨 crawled / 1933 / 2713----
인트로메딕(150840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인트로메딕 crawled / 1934 / 2713----
녹십자엠에스(142280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 녹십자엠에스 crawled / 1935 / 2713----
와이제이엠게임즈(193250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이제이엠게임즈 crawled / 1936 / 2713----
소리바다(053110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 소리바다 crawled / 1937 / 2713----
유아이엘(049520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유아이엘 crawled / 1938 / 2713----
라온시큐어(042510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 라온시큐어 crawled / 1939 / 2713----
KNN(058400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KNN crawled / 1940 / 2713----
엠에스씨(009780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엠에스씨 crawled / 1941 / 2713----
나노캠텍(091970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나노캠텍 crawled / 1942 / 2713----
레드캡투어(038390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 레드캡투어 crawled / 1943 / 2713----
퓨쳐켐(220100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 퓨쳐켐 crawled / 1944 / 2713----
일신바이오(068330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일신바이오 crawled / 1945 / 2713----
고려제약(014570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고려제약 crawled / 1946 / 2713----
대원미디어(048910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대원미디어 crawled / 1947 / 2713----
애니젠(196300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 애니젠 crawled / 1948 / 2713----
화일약품(061250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화일약품 crawled / 1949 / 2713----
씨아이에스(222080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨아이에스 crawled / 1950 / 2713----
영풍정밀(036560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영풍정밀 crawled / 1951 / 2713----
이화공영(001840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이화공영 crawled / 1952 / 2713----
세보엠이씨(011560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세보엠이씨 crawled / 1953 / 2713----
우리산업홀딩스(072470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리산업홀딩스 crawled / 1954 / 2713----
엑셈(205100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엑셈 crawled / 1955 / 2713----
아바코(083930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아바코 crawled / 1956 / 2713----
코콤(015710)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코콤 crawled / 1957 / 2713----
에이스테크(088800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이스테크 crawled / 1958 / 2713----
링크제니시스(219420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 링크제니시스 crawled / 1959 / 2713----
뉴로스(126870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 뉴로스 crawled / 1960 / 2713----
바른손이앤에이(035620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바른손이앤에이 crawled / 1961 / 2713----
코데즈컴바인(047770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코데즈컴바인 crawled / 1962 / 2713----
현대정보기술(026180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대정보기술 crawled / 1963 / 2713----
이화전기(024810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이화전기 crawled / 1964 / 2713----
선광(003100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 선광 crawled / 1965 / 2713----
쎄트렉아이(099320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쎄트렉아이 crawled / 1966 / 2713----
NHN벅스(104200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NHN벅스 crawled / 1967 / 2713----
대양전기공업(108380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대양전기공업 crawled / 1968 / 2713----
테스나(131970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 테스나 crawled / 1969 / 2713----
세화피앤씨(252500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세화피앤씨 crawled / 1970 / 2713----
KPX생명과학(114450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KPX생명과학 crawled / 1971 / 2713----
크리스탈신소재(900250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크리스탈신소재 crawled / 1972 / 2713----
유비쿼스홀딩스(078070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유비쿼스홀딩스 crawled / 1973 / 2713----
린드먼아시아(277070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 린드먼아시아 crawled / 1974 / 2713----
대원(007680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대원 crawled / 1975 / 2713----
글로본(019660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 글로본 crawled / 1976 / 2713----
위지트(036090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 위지트 crawled / 1977 / 2713----
하이즈항공(221840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이즈항공 crawled / 1978 / 2713----
화이브라더스코리아(204630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화이브라더스코리아 crawled / 1979 / 2713----
배럴(267790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 배럴 crawled / 1980 / 2713----
아바텍(149950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아바텍 crawled / 1981 / 2713----
신일제약(012790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신일제약 crawled / 1982 / 2713----
이지웰페어(090850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이지웰페어 crawled / 1983 / 2713----
비에이치아이(083650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비에이치아이 crawled / 1984 / 2713----
유티아이(179900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유티아이 crawled / 1985 / 2713----
서원인텍(093920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서원인텍 crawled / 1986 / 2713----
좋은사람들(033340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 좋은사람들 crawled / 1987 / 2713----
AP위성(211270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- AP위성 crawled / 1988 / 2713----
빅솔론(093190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 빅솔론 crawled / 1989 / 2713----
성도이엔지(037350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성도이엔지 crawled / 1990 / 2713----
우주일렉트로(065680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우주일렉트로 crawled / 1991 / 2713----
이엘피(063760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이엘피 crawled / 1992 / 2713----
엘앤케이바이오(156100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘앤케이바이오 crawled / 1993 / 2713----
유비쿼스(264450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유비쿼스 crawled / 1994 / 2713----
피엔티(137400)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피엔티 crawled / 1995 / 2713----
이에스브이(223310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이에스브이 crawled / 1996 / 2713----
팅크웨어(084730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팅크웨어 crawled / 1997 / 2713----
하나마이크론(067310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나마이크론 crawled / 1998 / 2713----
재영솔루텍(049630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 재영솔루텍 crawled / 1999 / 2713----
랩지노믹스(084650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 랩지노믹스 crawled / 2000 / 2713----
정상제이엘에스(040420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 정상제이엘에스 crawled / 2001 / 2713----
폭스브레인(039230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 폭스브레인 crawled / 2002 / 2713----
세명전기(017510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세명전기 crawled / 2003 / 2713----
더블유에프엠(035290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 더블유에프엠 crawled / 2004 / 2713----
서울제약(018680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서울제약 crawled / 2005 / 2713----
푸른저축은행(007330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 푸른저축은행 crawled / 2006 / 2713----
피에스텍(002230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피에스텍 crawled / 2007 / 2713----
전파기지국(065530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 전파기지국 crawled / 2008 / 2713----
케이사인(192250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이사인 crawled / 2009 / 2713----
동아엘텍(088130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동아엘텍 crawled / 2010 / 2713----
세코닉스(053450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세코닉스 crawled / 2011 / 2713----
바이오스마트(038460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이오스마트 crawled / 2012 / 2713----
에스텍(069510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스텍 crawled / 2013 / 2713----
중앙오션(054180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 중앙오션 crawled / 2014 / 2713----
잉글우드랩(950140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 잉글우드랩 crawled / 2015 / 2713----
삼천리자전거(024950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼천리자전거 crawled / 2016 / 2713----
선익시스템(171090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 선익시스템 crawled / 2017 / 2713----
팜스토리(027710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팜스토리 crawled / 2018 / 2713----
대정화금(120240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대정화금 crawled / 2019 / 2713----
덕우전자(263600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덕우전자 crawled / 2020 / 2713----
영인프런티어(036180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영인프런티어 crawled / 2021 / 2713----
시그네틱스(033170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 시그네틱스 crawled / 2022 / 2713----
미래SCI(028040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래SCI crawled / 2023 / 2713----
포티스(141020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포티스 crawled / 2024 / 2713----
아비코전자(036010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아비코전자 crawled / 2025 / 2713----
청담러닝(096240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 청담러닝 crawled / 2026 / 2713----
씨트리(047920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨트리 crawled / 2027 / 2713----
코다코(046070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코다코 crawled / 2028 / 2713----
엘비세미콘(061970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘비세미콘 crawled / 2029 / 2713----
리드(197210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 리드 crawled / 2030 / 2713----
신성델타테크(065350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신성델타테크 crawled / 2031 / 2713----
오픈베이스(049480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오픈베이스 crawled / 2032 / 2713----
옴니시스템(057540)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 옴니시스템 crawled / 2033 / 2713----
제이스테판(096690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이스테판 crawled / 2034 / 2713----
에프에스티(036810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에프에스티 crawled / 2035 / 2713----
에이테크솔루션(071670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이테크솔루션 crawled / 2036 / 2713----
국순당(043650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국순당 crawled / 2037 / 2713----
제닉(123330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제닉 crawled / 2038 / 2713----
비트컴퓨터(032850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비트컴퓨터 crawled / 2039 / 2713----
EMW(079190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- EMW crawled / 2040 / 2713----
유니크(011320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니크 crawled / 2041 / 2713----
리켐(131100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 리켐 crawled / 2042 / 2713----
누리텔레콤(040160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 누리텔레콤 crawled / 2043 / 2713----
에코바이오(038870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에코바이오 crawled / 2044 / 2713----
블루콤(033560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 블루콤 crawled / 2045 / 2713----
초록뱀(047820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 초록뱀 crawled / 2046 / 2713----
MP그룹(065150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- MP그룹 crawled / 2047 / 2713----
가비아(079940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 가비아 crawled / 2048 / 2713----
인터불스(158310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인터불스 crawled / 2049 / 2713----
데일리블록체인(139050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 데일리블록체인 crawled / 2050 / 2713----
우정바이오(215380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우정바이오 crawled / 2051 / 2713----
세미콘라이트(214310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세미콘라이트 crawled / 2052 / 2713----
서울리거(043710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서울리거 crawled / 2053 / 2713----
나이스디앤비(130580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나이스디앤비 crawled / 2054 / 2713----
스맥(099440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스맥 crawled / 2055 / 2713----
파라텍(033540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파라텍 crawled / 2056 / 2713----
대성창투(027830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대성창투 crawled / 2057 / 2713----
나이벡(138610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나이벡 crawled / 2058 / 2713----
포스링크(056730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포스링크 crawled / 2059 / 2713----
앤디포스(238090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 앤디포스 crawled / 2060 / 2713----
모바일어플라이언스(087260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모바일어플라이언스 crawled / 2061 / 2713----
한빛소프트(047080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한빛소프트 crawled / 2062 / 2713----
동우팜투테이블(088910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동우팜투테이블 crawled / 2063 / 2713----
아진엑스텍(059120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아진엑스텍 crawled / 2064 / 2713----
엑시콘(092870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엑시콘 crawled / 2065 / 2713----
녹원씨엔아이(065560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 녹원씨엔아이 crawled / 2066 / 2713----
한국캐피탈(023760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국캐피탈 crawled / 2067 / 2713----
엘티씨(170920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘티씨 crawled / 2068 / 2713----
크린앤사이언스(045520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크린앤사이언스 crawled / 2069 / 2713----
에이텍(045660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이텍 crawled / 2070 / 2713----
보라티알(250000)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 보라티알 crawled / 2071 / 2713----
서린바이오(038070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서린바이오 crawled / 2072 / 2713----
어보브반도체(102120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 어보브반도체 crawled / 2073 / 2713----
코렌텍(104540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코렌텍 crawled / 2074 / 2713----
하츠(066130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하츠 crawled / 2075 / 2713----
원익큐브(014190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원익큐브 crawled / 2076 / 2713----
메타바이오메드(059210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메타바이오메드 crawled / 2077 / 2713----
파루(043200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파루 crawled / 2078 / 2713----
현대통신(039010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대통신 crawled / 2079 / 2713----
차이나그레이트(900040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 차이나그레이트 crawled / 2080 / 2713----
메디아나(041920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메디아나 crawled / 2081 / 2713----
엔터메이트(206400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔터메이트 crawled / 2082 / 2713----
KT서브마린(060370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KT서브마린 crawled / 2083 / 2713----
코아시아홀딩스(045970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코아시아홀딩스 crawled / 2084 / 2713----
오성첨단소재(052420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오성첨단소재 crawled / 2085 / 2713----
쎄노텍(222420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쎄노텍 crawled / 2086 / 2713----
이녹스(088390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이녹스 crawled / 2087 / 2713----
리노스(039980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 리노스 crawled / 2088 / 2713----
팍스넷(038160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팍스넷 crawled / 2089 / 2713----
케이엘넷(039420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이엘넷 crawled / 2090 / 2713----
THE E&M(089230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- THE E&M crawled / 2091 / 2713----
라이브플렉스(050120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 라이브플렉스 crawled / 2092 / 2713----
오스템(031510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오스템 crawled / 2093 / 2713----
유앤아이(056090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유앤아이 crawled / 2094 / 2713----
DSC인베스트먼트(241520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DSC인베스트먼트 crawled / 2095 / 2713----
오르비텍(046120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오르비텍 crawled / 2096 / 2713----
바이오빌(065940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이오빌 crawled / 2097 / 2713----
지란지교시큐리티(208350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지란지교시큐리티 crawled / 2098 / 2713----
디에이테크놀로지(196490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디에이테크놀로지 crawled / 2099 / 2713----
인텔리안테크(189300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인텔리안테크 crawled / 2100 / 2713----
이노와이어리스(073490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이노와이어리스 crawled / 2101 / 2713----
에쎈테크(043340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에쎈테크 crawled / 2102 / 2713----
토필드(057880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 토필드 crawled / 2103 / 2713----
켐트로스(220260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 켐트로스 crawled / 2104 / 2713----
아진산업(013310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아진산업 crawled / 2105 / 2713----
삼기오토모티브(122350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼기오토모티브 crawled / 2106 / 2713----
에스엔유(080000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스엔유 crawled / 2107 / 2713----
탑엔지니어링(065130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 탑엔지니어링 crawled / 2108 / 2713----
씨티엘(036170)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨티엘 crawled / 2109 / 2713----
옴니텔(057680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 옴니텔 crawled / 2110 / 2713----
모베이스(101330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모베이스 crawled / 2111 / 2713----
힘스(238490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 힘스 crawled / 2112 / 2713----
유라테크(048430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유라테크 crawled / 2113 / 2713----
와이엔텍(067900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이엔텍 crawled / 2114 / 2713----
체리부로(066360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 체리부로 crawled / 2115 / 2713----
대륙제관(004780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대륙제관 crawled / 2116 / 2713----
월덱스(101160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 월덱스 crawled / 2117 / 2713----
웰크론(065950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웰크론 crawled / 2118 / 2713----
이상네트웍스(080010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이상네트웍스 crawled / 2119 / 2713----
시큐브(131090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 시큐브 crawled / 2120 / 2713----
SGA솔루션즈(184230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SGA솔루션즈 crawled / 2121 / 2713----
미래나노텍(095500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래나노텍 crawled / 2122 / 2713----
태양씨앤엘(072520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태양씨앤엘 crawled / 2123 / 2713----
오디텍(080520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오디텍 crawled / 2124 / 2713----
서산(079650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서산 crawled / 2125 / 2713----
하이텍팜(106190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이텍팜 crawled / 2126 / 2713----
디알텍(214680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디알텍 crawled / 2127 / 2713----
일진파워(094820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일진파워 crawled / 2128 / 2713----
디지털대성(068930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디지털대성 crawled / 2129 / 2713----
에스앤씨엔진그룹(900080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스앤씨엔진그룹 crawled / 2130 / 2713----
하이로닉(149980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이로닉 crawled / 2131 / 2713----
셀바스헬스케어(208370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 셀바스헬스케어 crawled / 2132 / 2713----
지와이커머스(111820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지와이커머스 crawled / 2133 / 2713----
인베니아(079950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인베니아 crawled / 2134 / 2713----
에스넷(038680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스넷 crawled / 2135 / 2713----
알에프텍(061040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알에프텍 crawled / 2136 / 2713----
3S(060310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 3S crawled / 2137 / 2713----
태양(053620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 태양 crawled / 2138 / 2713----
GST(083450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GST crawled / 2139 / 2713----
삼강엠앤티(100090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼강엠앤티 crawled / 2140 / 2713----
스킨앤스킨(159910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스킨앤스킨 crawled / 2141 / 2713----
에스앤에스텍(101490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스앤에스텍 crawled / 2142 / 2713----
예스24(053280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 예스24 crawled / 2143 / 2713----
국일제지(078130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국일제지 crawled / 2144 / 2713----
에스에너지(095910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스에너지 crawled / 2145 / 2713----
한솔신텍(099660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔신텍 crawled / 2146 / 2713----
인성정보(033230)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인성정보 crawled / 2147 / 2713----
에이티테크놀러지(073570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이티테크놀러지 crawled / 2148 / 2713----
엔텔스(069410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔텔스 crawled / 2149 / 2713----
알티캐스트(085810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알티캐스트 crawled / 2150 / 2713----
대성미생물(036480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대성미생물 crawled / 2151 / 2713----
넥스트칩(092600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥스트칩 crawled / 2152 / 2713----
KCI(036670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KCI crawled / 2153 / 2713----
이젠텍(033600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이젠텍 crawled / 2154 / 2713----
동양파일(228340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양파일 crawled / 2155 / 2713----
티에스인베스트먼트(246690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티에스인베스트먼트 crawled / 2156 / 2713----
유성티엔에스(024800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유성티엔에스 crawled / 2157 / 2713----
정원엔시스(045510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 정원엔시스 crawled / 2158 / 2713----
이그잭스(060230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이그잭스 crawled / 2159 / 2713----
바른전자(064520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바른전자 crawled / 2160 / 2713----
마이크로프랜드(147760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마이크로프랜드 crawled / 2161 / 2713----
쿠첸(225650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쿠첸 crawled / 2162 / 2713----
동양이엔피(079960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양이엔피 crawled / 2163 / 2713----
오션브릿지(241790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오션브릿지 crawled / 2164 / 2713----
오이솔루션(138080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오이솔루션 crawled / 2165 / 2713----
아이앤씨(052860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이앤씨 crawled / 2166 / 2713----
YTN(040300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- YTN crawled / 2167 / 2713----
화진(134780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화진 crawled / 2168 / 2713----
파인테크닉스(106240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파인테크닉스 crawled / 2169 / 2713----
코프라(126600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코프라 crawled / 2170 / 2713----
엠게임(058630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엠게임 crawled / 2171 / 2713----
한프(066110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한프 crawled / 2172 / 2713----
드래곤플라이(030350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 드래곤플라이 crawled / 2173 / 2713----
모헨즈(006920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모헨즈 crawled / 2174 / 2713----
코맥스(036690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코맥스 crawled / 2175 / 2713----
디엔에이링크(127120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디엔에이링크 crawled / 2176 / 2713----
텔루스(196450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 텔루스 crawled / 2177 / 2713----
자이글(234920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 자이글 crawled / 2178 / 2713----
엔지스테크널러지(208860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔지스테크널러지 crawled / 2179 / 2713----
골든센츄리(900280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 골든센츄리 crawled / 2180 / 2713----
유테크(178780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유테크 crawled / 2181 / 2713----
서울전자통신(027040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서울전자통신 crawled / 2182 / 2713----
에이치엘비파워(043220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이치엘비파워 crawled / 2183 / 2713----
금강철강(053260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 금강철강 crawled / 2184 / 2713----
넥스지(081970)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥스지 crawled / 2185 / 2713----
엠에스오토텍(123040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엠에스오토텍 crawled / 2186 / 2713----
우수AMS(066590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우수AMS crawled / 2187 / 2713----
디지틀조선(033130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디지틀조선 crawled / 2188 / 2713----
대창스틸(140520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대창스틸 crawled / 2189 / 2713----
멜파스(096640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 멜파스 crawled / 2190 / 2713----
삼본정밀전자(111870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼본정밀전자 crawled / 2191 / 2713----
서호전기(065710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서호전기 crawled / 2192 / 2713----
케이맥(043290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이맥 crawled / 2193 / 2713----
한라IMS(092460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한라IMS crawled / 2194 / 2713----
진양제약(007370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진양제약 crawled / 2195 / 2713----
제이엔케이히터(126880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이엔케이히터 crawled / 2196 / 2713----
케이엠(083550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이엠 crawled / 2197 / 2713----
미래생명자원(218150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래생명자원 crawled / 2198 / 2713----
케이아이엔엑스(093320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이아이엔엑스 crawled / 2199 / 2713----
상지카일룸(042940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 상지카일룸 crawled / 2200 / 2713----
엔브이에이치코리아(067570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔브이에이치코리아 crawled / 2201 / 2713----
엔에스(217820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔에스 crawled / 2202 / 2713----
에이디테크놀로지(200710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이디테크놀로지 crawled / 2203 / 2713----
피앤텔(054340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피앤텔 crawled / 2204 / 2713----
피제이전자(006140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피제이전자 crawled / 2205 / 2713----
파세코(037070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파세코 crawled / 2206 / 2713----
진매트릭스(109820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진매트릭스 crawled / 2207 / 2713----
퍼시픽바이오(060900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 퍼시픽바이오 crawled / 2208 / 2713----
아이에스이커머스(069920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이에스이커머스 crawled / 2209 / 2713----
동운아나텍(094170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동운아나텍 crawled / 2210 / 2713----
인포바인(115310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인포바인 crawled / 2211 / 2713----
손오공(066910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 손오공 crawled / 2212 / 2713----
코위버(056360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코위버 crawled / 2213 / 2713----
한일네트웍스(046110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한일네트웍스 crawled / 2214 / 2713----
동신건설(025950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동신건설 crawled / 2215 / 2713----
솔고바이오(043100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 솔고바이오 crawled / 2216 / 2713----
한국경제TV(039340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국경제TV crawled / 2217 / 2713----
SGA(049470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SGA crawled / 2218 / 2713----
우원개발(046940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우원개발 crawled / 2219 / 2713----
트레이스(052290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 트레이스 crawled / 2220 / 2713----
에이씨티(138360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이씨티 crawled / 2221 / 2713----
씨케이에이치(900120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨케이에이치 crawled / 2222 / 2713----
아리온(058220)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아리온 crawled / 2223 / 2713----
한국선재(025550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국선재 crawled / 2224 / 2713----
SG&G(040610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SG&G crawled / 2225 / 2713----
나라엠앤디(051490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나라엠앤디 crawled / 2226 / 2713----
빅텍(065450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 빅텍 crawled / 2227 / 2713----
대림제지(017650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대림제지 crawled / 2228 / 2713----
유비벨록스(089850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유비벨록스 crawled / 2229 / 2713----
판타지오(032800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 판타지오 crawled / 2230 / 2713----
상신전자(263810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 상신전자 crawled / 2231 / 2713----
이엘케이(094190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이엘케이 crawled / 2232 / 2713----
대동스틸(048470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대동스틸 crawled / 2233 / 2713----
지엔씨에너지(119850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지엔씨에너지 crawled / 2234 / 2713----
비엠티(086670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비엠티 crawled / 2235 / 2713----
대양제지(006580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대양제지 crawled / 2236 / 2713----
삼화네트웍스(046390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼화네트웍스 crawled / 2237 / 2713----
TPC(048770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TPC crawled / 2238 / 2713----
데코앤이(017680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 데코앤이 crawled / 2239 / 2713----
동일기연(032960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동일기연 crawled / 2240 / 2713----
미스터블루(207760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미스터블루 crawled / 2241 / 2713----
케이피에프(024880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이피에프 crawled / 2242 / 2713----
우노앤컴퍼니(114630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우노앤컴퍼니 crawled / 2243 / 2713----
에스엔텍(160600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스엔텍 crawled / 2244 / 2713----
효성오앤비(097870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 효성오앤비 crawled / 2245 / 2713----
이랜텍(054210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이랜텍 crawled / 2246 / 2713----
디스플레이텍(066670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디스플레이텍 crawled / 2247 / 2713----
삼륭물산(014970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼륭물산 crawled / 2248 / 2713----
아이디스(143160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이디스 crawled / 2249 / 2713----
코메론(049430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코메론 crawled / 2250 / 2713----
EG(037370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- EG crawled / 2251 / 2713----
이매진아시아(036260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이매진아시아 crawled / 2252 / 2713----
크레아플래닛(058530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크레아플래닛 crawled / 2253 / 2713----
에스씨디(042110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스씨디 crawled / 2254 / 2713----
정다운(208140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 정다운 crawled / 2255 / 2713----
한일사료(005860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한일사료 crawled / 2256 / 2713----
인포마크(175140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인포마크 crawled / 2257 / 2713----
영화테크(265560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영화테크 crawled / 2258 / 2713----
제이씨케미칼(137950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이씨케미칼 crawled / 2259 / 2713----
딜리(131180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 딜리 crawled / 2260 / 2713----
아이엠텍(226350)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이엠텍 crawled / 2261 / 2713----
성창오토텍(080470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성창오토텍 crawled / 2262 / 2713----
덕신하우징(090410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 덕신하우징 crawled / 2263 / 2713----
라이트론(069540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 라이트론 crawled / 2264 / 2713----
켐트로닉스(089010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 켐트로닉스 crawled / 2265 / 2713----
이라이콤(041520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이라이콤 crawled / 2266 / 2713----
신진에스엠(138070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신진에스엠 crawled / 2267 / 2713----
심텍홀딩스(036710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 심텍홀딩스 crawled / 2268 / 2713----
HRS(036640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- HRS crawled / 2269 / 2713----
디에이피(066900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디에이피 crawled / 2270 / 2713----
뉴프렉스(085670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 뉴프렉스 crawled / 2271 / 2713----
차이나하오란(900090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 차이나하오란 crawled / 2272 / 2713----
케이프(064820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이프 crawled / 2273 / 2713----
윈팩(097800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 윈팩 crawled / 2274 / 2713----
나무가(190510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나무가 crawled / 2275 / 2713----
iMBC(052220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- iMBC crawled / 2276 / 2713----
크로바하이텍(043590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 크로바하이텍 crawled / 2277 / 2713----
팬엔터테인먼트(068050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팬엔터테인먼트 crawled / 2278 / 2713----
서진오토모티브(122690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서진오토모티브 crawled / 2279 / 2713----
새로닉스(042600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 새로닉스 crawled / 2280 / 2713----
SG(255220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SG crawled / 2281 / 2713----
파인디앤씨(049120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파인디앤씨 crawled / 2282 / 2713----
갑을메탈(024840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 갑을메탈 crawled / 2283 / 2713----
무림SP(001810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 무림SP crawled / 2284 / 2713----
엔시트론(101400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔시트론 crawled / 2285 / 2713----
지니언스(263860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지니언스 crawled / 2286 / 2713----
신라섬유(001000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신라섬유 crawled / 2287 / 2713----
흥국에프엔비(189980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 흥국에프엔비 crawled / 2288 / 2713----
대성파인텍(104040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대성파인텍 crawled / 2289 / 2713----
엘엠에스(073110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘엠에스 crawled / 2290 / 2713----
코리아에프티(123410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코리아에프티 crawled / 2291 / 2713----
디엠씨(101000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디엠씨 crawled / 2292 / 2713----
로체시스템즈(071280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 로체시스템즈 crawled / 2293 / 2713----
제이엠티(094970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이엠티 crawled / 2294 / 2713----
한국맥널티(222980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국맥널티 crawled / 2295 / 2713----
삼현철강(017480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼현철강 crawled / 2296 / 2713----
매커스(093520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 매커스 crawled / 2297 / 2713----
인포뱅크(039290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인포뱅크 crawled / 2298 / 2713----
동아화성(041930)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동아화성 crawled / 2299 / 2713----
휘닉스소재(050090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휘닉스소재 crawled / 2300 / 2713----
픽셀플러스(087600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 픽셀플러스 crawled / 2301 / 2713----
KB오토시스(024120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KB오토시스 crawled / 2302 / 2713----
엠벤처투자(019590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엠벤처투자 crawled / 2303 / 2713----
아시아경제(127710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아시아경제 crawled / 2304 / 2713----
한국테크놀로지(053590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국테크놀로지 crawled / 2305 / 2713----
디딤(217620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디딤 crawled / 2306 / 2713----
일경산업개발(078940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일경산업개발 crawled / 2307 / 2713----
씨그널엔터테인먼트그룹(099830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨그널엔터테인먼트그룹 crawled / 2308 / 2713----
유니트론텍(142210)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니트론텍 crawled / 2309 / 2713----
마제스타(035480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마제스타 crawled / 2310 / 2713----
티비씨(033830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티비씨 crawled / 2311 / 2713----
삼영이엔씨(065570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼영이엔씨 crawled / 2312 / 2713----
비츠로시스(054220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비츠로시스 crawled / 2313 / 2713----
삼진엘앤디(054090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼진엘앤디 crawled / 2314 / 2713----
와이오엠(066430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이오엠 crawled / 2315 / 2713----
로고스바이오(238120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 로고스바이오 crawled / 2316 / 2713----
한국팩키지(037230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국팩키지 crawled / 2317 / 2713----
아이엠(101390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이엠 crawled / 2318 / 2713----
와이디온라인(052770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이디온라인 crawled / 2319 / 2713----
씨앤지하이테크(264660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨앤지하이테크 crawled / 2320 / 2713----
아이티센(124500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이티센 crawled / 2321 / 2713----
바이오로그디바이스(208710)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바이오로그디바이스 crawled / 2322 / 2713----
디바이스이엔지(187870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디바이스이엔지 crawled / 2323 / 2713----
자연과환경(043910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 자연과환경 crawled / 2324 / 2713----
데이타솔루션(263800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 데이타솔루션 crawled / 2325 / 2713----
에코마이스터(064510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에코마이스터 crawled / 2326 / 2713----
시스웍(269620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 시스웍 crawled / 2327 / 2713----
잉크테크(049550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 잉크테크 crawled / 2328 / 2713----
베셀(177350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 베셀 crawled / 2329 / 2713----
우리기술(032820)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리기술 crawled / 2330 / 2713----
에스마크(030270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스마크 crawled / 2331 / 2713----
한국가구(004590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국가구 crawled / 2332 / 2713----
오리엔트정공(065500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오리엔트정공 crawled / 2333 / 2713----
우리넷(115440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리넷 crawled / 2334 / 2713----
한컴시큐어(054920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한컴시큐어 crawled / 2335 / 2713----
이엠넷(123570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이엠넷 crawled / 2336 / 2713----
대진디엠피(065690)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대진디엠피 crawled / 2337 / 2713----
우진비앤지(018620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우진비앤지 crawled / 2338 / 2713----
이스트소프트(047560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이스트소프트 crawled / 2339 / 2713----
피앤씨테크(237750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피앤씨테크 crawled / 2340 / 2713----
고려시멘트(198440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고려시멘트 crawled / 2341 / 2713----
씨큐브(101240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨큐브 crawled / 2342 / 2713----
모아텍(033200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모아텍 crawled / 2343 / 2713----
미래테크놀로지(213090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래테크놀로지 crawled / 2344 / 2713----
미동앤씨네마(161570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미동앤씨네마 crawled / 2345 / 2713----
글로벌에스엠(900070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 글로벌에스엠 crawled / 2346 / 2713----
희림(037440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 희림 crawled / 2347 / 2713----
엔에스엔(031860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔에스엔 crawled / 2348 / 2713----
오스테오닉(226400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오스테오닉 crawled / 2349 / 2713----
제로투세븐(159580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제로투세븐 crawled / 2350 / 2713----
W홀딩컴퍼니(052300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- W홀딩컴퍼니 crawled / 2351 / 2713----
한국코퍼레이션(050540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국코퍼레이션 crawled / 2352 / 2713----
솔루에타(154040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 솔루에타 crawled / 2353 / 2713----
하이셈(200470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이셈 crawled / 2354 / 2713----
수산아이앤티(050960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 수산아이앤티 crawled / 2355 / 2713----
대주산업(003310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대주산업 crawled / 2356 / 2713----
이-글 벳(044960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이-글 벳 crawled / 2357 / 2713----
이스트아시아홀딩스(900110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이스트아시아홀딩스 crawled / 2358 / 2713----
TJ미디어(032540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- TJ미디어 crawled / 2359 / 2713----
에너토크(019990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에너토크 crawled / 2360 / 2713----
네오디안테크놀로지(072770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네오디안테크놀로지 crawled / 2361 / 2713----
네패스신소재(087730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네패스신소재 crawled / 2362 / 2713----
신화인터텍(056700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신화인터텍 crawled / 2363 / 2713----
로보로보(215100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 로보로보 crawled / 2364 / 2713----
슈프리마에이치큐(094840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 슈프리마에이치큐 crawled / 2365 / 2713----
에프엔씨애드컬쳐(063440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에프엔씨애드컬쳐 crawled / 2366 / 2713----
캐스텍코리아(071850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 캐스텍코리아 crawled / 2367 / 2713----
에치디프로(214870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에치디프로 crawled / 2368 / 2713----
제일바이오(052670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제일바이오 crawled / 2369 / 2713----
오공(045060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오공 crawled / 2370 / 2713----
알엔투테크놀로지(148250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알엔투테크놀로지 crawled / 2371 / 2713----
포메탈(119500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포메탈 crawled / 2372 / 2713----
경창산업(024910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경창산업 crawled / 2373 / 2713----
인프라웨어(041020)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인프라웨어 crawled / 2374 / 2713----
디지탈옵틱(106520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디지탈옵틱 crawled / 2375 / 2713----
동일금속(109860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동일금속 crawled / 2376 / 2713----
세원물산(024830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세원물산 crawled / 2377 / 2713----
승일(049830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 승일 crawled / 2378 / 2713----
성우전자(081580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성우전자 crawled / 2379 / 2713----
삼영엠텍(054540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼영엠텍 crawled / 2380 / 2713----
코센(009730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코센 crawled / 2381 / 2713----
서연전자(012860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서연전자 crawled / 2382 / 2713----
링네트(042500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 링네트 crawled / 2383 / 2713----
웰크론한텍(076080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웰크론한텍 crawled / 2384 / 2713----
그랜드백화점(019010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 그랜드백화점 crawled / 2385 / 2713----
에이디칩스(054630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이디칩스 crawled / 2386 / 2713----
에이텍티앤(224110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이텍티앤 crawled / 2387 / 2713----
인지디스플레(037330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인지디스플레 crawled / 2388 / 2713----
쎄니트(037760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쎄니트 crawled / 2389 / 2713----
에스엔피월드(263920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스엔피월드 crawled / 2390 / 2713----
큐로홀딩스(051780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 큐로홀딩스 crawled / 2391 / 2713----
육일씨엔에쓰(191410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 육일씨엔에쓰 crawled / 2392 / 2713----
퓨전데이타(195440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 퓨전데이타 crawled / 2393 / 2713----
오리콤(010470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오리콤 crawled / 2394 / 2713----
휴마시스(205470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴마시스 crawled / 2395 / 2713----
쎄미시스코(136510)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쎄미시스코 crawled / 2396 / 2713----
한국컴퓨터(054040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국컴퓨터 crawled / 2397 / 2713----
SDN(099220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SDN crawled / 2398 / 2713----
케이디켐(221980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이디켐 crawled / 2399 / 2713----
현우산업(092300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현우산업 crawled / 2400 / 2713----
인터엠(017250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인터엠 crawled / 2401 / 2713----
메가엠디(133750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메가엠디 crawled / 2402 / 2713----
삼진(032750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼진 crawled / 2403 / 2713----
현대공업(170030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현대공업 crawled / 2404 / 2713----
해성옵틱스(076610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 해성옵틱스 crawled / 2405 / 2713----
CNH(023460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CNH crawled / 2406 / 2713----
원익(032940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원익 crawled / 2407 / 2713----
아이오케이(078860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이오케이 crawled / 2408 / 2713----
포비스티앤씨(016670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포비스티앤씨 crawled / 2409 / 2713----
칩스앤미디어(094360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 칩스앤미디어 crawled / 2410 / 2713----
영우디에스피(143540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영우디에스피 crawled / 2411 / 2713----
휴맥스홀딩스(028080)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 휴맥스홀딩스 crawled / 2412 / 2713----
투윈글로벌(066410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 투윈글로벌 crawled / 2413 / 2713----
램테크놀러지(171010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 램테크놀러지 crawled / 2414 / 2713----
S&K폴리텍(091340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- S&K폴리텍 crawled / 2415 / 2713----
케이피에스(256940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이피에스 crawled / 2416 / 2713----
디케이락(105740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디케이락 crawled / 2417 / 2713----
토박스코리아(215480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 토박스코리아 crawled / 2418 / 2713----
샘코(263540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 샘코 crawled / 2419 / 2713----
NE능률(053290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- NE능률 crawled / 2420 / 2713----
포시에스(189690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 포시에스 crawled / 2421 / 2713----
아세아텍(050860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아세아텍 crawled / 2422 / 2713----
수성(084180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 수성 crawled / 2423 / 2713----
우리로(046970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리로 crawled / 2424 / 2713----
진바이오텍(086060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 진바이오텍 crawled / 2425 / 2713----
모비스(250060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모비스 crawled / 2426 / 2713----
이엑스티(226360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이엑스티 crawled / 2427 / 2713----
아이즈비전(031310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이즈비전 crawled / 2428 / 2713----
경남스틸(039240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 경남스틸 crawled / 2429 / 2713----
우리이티아이(082850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리이티아이 crawled / 2430 / 2713----
스카이문스테크놀로지(033790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스카이문스테크놀로지 crawled / 2431 / 2713----
화성밸브(039610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화성밸브 crawled / 2432 / 2713----
우림기계(101170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우림기계 crawled / 2433 / 2713----
에스에이티(060540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스에이티 crawled / 2434 / 2713----
브리지텍(064480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 브리지텍 crawled / 2435 / 2713----
아이씨케이(068940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이씨케이 crawled / 2436 / 2713----
푸른기술(094940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 푸른기술 crawled / 2437 / 2713----
루미마이크로(082800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 루미마이크로 crawled / 2438 / 2713----
조광ILI(044060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 조광ILI crawled / 2439 / 2713----
고려신용정보(049720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고려신용정보 crawled / 2440 / 2713----
큐브엔터(182360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 큐브엔터 crawled / 2441 / 2713----
트루윈(105550)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 트루윈 crawled / 2442 / 2713----
삼원테크(073640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼원테크 crawled / 2443 / 2713----
한일단조(024740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한일단조 crawled / 2444 / 2713----
형지I&C(011080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 형지I&C crawled / 2445 / 2713----
파버나인(177830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파버나인 crawled / 2446 / 2713----
프리엠스(053160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 프리엠스 crawled / 2447 / 2713----
성우테크론(045300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성우테크론 crawled / 2448 / 2713----
인텍플러스(064290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인텍플러스 crawled / 2449 / 2713----
비디아이(148140)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 비디아이 crawled / 2450 / 2713----
스페코(013810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스페코 crawled / 2451 / 2713----
플랜티넷(075130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 플랜티넷 crawled / 2452 / 2713----
흥국(010240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 흥국 crawled / 2453 / 2713----
바른손(018700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바른손 crawled / 2454 / 2713----
큐에스아이(066310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 큐에스아이 crawled / 2455 / 2713----
케이씨에스(115500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이씨에스 crawled / 2456 / 2713----
국영지앤엠(006050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국영지앤엠 crawled / 2457 / 2713----
알비케이이엠디(106080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알비케이이엠디 crawled / 2458 / 2713----
한솔시큐어(070300)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔시큐어 crawled / 2459 / 2713----
뉴인텍(012340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 뉴인텍 crawled / 2460 / 2713----
특수건설(026150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 특수건설 crawled / 2461 / 2713----
파수닷컴(150900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파수닷컴 crawled / 2462 / 2713----
일지테크(019540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일지테크 crawled / 2463 / 2713----
인화정공(101930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 인화정공 crawled / 2464 / 2713----
KD건설(044180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KD건설 crawled / 2465 / 2713----
와토스코리아(079000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와토스코리아 crawled / 2466 / 2713----
이트론(096040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이트론 crawled / 2467 / 2713----
이건홀딩스(039020)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이건홀딩스 crawled / 2468 / 2713----
신원종합개발(017000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신원종합개발 crawled / 2469 / 2713----
티엘아이(062860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티엘아이 crawled / 2470 / 2713----
이디(033110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이디 crawled / 2471 / 2713----
디케이디앤아이(033310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디케이디앤아이 crawled / 2472 / 2713----
서암기계공업(100660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서암기계공업 crawled / 2473 / 2713----
피제이메탈(128660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피제이메탈 crawled / 2474 / 2713----
사파이어테크놀로지(123260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 사파이어테크놀로지 crawled / 2475 / 2713----
푸드웰(005670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 푸드웰 crawled / 2476 / 2713----
카스(016920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 카스 crawled / 2477 / 2713----
우리이앤엘(153490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리이앤엘 crawled / 2478 / 2713----
버추얼텍(036620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 버추얼텍 crawled / 2479 / 2713----
씨유메디칼(115480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨유메디칼 crawled / 2480 / 2713----
원풍(008370)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원풍 crawled / 2481 / 2713----
서연탑메탈(019770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서연탑메탈 crawled / 2482 / 2713----
완리(900180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 완리 crawled / 2483 / 2713----
이글루시큐리티(067920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이글루시큐리티 crawled / 2484 / 2713----
지에스이(053050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지에스이 crawled / 2485 / 2713----
고려반도체(089890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 고려반도체 crawled / 2486 / 2713----
유니맥스정보시스템(215090)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니맥스정보시스템 crawled / 2487 / 2713----
위즈코프(038620)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 위즈코프 crawled / 2488 / 2713----
KMH하이텍(052900)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KMH하이텍 crawled / 2489 / 2713----
메이슨캐피탈(021880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 메이슨캐피탈 crawled / 2490 / 2713----
아이크래프트(052460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이크래프트 crawled / 2491 / 2713----
세중(039310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세중 crawled / 2492 / 2713----
엑사이엔씨(054940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엑사이엔씨 crawled / 2493 / 2713----
옵티시스(109080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 옵티시스 crawled / 2494 / 2713----
씨씨에스(066790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨씨에스 crawled / 2495 / 2713----
백금T&A(046310)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 백금T&A crawled / 2496 / 2713----
디에스티(033430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디에스티 crawled / 2497 / 2713----
부스타(008470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 부스타 crawled / 2498 / 2713----
네오티스(085910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네오티스 crawled / 2499 / 2713----
서전기전(189860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 서전기전 crawled / 2500 / 2713----
상보(027580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 상보 crawled / 2501 / 2713----
화신정공(126640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화신정공 crawled / 2502 / 2713----
코렌(078650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코렌 crawled / 2503 / 2713----
유니온커뮤니티(203450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유니온커뮤니티 crawled / 2504 / 2713----
파인디지털(038950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파인디지털 crawled / 2505 / 2713----
에이티세미콘(089530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이티세미콘 crawled / 2506 / 2713----
티플랙스(081150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티플랙스 crawled / 2507 / 2713----
신화콘텍(187270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신화콘텍 crawled / 2508 / 2713----
GH신소재(130500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GH신소재 crawled / 2509 / 2713----
아이컴포넌트(059100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이컴포넌트 crawled / 2510 / 2713----
와이비엠넷(057030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 와이비엠넷 crawled / 2511 / 2713----
프럼파스트(035200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 프럼파스트 crawled / 2512 / 2713----
다믈멀티미디어(093640)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 다믈멀티미디어 crawled / 2513 / 2713----
국일신동(060480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 국일신동 crawled / 2514 / 2713----
케이씨피드(025880)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이씨피드 crawled / 2515 / 2713----
원일특강(012620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 원일특강 crawled / 2516 / 2713----
한탑(002680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한탑 crawled / 2517 / 2713----
엔피케이(048830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔피케이 crawled / 2518 / 2713----
동국알앤에스(075970)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동국알앤에스 crawled / 2519 / 2713----
대신정보통신(020180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신정보통신 crawled / 2520 / 2713----
패션플랫폼(225590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 패션플랫폼 crawled / 2521 / 2713----
DB라이텍(045890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- DB라이텍 crawled / 2522 / 2713----
윈하이텍(192390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 윈하이텍 crawled / 2523 / 2713----
흥구석유(024060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 흥구석유 crawled / 2524 / 2713----
한일화학(007770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한일화학 crawled / 2525 / 2713----
장원테크(174880)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 장원테크 crawled / 2526 / 2713----
에스아이티글로벌(050320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스아이티글로벌 crawled / 2527 / 2713----
빛샘전자(072950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 빛샘전자 crawled / 2528 / 2713----
케이씨티(089150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이씨티 crawled / 2529 / 2713----
나노(187790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 나노 crawled / 2530 / 2713----
대한과학(131220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대한과학 crawled / 2531 / 2713----
네오오토(212560)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네오오토 crawled / 2532 / 2713----
삼일기업공사(002290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼일기업공사 crawled / 2533 / 2713----
CS(065770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- CS crawled / 2534 / 2713----
뉴보텍(060260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 뉴보텍 crawled / 2535 / 2713----
코이즈(121850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코이즈 crawled / 2536 / 2713----
에이치시티(072990)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이치시티 crawled / 2537 / 2713----
이에스에이(052190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이에스에이 crawled / 2538 / 2713----
이즈미디어(181340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이즈미디어 crawled / 2539 / 2713----
파이오링크(170790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파이오링크 crawled / 2540 / 2713----
UCI(038340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- UCI crawled / 2541 / 2713----
타이거일렉(219130)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 타이거일렉 crawled / 2542 / 2713----
피델릭스(032580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피델릭스 crawled / 2543 / 2713----
에스아이리소스(065420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스아이리소스 crawled / 2544 / 2713----
GMR 머티리얼즈(032860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- GMR 머티리얼즈 crawled / 2545 / 2713----
오리엔탈정공(014940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오리엔탈정공 crawled / 2546 / 2713----
우리조명(037400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우리조명 crawled / 2547 / 2713----
YW(051390)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- YW crawled / 2548 / 2713----
신스타임즈(056000)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신스타임즈 crawled / 2549 / 2713----
에이치케이(044780)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이치케이 crawled / 2550 / 2713----
기산텔레콤(035460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 기산텔레콤 crawled / 2551 / 2713----
에프엔에스테크(083500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에프엔에스테크 crawled / 2552 / 2713----
유신(054930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유신 crawled / 2553 / 2713----
에코플라스틱(038110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에코플라스틱 crawled / 2554 / 2713----
이더블유케이(258610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이더블유케이 crawled / 2555 / 2713----
액트(131400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 액트 crawled / 2556 / 2713----
알톤스포츠(123750)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알톤스포츠 crawled / 2557 / 2713----
맥스로텍(141070)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 맥스로텍 crawled / 2558 / 2713----
에이치엔티(176440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이치엔티 crawled / 2559 / 2713----
알에프세미(096610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 알에프세미 crawled / 2560 / 2713----
핸디소프트(220180)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 핸디소프트 crawled / 2561 / 2713----
넥스트바이오홀딩스(051980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥스트바이오홀딩스 crawled / 2562 / 2713----
파인텍(131760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 파인텍 crawled / 2563 / 2713----
스포츠서울(039670)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스포츠서울 crawled / 2564 / 2713----
동양피엔에프(104460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양피엔에프 crawled / 2565 / 2713----
루트로닉3우C(08537M)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 루트로닉3우C crawled / 2566 / 2713----
아즈텍WB(032080)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아즈텍WB crawled / 2567 / 2713----
골드퍼시픽(038530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 골드퍼시픽 crawled / 2568 / 2713----
일야(058450)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 일야 crawled / 2569 / 2713----
웰크론강원(114190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웰크론강원 crawled / 2570 / 2713----
한창산업(079170)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한창산업 crawled / 2571 / 2713----
구영테크(053270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 구영테크 crawled / 2572 / 2713----
중앙에너비스(000440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 중앙에너비스 crawled / 2573 / 2713----
연이정보통신(090740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 연이정보통신 crawled / 2574 / 2713----
제일테크노스(038010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제일테크노스 crawled / 2575 / 2713----
아시아종묘(154030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아시아종묘 crawled / 2576 / 2713----
코리아에스이(101670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코리아에스이 crawled / 2577 / 2713----
한국큐빅(021650)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국큐빅 crawled / 2578 / 2713----
한양디지텍(078350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한양디지텍 crawled / 2579 / 2713----
스타플렉스(115570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스타플렉스 crawled / 2580 / 2713----
이루온(065440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이루온 crawled / 2581 / 2713----
코디(080530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코디 crawled / 2582 / 2713----
솔트웍스(230980)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 솔트웍스 crawled / 2583 / 2713----
이씨에스(067010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이씨에스 crawled / 2584 / 2713----
제이엠아이(033050)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이엠아이 crawled / 2585 / 2713----
세원(234100)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세원 crawled / 2586 / 2713----
삼일(032280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼일 crawled / 2587 / 2713----
디이엔티(079810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디이엔티 crawled / 2588 / 2713----
코닉글로리(094860)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 코닉글로리 crawled / 2589 / 2713----
모바일리더(100030)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 모바일리더 crawled / 2590 / 2713----
한네트(052600)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한네트 crawled / 2591 / 2713----
한국정보공학(039740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국정보공학 crawled / 2592 / 2713----
풍강(093380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 풍강 crawled / 2593 / 2713----
웹스(196700)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 웹스 crawled / 2594 / 2713----
제일제강(023440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제일제강 crawled / 2595 / 2713----
에프알텍(073540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에프알텍 crawled / 2596 / 2713----
마이크로컨텍솔(098120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 마이크로컨텍솔 crawled / 2597 / 2713----
멕아이씨에스(058110)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 멕아이씨에스 crawled / 2598 / 2713----
썬텍(122800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 썬텍 crawled / 2599 / 2713----
디젠스(113810)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디젠스 crawled / 2600 / 2713----
텔레필드(091440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 텔레필드 crawled / 2601 / 2713----
팬스타엔터프라이즈(054300)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 팬스타엔터프라이즈 crawled / 2602 / 2713----
유아이디(069330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유아이디 crawled / 2603 / 2713----
한컴지엠디(077280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한컴지엠디 crawled / 2604 / 2713----
삼우엠스(082660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼우엠스 crawled / 2605 / 2713----
피씨디렉트(051380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피씨디렉트 crawled / 2606 / 2713----
C&S자산관리(032040)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- C&S자산관리 crawled / 2607 / 2713----
동양에스텍(060380)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동양에스텍 crawled / 2608 / 2713----
쌍용정보통신(010280)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 쌍용정보통신 crawled / 2609 / 2713----
디엠티(134580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디엠티 crawled / 2610 / 2713----
에스폴리텍(050760)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스폴리텍 crawled / 2611 / 2713----
티피씨글로벌(130740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 티피씨글로벌 crawled / 2612 / 2713----
네이블(153460)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 네이블 crawled / 2613 / 2713----
로지시스(067730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 로지시스 crawled / 2614 / 2713----
대창솔루션(096350)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대창솔루션 crawled / 2615 / 2713----
피에스엠씨(024850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 피에스엠씨 crawled / 2616 / 2713----
에스제이케이(080440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스제이케이 crawled / 2617 / 2713----
토탈소프트(045340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 토탈소프트 crawled / 2618 / 2713----
케이엔더블유(105330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이엔더블유 crawled / 2619 / 2713----
한솔씨앤피(221610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔씨앤피 crawled / 2620 / 2713----
디지아이(043360)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디지아이 crawled / 2621 / 2713----
동방선기(099410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동방선기 crawled / 2622 / 2713----
성호전자(043260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 성호전자 crawled / 2623 / 2713----
바른테크놀로지(029480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 바른테크놀로지 crawled / 2624 / 2713----
오킨스전자(080580)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 오킨스전자 crawled / 2625 / 2713----
KJ프리텍(083470)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- KJ프리텍 crawled / 2626 / 2713----
케이피티(054410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이피티 crawled / 2627 / 2713----
케이에스피(073010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이에스피 crawled / 2628 / 2713----
이미지스(115610)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이미지스 crawled / 2629 / 2713----
제이웨이(058420)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이웨이 crawled / 2630 / 2713----
동일철강(023790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동일철강 crawled / 2631 / 2713----
행남자기(008800)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 행남자기 crawled / 2632 / 2713----
제너셈(217190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제너셈 crawled / 2633 / 2713----
카테아(026260)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 카테아 crawled / 2634 / 2713----
케이비제9호스팩(232270)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이비제9호스팩 crawled / 2635 / 2713----
PN풍년(024940)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- PN풍년 crawled / 2636 / 2713----
플레이위드(023770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 플레이위드 crawled / 2637 / 2713----
디비케이(073190)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 디비케이 crawled / 2638 / 2713----
옵토팩(123010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 옵토팩 crawled / 2639 / 2713----
우성아이비(194610)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 우성아이비 crawled / 2640 / 2713----
두올산업(078590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 두올산업 crawled / 2641 / 2713----
레이젠(047440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 레이젠 crawled / 2642 / 2713----
에스앤더블류(103230)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스앤더블류 crawled / 2643 / 2713----
아이텍반도체(119830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 아이텍반도체 crawled / 2644 / 2713----
삼보산업(009620)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 삼보산업 crawled / 2645 / 2713----
제미니투자(019570)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제미니투자 crawled / 2646 / 2713----
세진티에스(067770)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세진티에스 crawled / 2647 / 2713----
지어소프트(051160)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지어소프트 crawled / 2648 / 2713----
한솔인티큐브(070590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한솔인티큐브 crawled / 2649 / 2713----
광진실업(026910)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 광진실업 crawled / 2650 / 2713----
씨엔플러스(115530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 씨엔플러스 crawled / 2651 / 2713----
넥스트리밍(139670)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 넥스트리밍 crawled / 2652 / 2713----
현진소재(053660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 현진소재 crawled / 2653 / 2713----
이퓨쳐(134060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이퓨쳐 crawled / 2654 / 2713----
대동기어(008830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대동기어 crawled / 2655 / 2713----
누리플랜(069140)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 누리플랜 crawled / 2656 / 2713----
대동금속(020400)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대동금속 crawled / 2657 / 2713----
테라셈(182690)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 테라셈 crawled / 2658 / 2713----
광진윈텍(090150)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 광진윈텍 crawled / 2659 / 2713----
에스티오(098660)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스티오 crawled / 2660 / 2713----
제이티(089790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 제이티 crawled / 2661 / 2713----
신라에스지(025870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신라에스지 crawled / 2662 / 2713----
ITX엠투엠(099520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- ITX엠투엠 crawled / 2663 / 2713----
세동(053060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 세동 crawled / 2664 / 2713----
에스디시스템(121890)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에스디시스템 crawled / 2665 / 2713----
지디(155960)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 지디 crawled / 2666 / 2713----
엘디티(096870)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엘디티 crawled / 2667 / 2713----
이원컴포텍(088290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이원컴포텍 crawled / 2668 / 2713----
키움스팩4호(226850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 키움스팩4호 crawled / 2669 / 2713----
한국정밀기계(101680)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국정밀기계 crawled / 2670 / 2713----
청보산업(013720)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 청보산업 crawled / 2671 / 2713----
스틸플라워(087220)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 스틸플라워 crawled / 2672 / 2713----
영신금속(007530)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 영신금속 crawled / 2673 / 2713----
화신테크(086250)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 화신테크 crawled / 2674 / 2713----
하나금융7호스팩(230240)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나금융7호스팩 crawled / 2675 / 2713----
골든브릿지제4호스팩(227950)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 골든브릿지제4호스팩 crawled / 2676 / 2713----
엔에이치스팩12호(273060)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔에이치스팩12호 crawled / 2677 / 2713----
교보비엔케이스팩(242040)의 history 작업을 시작합니다.

DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 교보비엔케이스팩 crawled / 2678 / 2713----
엔에이치스팩10호(256630)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔에이치스팩10호 crawled / 2679 / 2713----
유진스팩3호(221200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 유진스팩3호 crawled / 2680 / 2713----
엔에이치스팩11호(256840)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 엔에이치스팩11호 crawled / 2681 / 2713----
에이치엠씨3호스팩(226340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 에이치엠씨3호스팩 crawled / 2682 / 2713----
하이제3호스팩(217500)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이제3호스팩 crawled / 2683 / 2713----
신한제4호스팩(277480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한제4호스팩 crawled / 2684 / 2713----
한국4호스팩(240540)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국4호스팩 crawled / 2685 / 2713----
대신밸런스제3호스팩(253590)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신밸런스제3호스팩 crawled / 2686 / 2713----
동부제4호스팩(230490)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동부제4호스팩 crawled / 2687 / 2713----
케이비제10호스팩(250930)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이비제10호스팩 crawled / 2688 / 2713----
대신밸런스제4호스팩(262830)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대신밸런스제4호스팩 crawled / 2689 / 2713----
미래에셋대우스팩1호(265480)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋대우스팩1호 crawled / 2690 / 2713----
하이에이아이1호스팩(235010)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하이에이아이1호스팩 crawled / 2691 / 2713----
미래에셋제5호스팩(239340)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 미래에셋제5호스팩 crawled / 2692 / 2713----
동부스팩5호(281740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동부스팩5호 crawled / 2693 / 2713----
IBKS제3호스팩(225430)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- IBKS제3호스팩 crawled / 2694 / 2713----
IBKS제5호스팩(254120)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- IBKS제5호스팩 crawled / 2695 / 2713----
IBKS제6호스팩(264850)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- IBKS제6호스팩 crawled / 2696 / 2713----
하나금융10호스팩(270520)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나금융10호스팩 crawled / 2697 / 2713----
동부스팩3호(226440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 동부스팩3호 crawled / 2698 / 2713----
한국제6호스팩(281410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국제6호스팩 crawled / 2699 / 2713----
한화수성스팩(265920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화수성스팩 crawled / 2700 / 2713----
하나금융9호스팩(261200)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 하나금융9호스팩 crawled / 2701 / 2713----
이베스트스팩3호(225440)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 이베스트스팩3호 crawled / 2702 / 2713----
교보7호스팩(267320)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 교보7호스팩 crawled / 2703 / 2713----
한국제5호스팩(271740)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한국제5호스팩 crawled / 2704 / 2713----
신한제3호스팩(257730)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 신한제3호스팩 crawled / 2705 / 2713----
IBKS제7호스팩(276920)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- IBKS제7호스팩 crawled / 2706 / 2713----
SK3호스팩(232330)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- SK3호스팩 crawled / 2707 / 2713----
한화에이스스팩4호(279410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화에이스스팩4호 crawled / 2708 / 2713----
대호피앤씨우(021045)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 대호피앤씨우 crawled / 2709 / 2713----
케이비제11호스팩(258790)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 케이비제11호스팩 crawled / 2710 / 2713----
한화에이스스팩3호(264290)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 한화에이스스팩3호 crawled / 2711 / 2713----
IBKS제8호스팩(277410)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- IBKS제8호스팩 crawled / 2712 / 2713----
소프트센우(032685)의 history 작업을 시작합니다.
DB기간과 겹치는 기간이 없었습니다.
2018-04-16 00:00:00 ~ 2018-04-17 00:00:00 기간의
데이터가 크롤 및 저장 되었습니다 INSERT COUNT: 1
총 1개의 데이터가 크롤 및 INSERT 되었습니다. INSERT COUNT: 1
---- 소프트센우 crawled / 2713 / 2713----

In [11]:
# Crawl Company Financial Data
finance_crawler.save_company_information()

총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005930의 재무정보를 가져왔습니다.
1/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000660의 재무정보를 가져왔습니다.
2/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
207940의 재무정보를 가져왔습니다.
3/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
4/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068270의 재무정보를 가져왔습니다.
5/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005380의 재무정보를 가져왔습니다.
6/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005490의 재무정보를 가져왔습니다.
7/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051910의 재무정보를 가져왔습니다.
8/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
028260의 재무정보를 가져왔습니다.
9/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035420의 재무정보를 가져왔습니다.
10/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105560는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
11/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012330의 재무정보를 가져왔습니다.
12/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032830는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
13/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015760의 재무정보를 가져왔습니다.
14/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
055550는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
15/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034730의 재무정보를 가져왔습니다.
16/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051900의 재무정보를 가져왔습니다.
17/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090430의 재무정보를 가져왔습니다.
18/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096770의 재무정보를 가져왔습니다.
19/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017670의 재무정보를 가져왔습니다.
20/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018260의 재무정보를 가져왔습니다.
21/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066570의 재무정보를 가져왔습니다.
22/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003550의 재무정보를 가져왔습니다.
23/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011170의 재무정보를 가져왔습니다.
24/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033780의 재무정보를 가져왔습니다.
25/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010950의 재무정보를 가져왔습니다.
26/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006400의 재무정보를 가져왔습니다.
27/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086790는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
28/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000270의 재무정보를 가져왔습니다.
29/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000810는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
30/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
251270의 재무정보를 가져왔습니다.
31/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002790의 재무정보를 가져왔습니다.
32/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000030는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
33/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035720의 재무정보를 가져왔습니다.
34/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034220의 재무정보를 가져왔습니다.
35/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024110는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
36/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009540의 재무정보를 가져왔습니다.
37/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010130의 재무정보를 가져왔습니다.
38/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036570의 재무정보를 가져왔습니다.
39/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009150의 재무정보를 가져왔습니다.
40/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139480의 재무정보를 가져왔습니다.
41/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030200의 재무정보를 가져왔습니다.
42/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023530의 재무정보를 가져왔습니다.
43/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267250의 재무정보를 가져왔습니다.
44/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004020의 재무정보를 가져왔습니다.
45/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
021240의 재무정보를 가져왔습니다.
46/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086280의 재무정보를 가져왔습니다.
47/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
161390의 재무정보를 가져왔습니다.
48/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
128940의 재무정보를 가져왔습니다.
49/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018880의 재무정보를 가져왔습니다.
50/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006800는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
51/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008930의 재무정보를 가져왔습니다.
52/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035250의 재무정보를 가져왔습니다.

53/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078930의 재무정보를 가져왔습니다.
54/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069500의 재무정보를 가져왔습니다.
55/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032640의 재무정보를 가져왔습니다.
56/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
088350는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
57/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
271560의 재무정보를 가져왔습니다.
58/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009830의 재무정보를 가져왔습니다.
59/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
097950의 재무정보를 가져왔습니다.
60/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000720의 재무정보를 가져왔습니다.
61/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036460의 재무정보를 가져왔습니다.
62/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001040의 재무정보를 가져왔습니다.
63/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004990의 재무정보를 가져왔습니다.
64/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047810의 재무정보를 가져왔습니다.
65/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071050는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
66/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004800의 재무정보를 가져왔습니다.
67/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005830는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
68/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
029780는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
69/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010060의 재무정보를 가져왔습니다.
70/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004170의 재무정보를 가져왔습니다.
71/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008770의 재무정보를 가져왔습니다.
72/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005940는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
73/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002380의 재무정보를 가져왔습니다.
74/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
75/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012750의 재무정보를 가져왔습니다.
76/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
028050의 재무정보를 가져왔습니다.
77/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009240의 재무정보를 가져왔습니다.
78/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138930는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
79/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012630의 재무정보를 가져왔습니다.
80/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001450는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
81/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016360는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
82/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003490의 재무정보를 가져왔습니다.
83/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079440는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
84/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241560의 재무정보를 가져왔습니다.
85/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
088980는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
86/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
282330의 재무정보를 가져왔습니다.
87/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000120의 재무정보를 가져왔습니다.
88/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000100의 재무정보를 가져왔습니다.
89/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010140의 재무정보를 가져왔습니다.
90/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102110의 재무정보를 가져왔습니다.
91/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011070의 재무정보를 가져왔습니다.
92/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011780의 재무정보를 가져왔습니다.
93/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042660의 재무정보를 가져왔습니다.
94/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047050의 재무정보를 가져왔습니다.
95/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000880의 재무정보를 가져왔습니다.
96/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000210의 재무정보를 가져왔습니다.
97/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007070의 재무정보를 가져왔습니다.
98/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
026960의 재무정보를 가져왔습니다.
99/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007310의 재무정보를 가져왔습니다.
100/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
028670의 재무정보를 가져왔습니다.
101/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006280의 재무정보를 가져왔습니다.
102/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008560는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
103/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006360의 재무정보를 가져왔습니다.
104/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039490는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
105/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069620의 재무정보를 가져왔습니다.
106/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122630의 재무정보를 가져왔습니다.
107/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047040의 재무정보를 가져왔습니다.
108/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003410의 재무정보를 가져왔습니다.
109/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000060는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
110/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
111/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006260의 재무정보를 가져왔습니다.
112/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204320의 재무정보를 가져왔습니다.
113/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030000의 재무정보를 가져왔습니다.
114/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069960의 재무정보를 가져왔습니다.
115/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000150의 재무정보를 가져왔습니다.
116/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017800의 재무정보를 가져왔습니다.
117/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051600의 재무정보를 가져왔습니다.
118/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138040는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
119/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139130는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
120/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005250의 재무정보를 가져왔습니다.
121/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004370의 재무정보를 가져왔습니다.
122/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010620의 재무정보를 가져왔습니다.
123/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006650의 재무정보를 가져왔습니다.
124/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
125/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010120의 재무정보를 가져왔습니다.
126/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004000의 재무정보를 가져왔습니다.
127/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009420의 재무정보를 가져왔습니다.
128/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042670의 재무정보를 가져왔습니다.
129/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071840의 재무정보를 가져왔습니다.
130/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267270의 재무정보를 가져왔습니다.
131/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000240의 재무정보를 가져왔습니다.
132/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
161890의 재무정보를 가져왔습니다.
133/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
120110의 재무정보를 가져왔습니다.
134/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003520의 재무정보를 가져왔습니다.
135/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012510의 재무정보를 가져왔습니다.
136/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
137/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
020150의 재무정보를 가져왔습니다.
138/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000670의 재무정보를 가져왔습니다.
139/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034020의 재무정보를 가져왔습니다.
140/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001800의 재무정보를 가져왔습니다.
141/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079160의 재무정보를 가져왔습니다.
142/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
143/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
081660의 재무정보를 가져왔습니다.
144/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114090의 재무정보를 가져왔습니다.
145/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011200의 재무정보를 가져왔습니다.
146/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005440의 재무정보를 가져왔습니다.
147/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000080의 재무정보를 가져왔습니다.
148/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192820의 재무정보를 가져왔습니다.
149/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
233740의 재무정보를 가져왔습니다.
150/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012450의 재무정보를 가져왔습니다.
151/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011210의 재무정보를 가져왔습니다.
152/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064350의 재무정보를 가져왔습니다.
153/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011790의 재무정보를 가져왔습니다.
154/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003000의 재무정보를 가져왔습니다.
155/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115390의 재무정보를 가져왔습니다.
156/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003240의 재무정보를 가져왔습니다.
157/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003690는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
158/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001740의 재무정보를 가져왔습니다.
159/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005690의 재무정보를 가져왔습니다.

160/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
148020의 재무정보를 가져왔습니다.
161/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
082640는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
162/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039130의 재무정보를 가져왔습니다.
163/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226320의 재무정보를 가져왔습니다.
164/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
185750의 재무정보를 가져왔습니다.
165/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
180640의 재무정보를 가져왔습니다.
166/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
181710의 재무정보를 가져왔습니다.
167/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214320의 재무정보를 가져왔습니다.
168/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005300의 재무정보를 가져왔습니다.
169/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003090의 재무정보를 가져왔습니다.
170/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027410의 재무정보를 가져왔습니다.
171/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
057050의 재무정보를 가져왔습니다.
172/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
285130의 재무정보를 가져왔습니다.
173/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089590의 재무정보를 가져왔습니다.
174/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102780의 재무정보를 가져왔습니다.
175/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002350의 재무정보를 가져왔습니다.
176/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
111770의 재무정보를 가져왔습니다.
177/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
229200의 재무정보를 가져왔습니다.
178/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
153130의 재무정보를 가져왔습니다.
179/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014820의 재무정보를 가져왔습니다.
180/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018250의 재무정보를 가져왔습니다.
181/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006040의 재무정보를 가져왔습니다.
182/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001440의 재무정보를 가져왔습니다.
183/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005610의 재무정보를 가져왔습니다.
184/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
103140의 재무정보를 가져왔습니다.
185/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052690의 재무정보를 가져왔습니다.
186/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001120의 재무정보를 가져왔습니다.
187/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
020560의 재무정보를 가져왔습니다.
188/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069260의 재무정보를 가져왔습니다.
189/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
282000의 재무정보를 가져왔습니다.
190/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
170900의 재무정보를 가져왔습니다.
191/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023590의 재무정보를 가져왔습니다.
192/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079550의 재무정보를 가져왔습니다.
193/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006840의 재무정보를 가져왔습니다.
194/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073240의 재무정보를 가져왔습니다.
195/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006490의 재무정보를 가져왔습니다.
196/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
175330는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
197/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272450의 재무정보를 가져왔습니다.
198/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
152100의 재무정보를 가져왔습니다.
199/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071320의 재무정보를 가져왔습니다.
200/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033180의 재무정보를 가져왔습니다.
201/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001230의 재무정보를 가져왔습니다.
202/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093370의 재무정보를 가져왔습니다.
203/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001060의 재무정보를 가져왔습니다.
204/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031430의 재무정보를 가져왔습니다.
205/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
145990의 재무정보를 가져왔습니다.
206/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003300의 재무정보를 가져왔습니다.
207/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105630의 재무정보를 가져왔습니다.
208/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018670의 재무정보를 가져왔습니다.
209/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001430의 재무정보를 가져왔습니다.
210/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214980의 재무정보를 가져왔습니다.
211/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
085620는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
212/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
157450의 재무정보를 가져왔습니다.
213/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
284740의 재무정보를 가져왔습니다.
214/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010780의 재무정보를 가져왔습니다.
215/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001680의 재무정보를 가져왔습니다.
216/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000370는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
217/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
145720의 재무정보를 가져왔습니다.
218/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032350의 재무정보를 가져왔습니다.
219/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003470는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
220/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069660의 재무정보를 가져왔습니다.
221/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000640의 재무정보를 가져왔습니다.
222/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007570의 재무정보를 가져왔습니다.
223/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093050의 재무정보를 가져왔습니다.
224/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014680의 재무정보를 가져왔습니다.
225/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009410의 재무정보를 가져왔습니다.
226/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
020000의 재무정보를 가져왔습니다.
227/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009450의 재무정보를 가져왔습니다.
228/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267260의 재무정보를 가져왔습니다.
229/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049770의 재무정보를 가져왔습니다.
230/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024720의 재무정보를 가져왔습니다.
231/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000070의 재무정보를 가져왔습니다.
232/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002270의 재무정보를 가져왔습니다.
233/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105190의 재무정보를 가져왔습니다.
234/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007460의 재무정보를 가져왔습니다.
235/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005850의 재무정보를 가져왔습니다.
236/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
280360의 재무정보를 가져왔습니다.
237/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009970의 재무정보를 가져왔습니다.
238/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034830는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
239/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
240/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
108670의 재무정보를 가져왔습니다.
241/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004430의 재무정보를 가져왔습니다.
242/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272580의 재무정보를 가져왔습니다.
243/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114800의 재무정보를 가져왔습니다.
244/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042700의 재무정보를 가져왔습니다.
245/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003620의 재무정보를 가져왔습니다.
246/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003540는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
247/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
278540의 재무정보를 가져왔습니다.
248/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034310의 재무정보를 가져왔습니다.
249/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007700의 재무정보를 가져왔습니다.
250/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005500의 재무정보를 가져왔습니다.
251/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019680의 재무정보를 가져왔습니다.
252/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005880의 재무정보를 가져왔습니다.
253/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025860의 재무정보를 가져왔습니다.
254/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000990의 재무정보를 가져왔습니다.
255/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
029530의 재무정보를 가져왔습니다.
256/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
257/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096760의 재무정보를 가져왔습니다.
258/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002020의 재무정보를 가져왔습니다.
259/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123890는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
260/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037560의 재무정보를 가져왔습니다.
261/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005180의 재무정보를 가져왔습니다.
262/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003230의 재무정보를 가져왔습니다.
263/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019170의 재무정보를 가져왔습니다.
264/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002240의 재무정보를 가져왔습니다.
265/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025620의 재무정보를 가져왔습니다.
266/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
232080의 재무정보를 가져왔습니다.
267/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241590의 재무정보를 가져왔습니다.
268/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053210의 재무정보를 가져왔습니다.
269/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
270/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
112610의 재무정보를 가져왔습니다.
271/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064960의 재무정보를 가져왔습니다.
272/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192530는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
273/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017810의 재무정보를 가져왔습니다.
274/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192400의 재무정보를 가져왔습니다.
275/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031440의 재무정보를 가져왔습니다.
276/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002210의 재무정보를 가져왔습니다.
277/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079430의 재무정보를 가져왔습니다.
278/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
278530의 재무정보를 가져왔습니다.
279/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007630의 재무정보를 가져왔습니다.
280/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001820의 재무정보를 가져왔습니다.
281/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025540의 재무정보를 가져왔습니다.
282/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001720는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
283/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
273130의 재무정보를 가져왔습니다.
284/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
249420의 재무정보를 가져왔습니다.
285/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060980의 재무정보를 가져왔습니다.
286/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003850의 재무정보를 가져왔습니다.
287/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058650의 재무정보를 가져왔습니다.
288/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003530는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
289/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009290의 재무정보를 가져왔습니다.
290/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072710의 재무정보를 가져왔습니다.
291/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033920의 재무정보를 가져왔습니다.
292/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002390의 재무정보를 가져왔습니다.
293/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
126560의 재무정보를 가져왔습니다.
294/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
271980의 재무정보를 가져왔습니다.
295/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033270의 재무정보를 가져왔습니다.
296/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003920의 재무정보를 가져왔습니다.
297/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500019의 재무정보를 가져왔습니다.
298/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034120의 재무정보를 가져왔습니다.
299/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016580의 재무정보를 가져왔습니다.
300/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138250의 재무정보를 가져왔습니다.
301/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011690의 재무정보를 가져왔습니다.
302/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
234080의 재무정보를 가져왔습니다.
303/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003030의 재무정보를 가져왔습니다.
304/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004690의 재무정보를 가져왔습니다.
305/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
210980의 재무정보를 가져왔습니다.
306/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006120의 재무정보를 가져왔습니다.
307/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001520의 재무정보를 가져왔습니다.
308/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
161000의 재무정보를 가져왔습니다.
309/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004490의 재무정보를 가져왔습니다.
310/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006060의 재무정보를 가져왔습니다.
311/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036580의 재무정보를 가져왔습니다.
312/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078520의 재무정보를 가져왔습니다.
313/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008730의 재무정보를 가져왔습니다.
314/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014830의 재무정보를 가져왔습니다.
315/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002960의 재무정보를 가져왔습니다.
316/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033660는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
317/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
281820의 재무정보를 가져왔습니다.
318/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017390의 재무정보를 가져왔습니다.
319/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101530의 재무정보를 가져왔습니다.
320/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102460의 재무정보를 가져왔습니다.
321/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004380의 재무정보를 가져왔습니다.
322/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030790의 재무정보를 가져왔습니다.
323/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011810의 재무정보를 가져왔습니다.
324/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
074610의 재무정보를 가져왔습니다.
325/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009580의 재무정보를 가져왔습니다.
326/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017940의 재무정보를 가져왔습니다.
327/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000400는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
328/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004870의 재무정보를 가져왔습니다.
329/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010050는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
330/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008060의 재무정보를 가져왔습니다.
331/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101060의 재무정보를 가져왔습니다.
332/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000050의 재무정보를 가져왔습니다.
333/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003060의 재무정보를 가져왔습니다.
334/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015350의 재무정보를 가져왔습니다.
335/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003220의 재무정보를 가져왔습니다.
336/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091090의 재무정보를 가져왔습니다.
337/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079980의 재무정보를 가져왔습니다.
338/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
213500의 재무정보를 가져왔습니다.
339/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004960의 재무정보를 가져왔습니다.
340/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005810의 재무정보를 가져왔습니다.
341/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
342/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001630의 재무정보를 가져왔습니다.
343/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
082740의 재무정보를 가져왔습니다.
344/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005420의 재무정보를 가져왔습니다.
345/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214390의 재무정보를 가져왔습니다.
346/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000540는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
347/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008490의 재무정보를 가져왔습니다.
348/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
349/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
136490의 재무정보를 가져왔습니다.
350/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
183190의 재무정보를 가져왔습니다.
351/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002990의 재무정보를 가져왔습니다.
352/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037710의 재무정보를 가져왔습니다.
353/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005720의 재무정보를 가져왔습니다.
354/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001510는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
355/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
356/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016800의 재무정보를 가져왔습니다.
357/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006380의 재무정보를 가져왔습니다.
358/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007690의 재무정보를 가져왔습니다.
359/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016450의 재무정보를 가져왔습니다.
360/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000020의 재무정보를 가져왔습니다.
361/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
362/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002000의 재무정보를 가져왔습니다.
363/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570019의 재무정보를 가져왔습니다.
364/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094800는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
365/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
097230의 재무정보를 가져왔습니다.
366/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
070960의 재무정보를 가져왔습니다.
367/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004130의 재무정보를 가져왔습니다.
368/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
176950의 재무정보를 가져왔습니다.
369/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252670의 재무정보를 가져왔습니다.
370/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292190의 재무정보를 가져왔습니다.
371/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007160의 재무정보를 가져왔습니다.
372/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030610는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.

373/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084690의 재무정보를 가져왔습니다.
374/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000480의 재무정보를 가져왔습니다.
375/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122900의 재무정보를 가져왔습니다.
376/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009680의 재무정보를 가져왔습니다.
377/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007340의 재무정보를 가져왔습니다.
378/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001390의 재무정보를 가져왔습니다.
379/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044820의 재무정보를 가져왔습니다.
380/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214420의 재무정보를 가져왔습니다.
381/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001200는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
382/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002250의 재무정보를 가져왔습니다.
383/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003120의 재무정보를 가져왔습니다.
384/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
196230의 재무정보를 가져왔습니다.
385/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030210는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
386/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095570의 재무정보를 가져왔습니다.
387/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003560의 재무정보를 가져왔습니다.
388/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104700의 재무정보를 가져왔습니다.
389/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
152330의 재무정보를 가져왔습니다.
390/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
161510의 재무정보를 가져왔습니다.
391/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
195870의 재무정보를 가져왔습니다.
392/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033240의 재무정보를 가져왔습니다.
393/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
394/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
270810의 재무정보를 가져왔습니다.
395/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
268280의 재무정보를 가져왔습니다.
396/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
278240의 재무정보를 가져왔습니다.
397/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001500는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
398/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
152870의 재무정보를 가져왔습니다.
399/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001780의 재무정보를 가져왔습니다.
400/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
275980의 재무정보를 가져왔습니다.
401/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
029460의 재무정보를 가져왔습니다.
402/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027390의 재무정보를 가져왔습니다.
403/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272550의 재무정보를 가져왔습니다.
404/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102260의 재무정보를 가져왔습니다.
405/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035510의 재무정보를 가져왔습니다.
406/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004710의 재무정보를 가져왔습니다.
407/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139260의 재무정보를 가져왔습니다.
408/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002810의 재무정보를 가져왔습니다.
409/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011930의 재무정보를 가져왔습니다.
410/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007210의 재무정보를 가져왔습니다.
411/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025000의 재무정보를 가져왔습니다.
412/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138490의 재무정보를 가져왔습니다.
413/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068400의 재무정보를 가져왔습니다.
414/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016590의 재무정보를 가져왔습니다.
415/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005070의 재무정보를 가져왔습니다.
416/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016380의 재무정보를 가져왔습니다.
417/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001130의 재무정보를 가져왔습니다.
418/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002030의 재무정보를 가져왔습니다.
419/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000520의 재무정보를 가져왔습니다.
420/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
150460의 재무정보를 가져왔습니다.
421/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002780의 재무정보를 가져왔습니다.
422/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092230의 재무정보를 가져왔습니다.
423/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002320의 재무정보를 가져왔습니다.
424/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123690의 재무정보를 가져왔습니다.
425/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001250의 재무정보를 가져왔습니다.

426/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017960의 재무정보를 가져왔습니다.
427/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
077970의 재무정보를 가져왔습니다.
428/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004970의 재무정보를 가져왔습니다.
429/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000430의 재무정보를 가져왔습니다.
430/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
081000의 재무정보를 가져왔습니다.
431/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002310의 재무정보를 가져왔습니다.
432/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004360의 재무정보를 가져왔습니다.
433/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015860의 재무정보를 가져왔습니다.
434/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003200의 재무정보를 가져왔습니다.
435/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003570의 재무정보를 가져왔습니다.
436/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004700의 재무정보를 가져왔습니다.
437/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003070의 재무정보를 가져왔습니다.
438/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008700의 재무정보를 가져왔습니다.
439/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015360의 재무정보를 가져왔습니다.
440/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192090의 재무정보를 가져왔습니다.
441/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012610의 재무정보를 가져왔습니다.
442/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204480의 재무정보를 가져왔습니다.
443/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001270는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
444/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001940의 재무정보를 가져왔습니다.
445/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011760의 재무정보를 가져왔습니다.
446/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000680의 재무정보를 가져왔습니다.
447/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005680의 재무정보를 가져왔습니다.
448/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006390의 재무정보를 가져왔습니다.
449/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900140의 재무정보를 가져왔습니다.
450/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000970의 재무정보를 가져왔습니다.
451/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017180의 재무정보를 가져왔습니다.
452/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095720의 재무정보를 가져왔습니다.
453/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
454/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004310의 재무정보를 가져왔습니다.
455/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
456/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084010의 재무정보를 가져왔습니다.
457/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004150의 재무정보를 가져왔습니다.
458/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139280의 재무정보를 가져왔습니다.
459/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036530의 재무정보를 가져왔습니다.
460/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226490의 재무정보를 가져왔습니다.
461/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016880의 재무정보를 가져왔습니다.
462/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000140의 재무정보를 가져왔습니다.
463/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
251340의 재무정보를 가져왔습니다.
464/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200880의 재무정보를 가져왔습니다.
465/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011280의 재무정보를 가져왔습니다.
466/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292050의 재무정보를 가져왔습니다.
467/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001360의 재무정보를 가져왔습니다.
468/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
229640의 재무정보를 가져왔습니다.
469/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005740의 재무정보를 가져왔습니다.
470/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
143210의 재무정보를 가져왔습니다.
471/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039570의 재무정보를 가져왔습니다.
472/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007810의 재무정보를 가져왔습니다.
473/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000860의 재무정보를 가져왔습니다.
474/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008040의 재무정보를 가져왔습니다.
475/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003350의 재무정보를 가져왔습니다.
476/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001880의 재무정보를 가져왔습니다.
477/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
077500의 재무정보를 가져왔습니다.
478/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
479/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089470의 재무정보를 가져왔습니다.
480/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
194370의 재무정보를 가져왔습니다.
481/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004250의 재무정보를 가져왔습니다.
482/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001790의 재무정보를 가져왔습니다.
483/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
210540의 재무정보를 가져왔습니다.
484/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009270의 재무정보를 가져왔습니다.
485/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
282690의 재무정보를 가져왔습니다.
486/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000320의 재무정보를 가져왔습니다.
487/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005090의 재무정보를 가져왔습니다.
488/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002630의 재무정보를 가져왔습니다.
489/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
103130의 재무정보를 가져왔습니다.
490/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044450의 재무정보를 가져왔습니다.
491/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005960의 재무정보를 가져왔습니다.
492/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002450의 재무정보를 가져왔습니다.
493/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
128820의 재무정보를 가져왔습니다.
494/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005390의 재무정보를 가져왔습니다.
495/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
168490는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
496/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000180의 재무정보를 가져왔습니다.
497/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
168580의 재무정보를 가져왔습니다.
498/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002840의 재무정보를 가져왔습니다.
499/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011160의 재무정보를 가져왔습니다.
500/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
026890의 재무정보를 가져왔습니다.
501/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005950의 재무정보를 가져왔습니다.
502/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000390의 재무정보를 가져왔습니다.
503/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000700의 재무정보를 가져왔습니다.
504/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267290의 재무정보를 가져왔습니다.
505/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002460의 재무정보를 가져왔습니다.
506/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
245710의 재무정보를 가져왔습니다.
507/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
103590의 재무정보를 가져왔습니다.
508/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001460의 재무정보를 가져왔습니다.
509/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004890의 재무정보를 가져왔습니다.
510/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000490의 재무정보를 가져왔습니다.
511/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
143860의 재무정보를 가져왔습니다.
512/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005870의 재무정보를 가져왔습니다.
513/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
075580의 재무정보를 가져왔습니다.
514/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017900의 재무정보를 가져왔습니다.
515/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
248170의 재무정보를 가져왔습니다.
516/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084680의 재무정보를 가져왔습니다.
517/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002150의 재무정보를 가져왔습니다.
518/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010820의 재무정보를 가져왔습니다.
519/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067830의 재무정보를 가져왔습니다.
520/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
521/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
522/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016610는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
523/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102280의 재무정보를 가져왔습니다.
524/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012690의 재무정보를 가져왔습니다.
525/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003960의 재무정보를 가져왔습니다.
526/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013870의 재무정보를 가져왔습니다.
527/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009320의 재무정보를 가져왔습니다.
528/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
529/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015890의 재무정보를 가져왔습니다.
530/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004560의 재무정보를 가져왔습니다.
531/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
085310의 재무정보를 가져왔습니다.
532/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092200의 재무정보를 가져왔습니다.
533/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001260의 재무정보를 가져왔습니다.
534/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
020760의 재무정보를 가져왔습니다.
535/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003460는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
536/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004060의 재무정보를 가져왔습니다.
537/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
264900의 재무정보를 가져왔습니다.
538/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041650의 재무정보를 가져왔습니다.
539/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
540/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002760의 재무정보를 가져왔습니다.
541/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
028100의 재무정보를 가져왔습니다.
542/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
117580의 재무정보를 가져왔습니다.
543/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011000의 재무정보를 가져왔습니다.
544/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
134790의 재무정보를 가져왔습니다.
545/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000230의 재무정보를 가져왔습니다.
546/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078000의 재무정보를 가져왔습니다.
547/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058430의 재무정보를 가져왔습니다.
548/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102970의 재무정보를 가져왔습니다.
549/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090350의 재무정보를 가져왔습니다.
550/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019440의 재무정보를 가져왔습니다.
551/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013570의 재무정보를 가져왔습니다.
552/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033530의 재무정보를 가져왔습니다.
553/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002360의 재무정보를 가져왔습니다.
554/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003830의 재무정보를 가져왔습니다.
555/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013580의 재무정보를 가져왔습니다.
556/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014790의 재무정보를 가져왔습니다.
557/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007980의 재무정보를 가져왔습니다.
558/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003160의 재무정보를 가져왔습니다.
559/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007660의 재무정보를 가져왔습니다.
560/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004540의 재무정보를 가져왔습니다.
561/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001340의 재무정보를 가져왔습니다.
562/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100250의 재무정보를 가져왔습니다.
563/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012030의 재무정보를 가져왔습니다.
564/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017040의 재무정보를 가져왔습니다.
565/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
144620의 재무정보를 가져왔습니다.
566/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
567/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002100의 재무정보를 가져왔습니다.
568/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035150의 재무정보를 가져왔습니다.
569/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272560의 재무정보를 가져왔습니다.
570/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013520의 재무정보를 가져왔습니다.
571/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006220는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
572/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004720의 재무정보를 가져왔습니다.
573/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094280의 재무정보를 가져왔습니다.
574/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007860의 재무정보를 가져왔습니다.
575/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037270의 재무정보를 가져왔습니다.
576/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024090의 재무정보를 가져왔습니다.
577/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015590의 재무정보를 가져왔습니다.
578/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035000의 재무정보를 가져왔습니다.
579/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092220의 재무정보를 가져왔습니다.
580/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034300의 재무정보를 가져왔습니다.
581/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
233160의 재무정보를 가져왔습니다.
582/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005430의 재무정보를 가져왔습니다.
583/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
277630의 재무정보를 가져왔습니다.
584/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014990의 재무정보를 가져왔습니다.
585/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002620의 재무정보를 가져왔습니다.
586/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084870의 재무정보를 가져왔습니다.
587/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
063160의 재무정보를 가져왔습니다.
588/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004980의 재무정보를 가져왔습니다.
589/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071970의 재무정보를 가져왔습니다.
590/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
591/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032560의 재무정보를 가져왔습니다.
592/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004840의 재무정보를 가져왔습니다.
593/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
594/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014280의 재무정보를 가져왔습니다.
595/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003650의 재무정보를 가져왔습니다.
596/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025560의 재무정보를 가져왔습니다.
597/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010690의 재무정보를 가져왔습니다.
598/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001290는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
599/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009200의 재무정보를 가져왔습니다.
600/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090370의 재무정보를 가져왔습니다.
601/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
251350의 재무정보를 가져왔습니다.
602/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
603/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002600의 재무정보를 가져왔습니다.
604/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007110의 재무정보를 가져왔습니다.
605/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004440의 재무정보를 가져왔습니다.
606/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007610의 재무정보를 가져왔습니다.
607/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012200의 재무정보를 가져왔습니다.
608/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
152550는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
609/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
273140의 재무정보를 가져왔습니다.
610/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002170의 재무정보를 가져왔습니다.
611/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530013의 재무정보를 가져왔습니다.
612/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225800의 재무정보를 가져왔습니다.
613/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034590의 재무정보를 가져왔습니다.
614/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100220의 재무정보를 가져왔습니다.
615/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003280의 재무정보를 가져왔습니다.
616/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
055490의 재무정보를 가져왔습니다.
617/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292160의 재무정보를 가져왔습니다.
618/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016710의 재무정보를 가져왔습니다.
619/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017370의 재무정보를 가져왔습니다.
620/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092440의 재무정보를 가져왔습니다.
621/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001470의 재무정보를 가져왔습니다.
622/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003080의 재무정보를 가져왔습니다.
623/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002900의 재무정보를 가져왔습니다.
624/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069640의 재무정보를 가져왔습니다.
625/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004200의 재무정보를 가져왔습니다.
626/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023000의 재무정보를 가져왔습니다.
627/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000650의 재무정보를 가져왔습니다.
628/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002720의 재무정보를 가져왔습니다.
629/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
223190의 재무정보를 가져왔습니다.
630/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
227840의 재무정보를 가져왔습니다.
631/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009160의 재무정보를 가져왔습니다.
632/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008970의 재무정보를 가져왔습니다.
633/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005980의 재무정보를 가져왔습니다.
634/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006090의 재무정보를 가져왔습니다.
635/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016740의 재무정보를 가져왔습니다.
636/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001380의 재무정보를 가져왔습니다.
637/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025750의 재무정보를 가져왔습니다.
638/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008350의 재무정보를 가져왔습니다.
639/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005800의 재무정보를 가져왔습니다.
640/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
134380의 재무정보를 가져왔습니다.
641/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010960의 재무정보를 가져왔습니다.
642/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530026의 재무정보를 가져왔습니다.

643/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
075180의 재무정보를 가져왔습니다.
644/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009470의 재무정보를 가져왔습니다.
645/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
190620의 재무정보를 가져왔습니다.
646/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
021820의 재무정보를 가져왔습니다.
647/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001530의 재무정보를 가져왔습니다.
648/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
111110의 재무정보를 가져왔습니다.
649/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
650/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004770의 재무정보를 가져왔습니다.
651/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267770의 재무정보를 가져왔습니다.
652/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012160의 재무정보를 가져왔습니다.
653/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009440의 재무정보를 가져왔습니다.
654/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
277650의 재무정보를 가져왔습니다.
655/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006340의 재무정보를 가져왔습니다.
656/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014530의 재무정보를 가져왔습니다.
657/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
293180의 재무정보를 가져왔습니다.
658/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002700의 재무정보를 가져왔습니다.
659/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000850의 재무정보를 가져왔습니다.
660/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252710의 재무정보를 가져왔습니다.
661/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
109070의 재무정보를 가져왔습니다.
662/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091170의 재무정보를 가져왔습니다.
663/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002300의 재무정보를 가져왔습니다.
664/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530024의 재무정보를 가져왔습니다.
665/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014710의 재무정보를 가져왔습니다.
666/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000220의 재무정보를 가져왔습니다.
667/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004910의 재무정보를 가져왔습니다.
668/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004450의 재무정보를 가져왔습니다.
669/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016090의 재무정보를 가져왔습니다.
670/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047400의 재무정보를 가져왔습니다.
671/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006370의 재무정보를 가져왔습니다.
672/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226980의 재무정보를 가져왔습니다.
673/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009310의 재무정보를 가져왔습니다.
674/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011700의 재무정보를 가져왔습니다.
675/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000890의 재무정보를 가져왔습니다.
676/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261250의 재무정보를 가져왔습니다.
677/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530031의 재무정보를 가져왔습니다.
678/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
130660의 재무정보를 가져왔습니다.
679/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002880의 재무정보를 가져왔습니다.
680/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011090의 재무정보를 가져왔습니다.
681/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008600의 재무정보를 가져왔습니다.
682/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003580의 재무정보를 가져왔습니다.
683/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007590의 재무정보를 가져왔습니다.
684/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004080의 재무정보를 가져왔습니다.
685/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058850의 재무정보를 가져왔습니다.
686/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
156080의 재무정보를 가져왔습니다.
687/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003480의 재무정보를 가져왔습니다.
688/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100840의 재무정보를 가져왔습니다.
689/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
143850의 재무정보를 가져왔습니다.
690/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
107590의 재무정보를 가져왔습니다.
691/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058730의 재무정보를 가져왔습니다.
692/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053690의 재무정보를 가져왔습니다.
693/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
278620의 재무정보를 가져왔습니다.
694/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
695/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001570의 재무정보를 가져왔습니다.
696/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000500의 재무정보를 가져왔습니다.

697/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093240의 재무정보를 가져왔습니다.
698/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090080의 재무정보를 가져왔습니다.
699/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
130730의 재무정보를 가져왔습니다.
700/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012320의 재무정보를 가져왔습니다.
701/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012800의 재무정보를 가져왔습니다.
702/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
163560의 재무정보를 가져왔습니다.
703/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001750는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
704/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011150의 재무정보를 가져왔습니다.
705/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014160의 재무정보를 가져왔습니다.
706/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058860의 재무정보를 가져왔습니다.
707/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
708/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023800의 재무정보를 가져왔습니다.
709/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
129260의 재무정보를 가져왔습니다.
710/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105840의 재무정보를 가져왔습니다.
711/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
120030의 재무정보를 가져왔습니다.
712/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005750의 재무정보를 가져왔습니다.
713/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010770의 재무정보를 가져왔습니다.
714/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015230의 재무정보를 가져왔습니다.
715/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005190의 재무정보를 가져왔습니다.
716/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068290의 재무정보를 가져왔습니다.
717/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006660의 재무정보를 가져왔습니다.
718/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007540의 재무정보를 가져왔습니다.
719/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083420의 재무정보를 가져왔습니다.
720/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006980의 재무정보를 가져왔습니다.
721/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
270800의 재무정보를 가져왔습니다.
722/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014440의 재무정보를 가져왔습니다.
723/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
130680의 재무정보를 가져왔습니다.
724/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009770의 재무정보를 가져왔습니다.
725/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027740의 재무정보를 가져왔습니다.
726/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
133820의 재무정보를 가져왔습니다.
727/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
728/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011500의 재무정보를 가져왔습니다.
729/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012170의 재무정보를 가져왔습니다.
730/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024890의 재무정보를 가져왔습니다.
731/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530025의 재무정보를 가져왔습니다.
732/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002200의 재무정보를 가져왔습니다.
733/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005110의 재무정보를 가져왔습니다.
734/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000590의 재무정보를 가져왔습니다.
735/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013360의 재무정보를 가져왔습니다.
736/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005010의 재무정보를 가져왔습니다.
737/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008250의 재무정보를 가져왔습니다.
738/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
145210의 재무정보를 가져왔습니다.
739/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
155660의 재무정보를 가져왔습니다.
740/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002920의 재무정보를 가져왔습니다.
741/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069730의 재무정보를 가져왔습니다.
742/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138230의 재무정보를 가져왔습니다.
743/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002820의 재무정보를 가져왔습니다.
744/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008260의 재무정보를 가져왔습니다.
745/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
746/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002140의 재무정보를 가져왔습니다.
747/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
118000의 재무정보를 가져왔습니다.
748/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
580007의 재무정보를 가져왔습니다.
749/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023450의 재무정보를 가져왔습니다.
750/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003610의 재무정보를 가져왔습니다.
751/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017550의 재무정보를 가져왔습니다.
752/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
277540의 재무정보를 가져왔습니다.
753/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004410의 재무정보를 가져왔습니다.
754/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009070의 재무정보를 가져왔습니다.
755/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
756/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011330의 재무정보를 가져왔습니다.
757/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018470의 재무정보를 가져왔습니다.
758/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012280의 재무정보를 가져왔습니다.
759/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014580의 재무정보를 가져왔습니다.
760/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114100의 재무정보를 가져왔습니다.
761/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001020의 재무정보를 가져왔습니다.
762/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006880의 재무정보를 가져왔습니다.
763/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008870의 재무정보를 가져왔습니다.
764/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500031의 재무정보를 가져왔습니다.
765/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006740의 재무정보를 가져왔습니다.
766/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006570의 재무정보를 가져왔습니다.
767/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252000의 재무정보를 가져왔습니다.
768/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025820의 재무정보를 가져왔습니다.
769/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122090의 재무정보를 가져왔습니다.
770/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069460의 재무정보를 가져왔습니다.
771/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014130의 재무정보를 가져왔습니다.
772/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000040의 재무정보를 가져왔습니다.
773/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001080의 재무정보를 가져왔습니다.
774/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079660의 재무정보를 가져왔습니다.
775/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
119650의 재무정보를 가져왔습니다.
776/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101140의 재무정보를 가져왔습니다.
777/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
778/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252420의 재무정보를 가져왔습니다.
779/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
281990의 재무정보를 가져왔습니다.
780/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530037의 재무정보를 가져왔습니다.
781/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001550의 재무정보를 가져왔습니다.
782/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023350의 재무정보를 가져왔습니다.
783/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
784/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
785/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010040의 재무정보를 가져왔습니다.
786/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049800의 재무정보를 가져왔습니다.
787/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
245360의 재무정보를 가져왔습니다.
788/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004270의 재무정보를 가져왔습니다.
789/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010100의 재무정보를 가져왔습니다.
790/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000300의 재무정보를 가져왔습니다.
791/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007120의 재무정보를 가져왔습니다.
792/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
088790의 재무정보를 가져왔습니다.
793/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123700의 재무정보를 가져왔습니다.
794/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000910의 재무정보를 가져왔습니다.
795/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272570의 재무정보를 가져왔습니다.
796/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500015의 재무정보를 가져왔습니다.
797/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025530의 재무정보를 가져왔습니다.
798/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013700의 재무정보를 가져왔습니다.
799/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018500의 재무정보를 가져왔습니다.
800/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015260의 재무정보를 가져왔습니다.
801/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
169950의 재무정보를 가져왔습니다.
802/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099140의 재무정보를 가져왔습니다.
803/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004090의 재무정보를 가져왔습니다.
804/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272910의 재무정보를 가져왔습니다.
805/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001070의 재무정보를 가져왔습니다.
806/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
807/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
266160의 재무정보를 가져왔습니다.
808/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092780의 재무정보를 가져왔습니다.
809/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
580006의 재무정보를 가져왔습니다.
810/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500001의 재무정보를 가져왔습니다.
811/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
020120의 재무정보를 가져왔습니다.
812/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292750의 재무정보를 가져왔습니다.
813/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023960의 재무정보를 가져왔습니다.
814/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009460의 재무정보를 가져왔습니다.
815/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005360의 재무정보를 가져왔습니다.
816/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550001의 재무정보를 가져왔습니다.
817/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084670의 재무정보를 가져왔습니다.
818/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005320의 재무정보를 가져왔습니다.
819/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004100의 재무정보를 가져왔습니다.
820/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001620의 재무정보를 가져왔습니다.
821/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008420의 재무정보를 가져왔습니다.
822/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
823/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004830의 재무정보를 가져왔습니다.
824/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001560의 재무정보를 가져왔습니다.
825/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007280의 재무정보를 가져왔습니다.
826/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096300는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
827/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
227830의 재무정보를 가져왔습니다.
828/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
266410의 재무정보를 가져왔습니다.
829/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
580004의 재무정보를 가져왔습니다.
830/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
132030의 재무정보를 가져왔습니다.
831/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010600의 재무정보를 가져왔습니다.
832/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006890의 재무정보를 가져왔습니다.
833/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
026940의 재무정보를 가져왔습니다.
834/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
835/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204450의 재무정보를 가져왔습니다.
836/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000760의 재무정보를 가져왔습니다.
837/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011230의 재무정보를 가져왔습니다.
838/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
021050의 재무정보를 가져왔습니다.
839/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
243880의 재무정보를 가져왔습니다.
840/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004140의 재무정보를 가져왔습니다.
841/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114260의 재무정보를 가져왔습니다.
842/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011420의 재무정보를 가져왔습니다.
843/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024070의 재무정보를 가져왔습니다.
844/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031820의 재무정보를 가져왔습니다.
845/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044380의 재무정보를 가져왔습니다.
846/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005820의 재무정보를 가져왔습니다.
847/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002220의 재무정보를 가져왔습니다.
848/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
136340의 재무정보를 가져왔습니다.
849/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550002의 재무정보를 가져왔습니다.
850/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003010의 재무정보를 가져왔습니다.
851/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
852/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093230의 재무정보를 가져왔습니다.
853/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071090의 재무정보를 가져왔습니다.
854/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001210의 재무정보를 가져왔습니다.
855/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
283580의 재무정보를 가져왔습니다.
856/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
190160의 재무정보를 가져왔습니다.
857/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002070의 재무정보를 가져왔습니다.
858/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
859/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023150의 재무정보를 가져왔습니다.
860/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072130의 재무정보를 가져왔습니다.
861/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
862/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024900의 재무정보를 가져왔습니다.

863/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
279530의 재무정보를 가져왔습니다.
864/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217780의 재무정보를 가져왔습니다.
865/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023810의 재무정보를 가져왔습니다.
866/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071950의 재무정보를 가져왔습니다.
867/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
137610의 재무정보를 가져왔습니다.
868/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014910의 재무정보를 가져왔습니다.
869/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002410의 재무정보를 가져왔습니다.
870/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252720의 재무정보를 가져왔습니다.
871/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
872/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
239660의 재무정보를 가져왔습니다.
873/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002690의 재무정보를 가져왔습니다.
874/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011300의 재무정보를 가져왔습니다.
875/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009190의 재무정보를 가져왔습니다.
876/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
580003의 재무정보를 가져왔습니다.
877/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214330의 재무정보를 가져왔습니다.
878/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010660의 재무정보를 가져왔습니다.
879/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027970의 재무정보를 가져왔습니다.
880/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013000의 재무정보를 가져왔습니다.
881/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008110의 재무정보를 가져왔습니다.
882/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
174360의 재무정보를 가져왔습니다.
883/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002710의 재무정보를 가져왔습니다.
884/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550014의 재무정보를 가져왔습니다.
885/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011390의 재무정보를 가져왔습니다.
886/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123310의 재무정보를 가져왔습니다.
887/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
155900의 재무정보를 가져왔습니다.
888/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009140의 재무정보를 가져왔습니다.
889/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292500의 재무정보를 가져왔습니다.
890/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
182480의 재무정보를 가져왔습니다.
891/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010580의 재무정보를 가져왔습니다.
892/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
145270의 재무정보를 가져왔습니다.
893/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
894/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019180의 재무정보를 가져왔습니다.
895/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114470의 재무정보를 가져왔습니다.
896/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006200의 재무정보를 가져왔습니다.
897/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
108450의 재무정보를 가져왔습니다.
898/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114820의 재무정보를 가져왔습니다.
899/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
211900의 재무정보를 가져왔습니다.
900/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500020의 재무정보를 가져왔습니다.
901/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015540의 재무정보를 가져왔습니다.
902/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009180의 재무정보를 가져왔습니다.
903/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009810의 재무정보를 가져왔습니다.
904/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226810의 재무정보를 가져왔습니다.
905/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520004의 재무정보를 가져왔습니다.
906/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030720의 재무정보를 가져왔습니다.
907/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003680의 재무정보를 가져왔습니다.
908/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
213610의 재무정보를 가져왔습니다.
909/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550042의 재무정보를 가져왔습니다.
910/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003780의 재무정보를 가져왔습니다.
911/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550020의 재무정보를 가져왔습니다.
912/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252400의 재무정보를 가져왔습니다.
913/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006110의 재무정보를 가져왔습니다.
914/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091230의 재무정보를 가져왔습니다.
915/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
195980의 재무정보를 가져왔습니다.
916/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002870의 재무정보를 가져왔습니다.

917/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530023의 재무정보를 가져왔습니다.
918/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003720의 재무정보를 가져왔습니다.
919/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550009의 재무정보를 가져왔습니다.
920/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500002의 재무정보를 가져왔습니다.
921/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
922/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004920의 재무정보를 가져왔습니다.
923/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252730의 재무정보를 가져왔습니다.
924/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261140의 재무정보를 가져왔습니다.
925/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139250의 재무정보를 가져왔습니다.
926/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
211560의 재무정보를 가져왔습니다.
927/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
285690의 재무정보를 가져왔습니다.
928/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002420의 재무정보를 가져왔습니다.
929/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000950의 재무정보를 가져왔습니다.
930/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
195930의 재무정보를 가져왔습니다.
931/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005450의 재무정보를 가져왔습니다.
932/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
182490의 재무정보를 가져왔습니다.
933/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
195920의 재무정보를 가져왔습니다.
934/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033250의 재무정보를 가져왔습니다.
935/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
172580의 재무정보를 가져왔습니다.
936/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015020의 재무정보를 가져왔습니다.
937/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
938/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
939/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
174350의 재무정보를 가져왔습니다.
940/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590010의 재무정보를 가져왔습니다.
941/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520006의 재무정보를 가져왔습니다.
942/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530005의 재무정보를 가져왔습니다.
943/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530012의 재무정보를 가져왔습니다.
944/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
170350의 재무정보를 가져왔습니다.
945/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263190의 재무정보를 가져왔습니다.
946/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590009의 재무정보를 가져왔습니다.
947/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
948/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122260의 재무정보를 가져왔습니다.
949/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520009의 재무정보를 가져왔습니다.
950/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099340는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
951/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140890의 재무정보를 가져왔습니다.
952/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
219480의 재무정보를 가져왔습니다.
953/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001420의 재무정보를 가져왔습니다.
954/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520013의 재무정보를 가져왔습니다.
955/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520014의 재무정보를 가져왔습니다.
956/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261060의 재무정보를 가져왔습니다.
957/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
230480의 재무정보를 가져왔습니다.
958/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550005의 재무정보를 가져왔습니다.
959/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005030의 재무정보를 가져왔습니다.
960/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520003의 재무정보를 가져왔습니다.
961/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530035의 재무정보를 가져왔습니다.
962/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570007의 재무정보를 가져왔습니다.
963/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123320의 재무정보를 가져왔습니다.
964/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500018의 재무정보를 가져왔습니다.
965/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530039의 재무정보를 가져왔습니다.
966/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204210의 재무정보를 가져왔습니다.
967/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
250780의 재무정보를 가져왔습니다.
968/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500009의 재무정보를 가져왔습니다.
969/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025890의 재무정보를 가져왔습니다.
970/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510007의 재무정보를 가져왔습니다.
971/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010420의 재무정보를 가져왔습니다.

972/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500022의 재무정보를 가져왔습니다.
973/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
275290의 재무정보를 가져왔습니다.
974/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520010의 재무정보를 가져왔습니다.
975/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051630의 재무정보를 가져왔습니다.
976/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520002의 재무정보를 가져왔습니다.
977/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590005의 재무정보를 가져왔습니다.
978/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530014의 재무정보를 가져왔습니다.
979/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550013의 재무정보를 가져왔습니다.
980/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001770의 재무정보를 가져왔습니다.
981/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253250의 재무정보를 가져왔습니다.
982/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590006의 재무정보를 가져왔습니다.
983/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
984/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
144600의 재무정보를 가져왔습니다.
985/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590007의 재무정보를 가져왔습니다.
986/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550008의 재무정보를 가져왔습니다.
987/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500027의 재무정보를 가져왔습니다.
988/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
157520의 재무정보를 가져왔습니다.
989/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530015의 재무정보를 가져왔습니다.
990/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590008의 재무정보를 가져왔습니다.
991/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
074600의 재무정보를 가져왔습니다.
992/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550026의 재무정보를 가져왔습니다.
993/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550019의 재무정보를 가져왔습니다.
994/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019490의 재무정보를 가져왔습니다.
995/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
243890의 재무정보를 가져왔습니다.
996/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550029의 재무정보를 가져왔습니다.
997/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
108590의 재무정보를 가져왔습니다.
998/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530017의 재무정보를 가져왔습니다.
999/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530016의 재무정보를 가져왔습니다.
1000/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570005의 재무정보를 가져왔습니다.
1001/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1002/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
580005의 재무정보를 가져왔습니다.
1003/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530018의 재무정보를 가져왔습니다.
1004/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
152280의 재무정보를 가져왔습니다.
1005/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292730의 재무정보를 가져왔습니다.
1006/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1007/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
251590의 재무정보를 가져왔습니다.
1008/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
256440의 재무정보를 가져왔습니다.
1009/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570015의 재무정보를 가져왔습니다.
1010/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530019의 재무정보를 가져왔습니다.
1011/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
229720의 재무정보를 가져왔습니다.
1012/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012600의 재무정보를 가져왔습니다.
1013/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008500의 재무정보를 가져왔습니다.
1014/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
266550의 재무정보를 가져왔습니다.
1015/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
153360의 재무정보를 가져왔습니다.
1016/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530032의 재무정보를 가져왔습니다.
1017/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590018의 재무정보를 가져왔습니다.
1018/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570008의 재무정보를 가져왔습니다.
1019/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570003의 재무정보를 가져왔습니다.
1020/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590002의 재무정보를 가져왔습니다.
1021/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500021의 재무정보를 가져왔습니다.
1022/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
289040의 재무정보를 가져왔습니다.
1023/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530021의 재무정보를 가져왔습니다.
1024/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530033의 재무정보를 가져왔습니다.
1025/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530020의 재무정보를 가져왔습니다.
1026/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530036의 재무정보를 가져왔습니다.
1027/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590004의 재무정보를 가져왔습니다.
1028/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550011의 재무정보를 가져왔습니다.
1029/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590003의 재무정보를 가져왔습니다.
1030/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
244620의 재무정보를 가져왔습니다.
1031/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500014의 재무정보를 가져왔습니다.
1032/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530022의 재무정보를 가져왔습니다.
1033/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500030의 재무정보를 가져왔습니다.
1034/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590017의 재무정보를 가져왔습니다.
1035/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550023의 재무정보를 가져왔습니다.
1036/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550004의 재무정보를 가져왔습니다.
1037/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550030의 재무정보를 가져왔습니다.
1038/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
276970의 재무정보를 가져왔습니다.
1039/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520012의 재무정보를 가져왔습니다.
1040/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
168300의 재무정보를 가져왔습니다.
1041/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500016의 재무정보를 가져왔습니다.
1042/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570012의 재무정보를 가져왔습니다.
1043/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114460의 재무정보를 가져왔습니다.
1044/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550024의 재무정보를 가져왔습니다.
1045/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570009의 재무정보를 가져왔습니다.
1046/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
278420의 재무정보를 가져왔습니다.
1047/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
137930의 재무정보를 가져왔습니다.
1048/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225130의 재무정보를 가져왔습니다.
1049/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590016의 재무정보를 가져왔습니다.
1050/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510009의 재무정보를 가져왔습니다.
1051/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500032의 재무정보를 가져왔습니다.
1052/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550021의 재무정보를 가져왔습니다.
1053/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
219900의 재무정보를 가져왔습니다.
1054/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091160의 재무정보를 가져왔습니다.
1055/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
276990의 재무정보를 가져왔습니다.
1056/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550044의 재무정보를 가져왔습니다.
1057/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
245340의 재무정보를 가져왔습니다.
1058/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
211210의 재무정보를 가져왔습니다.
1059/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
152180의 재무정보를 가져왔습니다.
1060/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570014의 재무정보를 가져왔습니다.
1061/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500012의 재무정보를 가져왔습니다.
1062/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140950의 재무정보를 가져왔습니다.
1063/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510005의 재무정보를 가져왔습니다.
1064/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520020의 재무정보를 가져왔습니다.
1065/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530038의 재무정보를 가져왔습니다.
1066/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292340의 재무정보를 가져왔습니다.
1067/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252650의 재무정보를 가져왔습니다.
1068/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500017의 재무정보를 가져왔습니다.
1069/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500023의 재무정보를 가져왔습니다.
1070/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550047의 재무정보를 가져왔습니다.
1071/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
237370의 재무정보를 가져왔습니다.
1072/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500024의 재무정보를 가져왔습니다.
1073/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530009의 재무정보를 가져왔습니다.
1074/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1075/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550015의 재무정보를 가져왔습니다.
1076/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590012의 재무정보를 가져왔습니다.
1077/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520021의 재무정보를 가져왔습니다.
1078/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
244660의 재무정보를 가져왔습니다.
1079/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570013의 재무정보를 가져왔습니다.
1080/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530008의 재무정보를 가져왔습니다.
1081/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
133690의 재무정보를 가져왔습니다.
1082/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
275540의 재무정보를 가져왔습니다.
1083/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
180400의 재무정보를 가져왔습니다.
1084/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
157490의 재무정보를 가져왔습니다.
1085/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1086/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217790의 재무정보를 가져왔습니다.
1087/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500011의 재무정보를 가져왔습니다.
1088/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
291610의 재무정보를 가져왔습니다.
1089/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550006의 재무정보를 가져왔습니다.
1090/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550003의 재무정보를 가져왔습니다.
1091/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
157500의 재무정보를 가져왔습니다.
1092/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550016의 재무정보를 가져왔습니다.
1093/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
266420의 재무정보를 가져왔습니다.
1094/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
148070의 재무정보를 가져왔습니다.
1095/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
117700의 재무정보를 가져왔습니다.
1096/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500003의 재무정보를 가져왔습니다.
1097/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530011의 재무정보를 가져왔습니다.
1098/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550007의 재무정보를 가져왔습니다.
1099/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
291630의 재무정보를 가져왔습니다.
1100/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261240의 재무정보를 가져왔습니다.
1101/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
237350의 재무정보를 가져왔습니다.
1102/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192720의 재무정보를 가져왔습니다.
1103/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590013의 재무정보를 가져왔습니다.
1104/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510008의 재무정보를 가져왔습니다.
1105/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550045의 재무정보를 가져왔습니다.
1106/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
159650의 재무정보를 가져왔습니다.
1107/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1108/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570010의 재무정보를 가져왔습니다.
1109/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550010의 재무정보를 가져왔습니다.
1110/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001140의 재무정보를 가져왔습니다.
1111/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500004의 재무정보를 가져왔습니다.
1112/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1113/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500007의 재무정보를 가져왔습니다.
1114/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
289480의 재무정보를 가져왔습니다.
1115/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550022의 재무정보를 가져왔습니다.
1116/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550033의 재무정보를 가져왔습니다.
1117/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570004의 재무정보를 가져왔습니다.
1118/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500006의 재무정보를 가져왔습니다.
1119/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550031의 재무정보를 가져왔습니다.
1120/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010640의 재무정보를 가져왔습니다.
1121/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
237440의 재무정보를 가져왔습니다.
1122/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
183700의 재무정보를 가져왔습니다.
1123/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500008의 재무정보를 가져왔습니다.
1124/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550025의 재무정보를 가져왔습니다.
1125/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500005의 재무정보를 가져왔습니다.
1126/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139220의 재무정보를 가져왔습니다.
1127/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140910의 재무정보를 가져왔습니다.
1128/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
117460의 재무정보를 가져왔습니다.
1129/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570006의 재무정보를 가져왔습니다.
1130/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1131/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1132/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1133/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215620의 재무정보를 가져왔습니다.
1134/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500029의 재무정보를 가져왔습니다.
1135/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1136/2713이 완료되었습니다.

총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
280920의 재무정보를 가져왔습니다.
1137/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261070의 재무정보를 가져왔습니다.
1138/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104520의 재무정보를 가져왔습니다.
1139/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091210의 재무정보를 가져왔습니다.
1140/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550027의 재무정보를 가져왔습니다.
1141/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261120의 재무정보를 가져왔습니다.
1142/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105780의 재무정보를 가져왔습니다.
1143/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530003의 재무정보를 가져왔습니다.
1144/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500013의 재무정보를 가져왔습니다.
1145/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1146/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500028의 재무정보를 가져왔습니다.
1147/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550032의 재무정보를 가져왔습니다.
1148/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570011의 재무정보를 가져왔습니다.
1149/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
269540의 재무정보를 가져왔습니다.
1150/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
590011의 재무정보를 가져왔습니다.
1151/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
147970의 재무정보를 가져왔습니다.
1152/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225060의 재무정보를 가져왔습니다.
1153/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225040의 재무정보를 가져왔습니다.
1154/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
251600의 재무정보를 가져왔습니다.
1155/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104530의 재무정보를 가져왔습니다.
1156/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
183710의 재무정보를 가져왔습니다.
1157/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550012의 재무정보를 가져왔습니다.
1158/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530007의 재무정보를 가져왔습니다.
1159/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
236350의 재무정보를 가져왔습니다.
1160/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
244670의 재무정보를 가져왔습니다.
1161/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
208470의 재무정보를 가져왔습니다.
1162/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530002의 재무정보를 가져왔습니다.
1163/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
227570의 재무정보를 가져왔습니다.
1164/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530004의 재무정보를 가져왔습니다.
1165/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500010의 재무정보를 가져왔습니다.
1166/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
266360의 재무정보를 가져왔습니다.
1167/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
190150의 재무정보를 가져왔습니다.
1168/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1169/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
143460의 재무정보를 가져왔습니다.
1170/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
152500의 재무정보를 가져왔습니다.
1171/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1172/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530006의 재무정보를 가져왔습니다.
1173/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
275300의 재무정보를 가져왔습니다.
1174/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
244580의 재무정보를 가져왔습니다.
1175/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
245350의 재무정보를 가져왔습니다.
1176/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241180의 재무정보를 가져왔습니다.
1177/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
251890의 재무정보를 가져왔습니다.
1178/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550018의 재무정보를 가져왔습니다.
1179/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510001의 재무정보를 가져왔습니다.
1180/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1181/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520015의 재무정보를 가져왔습니다.
1182/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253280의 재무정보를 가져왔습니다.
1183/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1184/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253990의 재무정보를 가져왔습니다.
1185/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
117680의 재무정보를 가져왔습니다.
1186/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520011의 재무정보를 가져왔습니다.
1187/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
260200의 재무정보를 가져왔습니다.
1188/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
260270의 재무정보를 가져왔습니다.
1189/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100910의 재무정보를 가져왔습니다.
1190/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200250의 재무정보를 가져왔습니다.
1191/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139660의 재무정보를 가져왔습니다.
1192/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140700의 재무정보를 가져왔습니다.
1193/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
266370의 재무정보를 가져왔습니다.
1194/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
227540의 재무정보를 가져왔습니다.
1195/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1196/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222180의 재무정보를 가져왔습니다.
1197/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261110의 재무정보를 가져왔습니다.
1198/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1199/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102960의 재무정보를 가져왔습니다.
1200/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1201/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
247790의 재무정보를 가져왔습니다.
1202/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520007의 재무정보를 가져왔습니다.
1203/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
266390의 재무정보를 가져왔습니다.
1204/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1205/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091180의 재무정보를 가져왔습니다.
1206/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292130의 재무정보를 가져왔습니다.
1207/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500025의 재무정보를 가져왔습니다.
1208/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
276000의 재무정보를 가져왔습니다.
1209/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253230의 재무정보를 가져왔습니다.
1210/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
210780의 재무정보를 가져왔습니다.
1211/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
228810의 재무정보를 가져왔습니다.
1212/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
250730의 재무정보를 가져왔습니다.
1213/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
153270의 재무정보를 가져왔습니다.
1214/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
228790의 재무정보를 가져왔습니다.
1215/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
283930의 재무정보를 가져왔습니다.
1216/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1217/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204420의 재무정보를 가져왔습니다.
1218/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
203780의 재무정보를 가져왔습니다.
1219/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570022의 재무정보를 가져왔습니다.
1220/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
248270의 재무정보를 가져왔습니다.
1221/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292100의 재무정보를 가져왔습니다.
1222/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570026의 재무정보를 가져왔습니다.
1223/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
289250의 재무정보를 가져왔습니다.
1224/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
234310의 재무정보를 가져왔습니다.
1225/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
265690의 재무정보를 가져왔습니다.
1226/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
291620의 재무정보를 가져왔습니다.
1227/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
279540의 재무정보를 가져왔습니다.
1228/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
247800의 재무정보를 가져왔습니다.
1229/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570020의 재무정보를 가져왔습니다.
1230/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
289260의 재무정보를 가져왔습니다.
1231/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1232/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267500의 재무정보를 가져왔습니다.
1233/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550046의 재무정보를 가져왔습니다.
1234/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570021의 재무정보를 가져왔습니다.
1235/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292120의 재무정보를 가져왔습니다.
1236/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
219390의 재무정보를 가져왔습니다.
1237/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292140의 재무정보를 가져왔습니다.
1238/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225030의 재무정보를 가져왔습니다.
1239/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140570의 재무정보를 가져왔습니다.
1240/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
248260의 재무정보를 가져왔습니다.
1241/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
275280의 재무정보를 가져왔습니다.
1242/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520005의 재무정보를 가져왔습니다.
1243/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570025의 재무정보를 가져왔습니다.
1244/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292110의 재무정보를 가져왔습니다.
1245/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
269420의 재무정보를 가져왔습니다.
1246/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
269370의 재무정보를 가져왔습니다.
1247/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
166400의 재무정보를 가져왔습니다.
1248/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
159800의 재무정보를 가져왔습니다.
1249/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139290의 재무정보를 가져왔습니다.
1250/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1251/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
284430의 재무정보를 가져왔습니다.
1252/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570027의 재무정보를 가져왔습니다.
1253/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267490의 재무정보를 가져왔습니다.
1254/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570024의 재무정보를 가져왔습니다.
1255/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550043의 재무정보를 가져왔습니다.
1256/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1257/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
292150의 재무정보를 가져왔습니다.
1258/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272220의 재무정보를 가져왔습니다.
1259/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
218420의 재무정보를 가져왔습니다.
1260/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
247780의 재무정보를 가져왔습니다.
1261/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510003의 재무정보를 가져왔습니다.
1262/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
570023의 재무정보를 가져왔습니다.
1263/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
280320의 재무정보를 가져왔습니다.
1264/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253290의 재무정보를 가져왔습니다.
1265/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200020의 재무정보를 가져왔습니다.
1266/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
205720의 재무정보를 가져왔습니다.
1267/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500026의 재무정보를 가져왔습니다.
1268/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200030의 재무정보를 가져왔습니다.
1269/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
287180의 재무정보를 가져왔습니다.
1270/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252410의 재무정보를 가져왔습니다.
1271/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253150의 재무정보를 가져왔습니다.
1272/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530041의 재무정보를 가져왔습니다.
1273/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
196030의 재무정보를 가져왔습니다.
1274/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272230의 재무정보를 가져왔습니다.
1275/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1276/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1277/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
291130의 재무정보를 가져왔습니다.
1278/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
160580의 재무정보를 가져왔습니다.
1279/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
291660의 재무정보를 가져왔습니다.
1280/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
238720의 재무정보를 가져왔습니다.
1281/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225050의 재무정보를 가져왔습니다.
1282/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
145670의 재무정보를 가져왔습니다.
1283/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530010의 재무정보를 가져왔습니다.
1284/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
117690의 재무정보를 가져왔습니다.
1285/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550041의 재무정보를 가져왔습니다.
1286/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
145850의 재무정보를 가져왔습니다.
1287/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
213630의 재무정보를 가져왔습니다.
1288/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
276650의 재무정보를 가져왔습니다.
1289/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510002의 재무정보를 가져왔습니다.
1290/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267300의 재무정보를 가져왔습니다.
1291/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530042의 재무정보를 가져왔습니다.
1292/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083380의 재무정보를 가져왔습니다.
1293/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083370의 재무정보를 가져왔습니다.
1294/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550050의 재무정보를 가져왔습니다.
1295/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138540의 재무정보를 가져왔습니다.
1296/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253240의 재무정보를 가져왔습니다.
1297/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
291890의 재무정보를 가져왔습니다.
1298/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550034의 재무정보를 가져왔습니다.
1299/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
287300의 재무정보를 가져왔습니다.
1300/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101280의 재무정보를 가져왔습니다.
1301/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
227560의 재무정보를 가져왔습니다.
1302/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530043의 재무정보를 가져왔습니다.
1303/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
141240의 재무정보를 가져왔습니다.
1304/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
285000의 재무정보를 가져왔습니다.
1305/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550040의 재무정보를 가져왔습니다.
1306/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261260의 재무정보를 가져왔습니다.
1307/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
228820의 재무정보를 가져왔습니다.
1308/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
271060의 재무정보를 가져왔습니다.
1309/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550038의 재무정보를 가져왔습니다.
1310/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
275750의 재무정보를 가져왔습니다.
1311/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520022의 재무정보를 가져왔습니다.
1312/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
228800의 재무정보를 가져왔습니다.
1313/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217770의 재무정보를 가져왔습니다.
1314/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
167860의 재무정보를 가져왔습니다.
1315/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
520023의 재무정보를 가져왔습니다.
1316/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
287320의 재무정보를 가져왔습니다.
1317/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
284990의 재무정보를 가져왔습니다.
1318/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530050의 재무정보를 가져왔습니다.
1319/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530044의 재무정보를 가져왔습니다.
1320/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
291680의 재무정보를 가져왔습니다.
1321/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
290130의 재무정보를 가져왔습니다.
1322/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131890의 재무정보를 가져왔습니다.
1323/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1324/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530046의 재무정보를 가져왔습니다.
1325/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
290080의 재무정보를 가져왔습니다.
1326/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261220의 재무정보를 가져왔습니다.
1327/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530048의 재무정보를 가져왔습니다.
1328/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530034의 재무정보를 가져왔습니다.
1329/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
211260의 재무정보를 가져왔습니다.
1330/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530051의 재무정보를 가져왔습니다.
1331/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530045의 재무정보를 가져왔습니다.
1332/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550039의 재무정보를 가져왔습니다.
1333/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550035의 재무정보를 가져왔습니다.
1334/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
266140의 재무정보를 가져왔습니다.
1335/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1336/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550037의 재무정보를 가져왔습니다.
1337/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550048의 재무정보를 가져왔습니다.
1338/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530047의 재무정보를 가져왔습니다.
1339/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
256750의 재무정보를 가져왔습니다.
1340/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510004의 재무정보를 가져왔습니다.
1341/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
500033의 재무정보를 가져왔습니다.
1342/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
189400의 재무정보를 가져왔습니다.
1343/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530049의 재무정보를 가져왔습니다.
1344/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550049의 재무정보를 가져왔습니다.
1345/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1346/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
196220의 재무정보를 가져왔습니다.
1347/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
181480의 재무정보를 가져왔습니다.
1348/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
530040의 재무정보를 가져왔습니다.
1349/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1350/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222170의 재무정보를 가져왔습니다.
1351/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
287310의 재무정보를 가져왔습니다.
1352/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
269530의 재무정보를 가져왔습니다.
1353/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
550036의 재무정보를 가져왔습니다.
1354/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241390의 재무정보를 가져왔습니다.
1355/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1356/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
232590의 재무정보를 가져왔습니다.
1357/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099350는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
1358/2713이 완료되었습니다.

총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
289670의 재무정보를 가져왔습니다.
1359/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
238670의 재무정보를 가져왔습니다.
1360/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226380의 재무정보를 가져왔습니다.
1361/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267450의 재무정보를 가져왔습니다.
1362/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
176710의 재무정보를 가져왔습니다.
1363/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1364/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1365/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
185680의 재무정보를 가져왔습니다.
1366/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140710의 재무정보를 가져왔습니다.
1367/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261920의 재무정보를 가져왔습니다.
1368/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267440의 재무정보를 가져왔습니다.
1369/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
195970의 재무정보를 가져왔습니다.
1370/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
236460의 재무정보를 가져왔습니다.
1371/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
244820의 재무정보를 가져왔습니다.
1372/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
285020의 재무정보를 가져왔습니다.
1373/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
287330의 재무정보를 가져왔습니다.
1374/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
152380의 재무정보를 가져왔습니다.
1375/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139230의 재무정보를 가져왔습니다.
1376/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1377/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140580의 재무정보를 가져왔습니다.
1378/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138910의 재무정보를 가져왔습니다.
1379/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200040의 재무정보를 가져왔습니다.
1380/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
097750의 재무정보를 가져왔습니다.
1381/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
285010의 재무정보를 가져왔습니다.
1382/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261270의 재무정보를 가져왔습니다.
1383/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091220의 재무정보를 가져왔습니다.
1384/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138530의 재무정보를 가져왔습니다.
1385/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139270의 재무정보를 가져왔습니다.
1386/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105010의 재무정보를 가져왔습니다.
1387/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222200의 재무정보를 가져왔습니다.
1388/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
510006의 재무정보를 가져왔습니다.
1389/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138520의 재무정보를 가져왔습니다.
1390/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
277640의 재무정보를 가져왔습니다.
1391/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200050의 재무정보를 가져왔습니다.
1392/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1393/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222190의 재무정보를 가져왔습니다.
1394/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
280930의 재무정보를 가져왔습니다.
1395/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
098560의 재무정보를 가져왔습니다.
1396/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1397/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
220130의 재무정보를 가져왔습니다.
1398/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
256450의 재무정보를 가져왔습니다.
1399/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
284980의 재무정보를 가져왔습니다.
1400/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1401/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1402/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
280940의 재무정보를 가져왔습니다.
1403/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139320의 재무정보를 가져왔습니다.
1404/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1405/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1406/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1407/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1408/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1409/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1410/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138920의 재무정보를 가져왔습니다.
1411/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1412/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1413/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1414/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1415/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1416/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139240의 재무정보를 가져왔습니다.
1417/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
227550의 재무정보를 가져왔습니다.
1418/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1419/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1420/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
271050의 재무정보를 가져왔습니다.
1421/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1422/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253160의 재무정보를 가져왔습니다.
1423/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1424/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1425/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139310의 재무정보를 가져왔습니다.
1426/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1427/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1428/2713이 완료되었습니다.
총 0개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 0개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 0개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
157510의 재무정보를 가져왔습니다.
1429/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1430/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1431/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1432/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1433/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1434/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1435/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1436/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1437/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1438/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1439/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1440/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1441/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
1442/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091990의 재무정보를 가져왔습니다.
1443/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215600의 재무정보를 가져왔습니다.
1444/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086900의 재무정보를 가져왔습니다.
1445/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084990의 재무정보를 가져왔습니다.
1446/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
130960의 재무정보를 가져왔습니다.
1447/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
028300의 재무정보를 가져왔습니다.
1448/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263750의 재무정보를 가져왔습니다.
1449/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068760의 재무정보를 가져왔습니다.
1450/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
950160의 재무정보를 가져왔습니다.
1451/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016170의 재무정보를 가져왔습니다.
1452/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
145020의 재무정보를 가져왔습니다.
1453/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253450의 재무정보를 가져왔습니다.
1454/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003670의 재무정보를 가져왔습니다.
1455/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095700의 재무정보를 가져왔습니다.
1456/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041960의 재무정보를 가져왔습니다.
1457/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078340의 재무정보를 가져왔습니다.
1458/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034230의 재무정보를 가져왔습니다.
1459/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007390의 재무정보를 가져왔습니다.
1460/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036490의 재무정보를 가져왔습니다.
1461/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
151910의 재무정보를 가져왔습니다.
1462/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
240810의 재무정보를 가져왔습니다.
1463/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065660의 재무정보를 가져왔습니다.
1464/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035760의 재무정보를 가져왔습니다.
1465/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
178920의 재무정보를 가져왔습니다.
1466/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
098460의 재무정보를 가져왔습니다.
1467/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042000의 재무정보를 가져왔습니다.
1468/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
085660의 재무정보를 가져왔습니다.
1469/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115450의 재무정보를 가져왔습니다.
1470/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
056190의 재무정보를 가져왔습니다.
1471/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
028150의 재무정보를 가져왔습니다.
1472/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200230의 재무정보를 가져왔습니다.
1473/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032680의 재무정보를 가져왔습니다.
1474/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046890의 재무정보를 가져왔습니다.
1475/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
022100의 재무정보를 가져왔습니다.
1476/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036830의 재무정보를 가져왔습니다.
1477/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192080의 재무정보를 가져왔습니다.
1478/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
108230의 재무정보를 가져왔습니다.
1479/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049950의 재무정보를 가져왔습니다.
1480/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038540의 재무정보를 가져왔습니다.
1481/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003380의 재무정보를 가져왔습니다.
1482/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078160의 재무정보를 가져왔습니다.
1483/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069080의 재무정보를 가져왔습니다.
1484/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102940의 재무정보를 가져왔습니다.
1485/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000250의 재무정보를 가져왔습니다.
1486/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214370의 재무정보를 가져왔습니다.
1487/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066970의 재무정보를 가져왔습니다.
1488/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096530의 재무정보를 가져왔습니다.
1489/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200130의 재무정보를 가져왔습니다.
1490/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039030의 재무정보를 가져왔습니다.
1491/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086520의 재무정보를 가져왔습니다.
1492/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036420의 재무정보를 가져왔습니다.
1493/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064760의 재무정보를 가져왔습니다.
1494/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
112040의 재무정보를 가져왔습니다.
1495/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041510의 재무정보를 가져왔습니다.
1496/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058470의 재무정보를 가져왔습니다.
1497/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
237690의 재무정보를 가져왔습니다.
1498/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083790의 재무정보를 가져왔습니다.
1499/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005290의 재무정보를 가져왔습니다.
1500/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
243070의 재무정보를 가져왔습니다.
1501/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039200의 재무정보를 가져왔습니다.
1502/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058820의 재무정보를 가져왔습니다.
1503/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084110의 재무정보를 가져왔습니다.
1504/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
183490의 재무정보를 가져왔습니다.
1505/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048260의 재무정보를 가져왔습니다.
1506/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090460의 재무정보를 가져왔습니다.
1507/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048530의 재무정보를 가져왔습니다.
1508/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035900의 재무정보를 가져왔습니다.
1509/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
144510의 재무정보를 가져왔습니다.
1510/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
141080의 재무정보를 가져왔습니다.
1511/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080160의 재무정보를 가져왔습니다.
1512/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031390의 재무정보를 가져왔습니다.
1513/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065620의 재무정보를 가져왔습니다.
1514/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053800의 재무정보를 가져왔습니다.
1515/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030190의 재무정보를 가져왔습니다.
1516/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
203690의 재무정보를 가져왔습니다.
1517/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035600의 재무정보를 가져왔습니다.
1518/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095610의 재무정보를 가져왔습니다.
1519/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
108320의 재무정보를 가져왔습니다.
1520/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067630의 재무정보를 가져왔습니다.
1521/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039840의 재무정보를 가져왔습니다.
1522/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041830의 재무정보를 가져왔습니다.
1523/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086450의 재무정보를 가져왔습니다.
1524/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089600의 재무정보를 가져왔습니다.
1525/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
082270의 재무정보를 가져왔습니다.
1526/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073070의 재무정보를 가져왔습니다.
1527/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
272290의 재무정보를 가져왔습니다.
1528/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
237880의 재무정보를 가져왔습니다.
1529/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025980의 재무정보를 가져왔습니다.
1530/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067080의 재무정보를 가져왔습니다.
1531/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267980의 재무정보를 가져왔습니다.
1532/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043150의 재무정보를 가져왔습니다.
1533/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
087010의 재무정보를 가져왔습니다.
1534/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
191420의 재무정보를 가져왔습니다.
1535/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030530의 재무정보를 가져왔습니다.
1536/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122870의 재무정보를 가져왔습니다.

1537/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
950170의 재무정보를 가져왔습니다.
1538/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140410의 재무정보를 가져왔습니다.
1539/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019210의 재무정보를 가져왔습니다.
1540/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214450의 재무정보를 가져왔습니다.
1541/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
182400의 재무정보를 가져왔습니다.
1542/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222040의 재무정보를 가져왔습니다.
1543/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036930의 재무정보를 가져왔습니다.
1544/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
063570의 재무정보를 가져왔습니다.
1545/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006730의 재무정보를 가져왔습니다.
1546/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053030의 재무정보를 가져왔습니다.
1547/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038290의 재무정보를 가져왔습니다.
1548/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051370의 재무정보를 가져왔습니다.
1549/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
085370의 재무정보를 가져왔습니다.
1550/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066700의 재무정보를 가져왔습니다.
1551/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025900의 재무정보를 가져왔습니다.
1552/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031980의 재무정보를 가져왔습니다.
1553/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067290의 재무정보를 가져왔습니다.
1554/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032190의 재무정보를 가져왔습니다.
1555/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033290의 재무정보를 가져왔습니다.
1556/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025770의 재무정보를 가져왔습니다.
1557/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023410의 재무정보를 가져왔습니다.
1558/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091700의 재무정보를 가져왔습니다.
1559/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084370의 재무정보를 가져왔습니다.
1560/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
206640의 재무정보를 가져왔습니다.
1561/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
196170의 재무정보를 가져왔습니다.
1562/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052020의 재무정보를 가져왔습니다.
1563/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092730의 재무정보를 가져왔습니다.
1564/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003800의 재무정보를 가져왔습니다.
1565/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078020는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
1566/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
218410의 재무정보를 가져왔습니다.
1567/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
063080의 재무정보를 가져왔습니다.
1568/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051500의 재무정보를 가져왔습니다.
1569/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013120의 재무정보를 가져왔습니다.
1570/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
174900의 재무정보를 가져왔습니다.
1571/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
213420의 재무정보를 가져왔습니다.
1572/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023890의 재무정보를 가져왔습니다.
1573/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068240의 재무정보를 가져왔습니다.
1574/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214150의 재무정보를 가져왔습니다.
1575/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049960의 재무정보를 가져왔습니다.
1576/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225570의 재무정보를 가져왔습니다.
1577/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217480의 재무정보를 가져왔습니다.
1578/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115960의 재무정보를 가져왔습니다.
1579/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
119610의 재무정보를 가져왔습니다.
1580/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035810의 재무정보를 가져왔습니다.
1581/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200670의 재무정보를 가져왔습니다.
1582/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010170의 재무정보를 가져왔습니다.
1583/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095660의 재무정보를 가져왔습니다.
1584/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015750의 재무정보를 가져왔습니다.
1585/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016250의 재무정보를 가져왔습니다.
1586/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016100의 재무정보를 가져왔습니다.
1587/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099190의 재무정보를 가져왔습니다.
1588/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
166090의 재무정보를 가져왔습니다.
1589/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052710의 재무정보를 가져왔습니다.
1590/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092040의 재무정보를 가져왔습니다.
1591/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123420의 재무정보를 가져왔습니다.
1592/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104830의 재무정보를 가져왔습니다.
1593/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060570의 재무정보를 가져왔습니다.
1594/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241770의 재무정보를 가져왔습니다.
1595/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100120의 재무정보를 가져왔습니다.
1596/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038500의 재무정보를 가져왔습니다.
1597/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006620의 재무정보를 가져왔습니다.
1598/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064240의 재무정보를 가져왔습니다.
1599/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080420의 재무정보를 가져왔습니다.
1600/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041140의 재무정보를 가져왔습니다.
1601/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086890의 재무정보를 가져왔습니다.
1602/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
142760의 재무정보를 가져왔습니다.
1603/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
260930의 재무정보를 가져왔습니다.
1604/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030520의 재무정보를 가져왔습니다.
1605/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044490의 재무정보를 가져왔습니다.
1606/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036630의 재무정보를 가져왔습니다.
1607/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
265520의 재무정보를 가져왔습니다.
1608/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086980의 재무정보를 가져왔습니다.
1609/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089030의 재무정보를 가져왔습니다.
1610/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041190는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
1611/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
232140의 재무정보를 가져왔습니다.
1612/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
185490의 재무정보를 가져왔습니다.
1613/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007720의 재무정보를 가져왔습니다.
1614/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
168330의 재무정보를 가져왔습니다.
1615/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067160의 재무정보를 가져왔습니다.
1616/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060250의 재무정보를 가져왔습니다.
1617/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241710의 재무정보를 가져왔습니다.
1618/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052260의 재무정보를 가져왔습니다.
1619/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032500의 재무정보를 가져왔습니다.
1620/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011040의 재무정보를 가져왔습니다.
1621/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024660의 재무정보를 가져왔습니다.
1622/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036540의 재무정보를 가져왔습니다.
1623/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013030의 재무정보를 가져왔습니다.
1624/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122990의 재무정보를 가져왔습니다.
1625/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014620의 재무정보를 가져왔습니다.
1626/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060280의 재무정보를 가져왔습니다.
1627/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023160의 재무정보를 가져왔습니다.
1628/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
255440의 재무정보를 가져왔습니다.
1629/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
203650의 재무정보를 가져왔습니다.
1630/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086390의 재무정보를 가져왔습니다.
1631/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263700의 재무정보를 가져왔습니다.
1632/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215360의 재무정보를 가져왔습니다.
1633/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046210의 재무정보를 가져왔습니다.
1634/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095270의 재무정보를 가져왔습니다.
1635/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
121800의 재무정보를 가져왔습니다.
1636/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
166480의 재무정보를 가져왔습니다.
1637/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
112240의 재무정보를 가져왔습니다.
1638/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054950의 재무정보를 가져왔습니다.
1639/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192440의 재무정보를 가져왔습니다.
1640/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044340의 재무정보를 가져왔습니다.
1641/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
228850의 재무정보를 가져왔습니다.
1642/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
057500의 재무정보를 가져왔습니다.
1643/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042520의 재무정보를 가져왔습니다.
1644/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
097780의 재무정보를 가져왔습니다.
1645/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
208640의 재무정보를 가져왔습니다.
1646/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
040350의 재무정보를 가져왔습니다.
1647/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
136480의 재무정보를 가져왔습니다.
1648/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036200의 재무정보를 가져왔습니다.
1649/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086040의 재무정보를 가져왔습니다.
1650/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039440의 재무정보를 가져왔습니다.
1651/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215200의 재무정보를 가져왔습니다.
1652/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
187420의 재무정보를 가져왔습니다.
1653/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140860의 재무정보를 가져왔습니다.
1654/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027050의 재무정보를 가져왔습니다.
1655/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065060의 재무정보를 가져왔습니다.
1656/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
183300의 재무정보를 가져왔습니다.
1657/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049180의 재무정보를 가져왔습니다.
1658/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214180의 재무정보를 가져왔습니다.
1659/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215000의 재무정보를 가져왔습니다.
1660/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
082920의 재무정보를 가져왔습니다.
1661/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048550의 재무정보를 가져왔습니다.
1662/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067390의 재무정보를 가져왔습니다.
1663/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
108790의 재무정보를 가져왔습니다.
1664/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091120의 재무정보를 가져왔습니다.
1665/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007820의 재무정보를 가져왔습니다.
1666/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217270의 재무정보를 가져왔습니다.
1667/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032790의 재무정보를 가져왔습니다.
1668/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064550의 재무정보를 가져왔습니다.
1669/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217730의 재무정보를 가져왔습니다.
1670/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046440의 재무정보를 가져왔습니다.
1671/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023910의 재무정보를 가져왔습니다.
1672/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102710의 재무정보를 가져왔습니다.
1673/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025320의 재무정보를 가져왔습니다.
1674/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
201490의 재무정보를 가져왔습니다.
1675/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083640의 재무정보를 가져왔습니다.
1676/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100130의 재무정보를 가져왔습니다.
1677/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060590의 재무정보를 가져왔습니다.
1678/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043610의 재무정보를 가져왔습니다.
1679/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018000의 재무정보를 가져왔습니다.
1680/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045100의 재무정보를 가져왔습니다.
1681/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060150의 재무정보를 가져왔습니다.
1682/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034950의 재무정보를 가져왔습니다.
1683/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
029960의 재무정보를 가져왔습니다.
1684/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114570의 재무정보를 가져왔습니다.
1685/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
126700의 재무정보를 가져왔습니다.
1686/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069110의 재무정보를 가져왔습니다.
1687/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078600의 재무정보를 가져왔습니다.
1688/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008290의 재무정보를 가져왔습니다.
1689/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
194510의 재무정보를 가져왔습니다.
1690/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214270의 재무정보를 가져왔습니다.
1691/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
137940의 재무정보를 가져왔습니다.
1692/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
144960의 재무정보를 가져왔습니다.
1693/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078150의 재무정보를 가져왔습니다.

1694/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
160550의 재무정보를 가져왔습니다.
1695/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
121440의 재무정보를 가져왔습니다.
1696/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123100의 재무정보를 가져왔습니다.
1697/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065160의 재무정보를 가져왔습니다.
1698/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
117670의 재무정보를 가져왔습니다.
1699/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
251370의 재무정보를 가져왔습니다.
1700/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
074430의 재무정보를 가져왔습니다.
1701/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
178320의 재무정보를 가져왔습니다.
1702/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064260의 재무정보를 가져왔습니다.
1703/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200780의 재무정보를 가져왔습니다.
1704/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058610의 재무정보를 가져왔습니다.
1705/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083660의 재무정보를 가져왔습니다.
1706/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900100의 재무정보를 가져왔습니다.
1707/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095340의 재무정보를 가져왔습니다.
1708/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018120의 재무정보를 가져왔습니다.
1709/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
251630의 재무정보를 가져왔습니다.
1710/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
224060의 재무정보를 가져왔습니다.
1711/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001540의 재무정보를 가져왔습니다.
1712/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052330의 재무정보를 가져왔습니다.
1713/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
205500의 재무정보를 가져왔습니다.
1714/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054670의 재무정보를 가져왔습니다.
1715/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
243840의 재무정보를 가져왔습니다.
1716/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089980의 재무정보를 가져왔습니다.
1717/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036190의 재무정보를 가져왔습니다.
1718/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
216050의 재무정보를 가져왔습니다.
1719/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
220630의 재무정보를 가져왔습니다.
1720/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042040의 재무정보를 가져왔습니다.
1721/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
143240의 재무정보를 가져왔습니다.
1722/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011370의 재무정보를 가져왔습니다.
1723/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036800의 재무정보를 가져왔습니다.
1724/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102210의 재무정보를 가져왔습니다.
1725/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131390의 재무정보를 가져왔습니다.
1726/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033100의 재무정보를 가져왔습니다.
1727/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036000의 재무정보를 가져왔습니다.
1728/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054050의 재무정보를 가져왔습니다.
1729/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071200의 재무정보를 가져왔습니다.
1730/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019550는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
1731/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115180의 재무정보를 가져왔습니다.
1732/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036890의 재무정보를 가져왔습니다.
1733/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054780의 재무정보를 가져왔습니다.
1734/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033160의 재무정보를 가져왔습니다.
1735/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100700의 재무정보를 가져왔습니다.
1736/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053980의 재무정보를 가져왔습니다.
1737/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
119860의 재무정보를 가져왔습니다.
1738/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
206560의 재무정보를 가져왔습니다.
1739/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017890의 재무정보를 가져왔습니다.
1740/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060720의 재무정보를 가져왔습니다.
1741/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090470의 재무정보를 가져왔습니다.
1742/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037460의 재무정보를 가져왔습니다.
1743/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036030의 재무정보를 가져왔습니다.
1744/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
121600의 재무정보를 가져왔습니다.
1745/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048410의 재무정보를 가져왔습니다.
1746/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043580의 재무정보를 가져왔습니다.
1747/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
206650의 재무정보를 가져왔습니다.
1748/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037950의 재무정보를 가져왔습니다.
1749/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032620의 재무정보를 가져왔습니다.
1750/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
260660의 재무정보를 가져왔습니다.
1751/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065650의 재무정보를 가져왔습니다.
1752/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215790의 재무정보를 가져왔습니다.
1753/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067170의 재무정보를 가져왔습니다.
1754/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065170의 재무정보를 가져왔습니다.
1755/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241690의 재무정보를 가져왔습니다.
1756/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031330의 재무정보를 가져왔습니다.
1757/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
021080는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
1758/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123860의 재무정보를 가져왔습니다.
1759/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018290의 재무정보를 가져왔습니다.
1760/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115160의 재무정보를 가져왔습니다.
1761/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005990의 재무정보를 가져왔습니다.
1762/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005160의 재무정보를 가져왔습니다.
1763/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035080의 재무정보를 가져왔습니다.
1764/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052790의 재무정보를 가져왔습니다.
1765/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222800의 재무정보를 가져왔습니다.
1766/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122640의 재무정보를 가져왔습니다.
1767/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
950110의 재무정보를 가져왔습니다.
1768/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053950의 재무정보를 가져왔습니다.
1769/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222110의 재무정보를 가져왔습니다.
1770/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046140의 재무정보를 가져왔습니다.
1771/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064800의 재무정보를 가져왔습니다.
1772/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900290의 재무정보를 가져왔습니다.
1773/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225530의 재무정보를 가져왔습니다.
1774/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043370의 재무정보를 가져왔습니다.
1775/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034940의 재무정보를 가져왔습니다.
1776/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138690의 재무정보를 가져왔습니다.
1777/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033500의 재무정보를 가져왔습니다.
1778/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
173940의 재무정보를 가져왔습니다.
1779/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045390의 재무정보를 가져왔습니다.
1780/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035890의 재무정보를 가져왔습니다.
1781/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002800의 재무정보를 가져왔습니다.
1782/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053610의 재무정보를 가져왔습니다.
1783/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114810의 재무정보를 가져왔습니다.
1784/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009300의 재무정보를 가져왔습니다.
1785/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114120의 재무정보를 가져왔습니다.
1786/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204840의 재무정보를 가져왔습니다.
1787/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131030의 재무정보를 가져왔습니다.
1788/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104480의 재무정보를 가져왔습니다.
1789/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067280의 재무정보를 가져왔습니다.
1790/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
234300의 재무정보를 가져왔습니다.
1791/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
141000의 재무정보를 가져왔습니다.
1792/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053350의 재무정보를 가져왔습니다.
1793/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032980의 재무정보를 가져왔습니다.
1794/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900310의 재무정보를 가져왔습니다.
1795/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083310의 재무정보를 가져왔습니다.
1796/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041590의 재무정보를 가져왔습니다.
1797/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041910의 재무정보를 가져왔습니다.
1798/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
227610의 재무정보를 가져왔습니다.

1799/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053300의 재무정보를 가져왔습니다.
1800/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033640의 재무정보를 가져왔습니다.
1801/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094850의 재무정보를 가져왔습니다.
1802/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140670의 재무정보를 가져왔습니다.
1803/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064090의 재무정보를 가져왔습니다.
1804/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060560의 재무정보를 가져왔습니다.
1805/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038060의 재무정보를 가져왔습니다.
1806/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
246720의 재무정보를 가져왔습니다.
1807/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
118990의 재무정보를 가져왔습니다.
1808/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067990의 재무정보를 가져왔습니다.
1809/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
127160의 재무정보를 가져왔습니다.
1810/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039560의 재무정보를 가져왔습니다.
1811/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
109960의 재무정보를 가져왔습니다.
1812/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
155650의 재무정보를 가져왔습니다.
1813/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217600의 재무정보를 가져왔습니다.
1814/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
239610의 재무정보를 가져왔습니다.
1815/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067000의 재무정보를 가져왔습니다.
1816/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225190의 재무정보를 가져왔습니다.
1817/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
040910의 재무정보를 가져왔습니다.
1818/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222810의 재무정보를 가져왔습니다.
1819/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053700의 재무정보를 가져왔습니다.
1820/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018310의 재무정보를 가져왔습니다.
1821/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049070의 재무정보를 가져왔습니다.
1822/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092130의 재무정보를 가져왔습니다.
1823/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014100의 재무정보를 가져왔습니다.
1824/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035610의 재무정보를 가져왔습니다.
1825/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044480의 재무정보를 가져왔습니다.
1826/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013990의 재무정보를 가져왔습니다.
1827/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090730의 재무정보를 가져왔습니다.
1828/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900300의 재무정보를 가져왔습니다.
1829/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086960의 재무정보를 가져왔습니다.
1830/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214430의 재무정보를 가져왔습니다.
1831/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054450의 재무정보를 가져왔습니다.
1832/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052400의 재무정보를 가져왔습니다.
1833/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
151860의 재무정보를 가져왔습니다.
1834/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
236200의 재무정보를 가져왔습니다.
1835/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131290의 재무정보를 가져왔습니다.
1836/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
056080의 재무정보를 가져왔습니다.
1837/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
149940의 재무정보를 가져왔습니다.
1838/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012700의 재무정보를 가져왔습니다.
1839/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
171120의 재무정보를 가져왔습니다.
1840/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900260의 재무정보를 가져왔습니다.
1841/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079370의 재무정보를 가져왔습니다.
1842/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096630의 재무정보를 가져왔습니다.
1843/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050890의 재무정보를 가져왔습니다.
1844/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030960의 재무정보를 가져왔습니다.
1845/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
021320의 재무정보를 가져왔습니다.
1846/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068790의 재무정보를 가져왔습니다.
1847/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122450의 재무정보를 가져왔습니다.
1848/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
097520의 재무정보를 가져왔습니다.
1849/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041460의 재무정보를 가져왔습니다.
1850/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204620의 재무정보를 가져왔습니다.
1851/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
077360의 재무정보를 가져왔습니다.
1852/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900270의 재무정보를 가져왔습니다.
1853/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073560의 재무정보를 가져왔습니다.
1854/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060300의 재무정보를 가져왔습니다.
1855/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090360의 재무정보를 가져왔습니다.
1856/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
194480의 재무정보를 가져왔습니다.
1857/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054800의 재무정보를 가져왔습니다.
1858/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140070의 재무정보를 가져왔습니다.
1859/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033320의 재무정보를 가져왔습니다.
1860/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225330의 재무정보를 가져왔습니다.
1861/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065510의 재무정보를 가져왔습니다.
1862/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
259630의 재무정보를 가져왔습니다.
1863/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
950130의 재무정보를 가져왔습니다.
1864/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014200의 재무정보를 가져왔습니다.
1865/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204990의 재무정보를 가져왔습니다.
1866/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
161580의 재무정보를 가져왔습니다.
1867/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004650의 재무정보를 가져왔습니다.
1868/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023900의 재무정보를 가져왔습니다.
1869/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079970의 재무정보를 가져왔습니다.
1870/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072870의 재무정보를 가져왔습니다.
1871/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071460의 재무정보를 가져왔습니다.
1872/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
136540의 재무정보를 가져왔습니다.
1873/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263770의 재무정보를 가져왔습니다.
1874/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241820의 재무정보를 가져왔습니다.
1875/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089140의 재무정보를 가져왔습니다.
1876/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095190의 재무정보를 가져왔습니다.
1877/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039860의 재무정보를 가져왔습니다.
1878/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
063170의 재무정보를 가져왔습니다.
1879/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047310의 재무정보를 가져왔습니다.
1880/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043090의 재무정보를 가져왔습니다.
1881/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066620의 재무정보를 가져왔습니다.
1882/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263720의 재무정보를 가져왔습니다.
1883/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
147830의 재무정보를 가져왔습니다.
1884/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051360의 재무정보를 가져왔습니다.
1885/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
195990의 재무정보를 가져왔습니다.
1886/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
026040의 재무정보를 가져왔습니다.
1887/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
109610의 재무정보를 가져왔습니다.
1888/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094480의 재무정보를 가져왔습니다.
1889/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192410의 재무정보를 가져왔습니다.
1890/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
021040의 재무정보를 가져왔습니다.
1891/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101730의 재무정보를 가져왔습니다.
1892/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080220의 재무정보를 가져왔습니다.
1893/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
034810의 재무정보를 가져왔습니다.
1894/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
230360의 재무정보를 가져왔습니다.
1895/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042370의 재무정보를 가져왔습니다.
1896/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
160980의 재무정보를 가져왔습니다.
1897/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
020710의 재무정보를 가져왔습니다.
1898/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038880의 재무정보를 가져왔습니다.
1899/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
108860의 재무정보를 가져왔습니다.
1900/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049080의 재무정보를 가져왔습니다.
1901/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
109740의 재무정보를 가져왔습니다.
1902/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005710의 재무정보를 가져왔습니다.
1903/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
219550의 재무정보를 가져왔습니다.
1904/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
059090의 재무정보를 가져왔습니다.
1905/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006910의 재무정보를 가져왔습니다.
1906/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041440의 재무정보를 가져왔습니다.
1907/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060240의 재무정보를 가져왔습니다.
1908/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036120의 재무정보를 가져왔습니다.
1909/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078890의 재무정보를 가져왔습니다.
1910/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048870의 재무정보를 가져왔습니다.
1911/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066980의 재무정보를 가져왔습니다.
1912/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091580의 재무정보를 가져왔습니다.
1913/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
082210의 재무정보를 가져왔습니다.
1914/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054620의 재무정보를 가져왔습니다.
1915/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072020의 재무정보를 가져왔습니다.
1916/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014470의 재무정보를 가져왔습니다.
1917/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092070의 재무정보를 가져왔습니다.
1918/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016600는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
1919/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131370의 재무정보를 가져왔습니다.
1920/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078140의 재무정보를 가져왔습니다.
1921/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025440의 재무정보를 가져왔습니다.
1922/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090710의 재무정보를 가져왔습니다.
1923/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
022220의 재무정보를 가져왔습니다.
1924/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138580의 재무정보를 가져왔습니다.
1925/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123840의 재무정보를 가져왔습니다.
1926/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091590의 재무정보를 가져왔습니다.
1927/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042420의 재무정보를 가져왔습니다.
1928/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039830의 재무정보를 가져왔습니다.
1929/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023600의 재무정보를 가져왔습니다.
1930/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009520의 재무정보를 가져왔습니다.
1931/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050110의 재무정보를 가져왔습니다.
1932/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
187220의 재무정보를 가져왔습니다.
1933/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
150840의 재무정보를 가져왔습니다.
1934/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
142280의 재무정보를 가져왔습니다.
1935/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
193250의 재무정보를 가져왔습니다.
1936/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053110의 재무정보를 가져왔습니다.
1937/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049520의 재무정보를 가져왔습니다.
1938/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042510의 재무정보를 가져왔습니다.
1939/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058400의 재무정보를 가져왔습니다.
1940/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009780의 재무정보를 가져왔습니다.
1941/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091970의 재무정보를 가져왔습니다.
1942/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038390의 재무정보를 가져왔습니다.
1943/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
220100의 재무정보를 가져왔습니다.
1944/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068330의 재무정보를 가져왔습니다.
1945/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014570의 재무정보를 가져왔습니다.
1946/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048910의 재무정보를 가져왔습니다.
1947/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
196300의 재무정보를 가져왔습니다.
1948/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
061250의 재무정보를 가져왔습니다.
1949/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222080의 재무정보를 가져왔습니다.
1950/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036560의 재무정보를 가져왔습니다.
1951/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001840의 재무정보를 가져왔습니다.
1952/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011560의 재무정보를 가져왔습니다.
1953/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072470의 재무정보를 가져왔습니다.
1954/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
205100의 재무정보를 가져왔습니다.
1955/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083930의 재무정보를 가져왔습니다.

1956/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
015710의 재무정보를 가져왔습니다.
1957/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
088800의 재무정보를 가져왔습니다.
1958/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
219420의 재무정보를 가져왔습니다.
1959/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
126870의 재무정보를 가져왔습니다.
1960/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035620의 재무정보를 가져왔습니다.
1961/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047770의 재무정보를 가져왔습니다.
1962/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
026180의 재무정보를 가져왔습니다.
1963/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024810의 재무정보를 가져왔습니다.
1964/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003100의 재무정보를 가져왔습니다.
1965/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099320의 재무정보를 가져왔습니다.
1966/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104200의 재무정보를 가져왔습니다.
1967/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
108380의 재무정보를 가져왔습니다.
1968/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131970의 재무정보를 가져왔습니다.
1969/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
252500의 재무정보를 가져왔습니다.
1970/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114450의 재무정보를 가져왔습니다.
1971/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900250의 재무정보를 가져왔습니다.
1972/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078070의 재무정보를 가져왔습니다.
1973/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
277070는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
1974/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007680의 재무정보를 가져왔습니다.
1975/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019660의 재무정보를 가져왔습니다.
1976/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036090의 재무정보를 가져왔습니다.
1977/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
221840의 재무정보를 가져왔습니다.
1978/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
204630의 재무정보를 가져왔습니다.
1979/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267790의 재무정보를 가져왔습니다.
1980/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
149950의 재무정보를 가져왔습니다.
1981/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012790의 재무정보를 가져왔습니다.
1982/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090850의 재무정보를 가져왔습니다.
1983/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083650의 재무정보를 가져왔습니다.
1984/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
179900의 재무정보를 가져왔습니다.
1985/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093920의 재무정보를 가져왔습니다.
1986/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033340의 재무정보를 가져왔습니다.
1987/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
211270의 재무정보를 가져왔습니다.
1988/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093190의 재무정보를 가져왔습니다.
1989/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037350의 재무정보를 가져왔습니다.
1990/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065680의 재무정보를 가져왔습니다.
1991/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
063760의 재무정보를 가져왔습니다.
1992/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
156100의 재무정보를 가져왔습니다.
1993/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
264450의 재무정보를 가져왔습니다.
1994/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
137400의 재무정보를 가져왔습니다.
1995/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
223310의 재무정보를 가져왔습니다.
1996/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084730의 재무정보를 가져왔습니다.
1997/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067310의 재무정보를 가져왔습니다.
1998/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049630의 재무정보를 가져왔습니다.
1999/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084650의 재무정보를 가져왔습니다.
2000/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
040420의 재무정보를 가져왔습니다.
2001/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039230의 재무정보를 가져왔습니다.
2002/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017510의 재무정보를 가져왔습니다.
2003/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035290의 재무정보를 가져왔습니다.
2004/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018680의 재무정보를 가져왔습니다.
2005/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007330는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2006/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002230의 재무정보를 가져왔습니다.
2007/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065530의 재무정보를 가져왔습니다.

2008/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192250의 재무정보를 가져왔습니다.
2009/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
088130의 재무정보를 가져왔습니다.
2010/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053450의 재무정보를 가져왔습니다.
2011/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038460의 재무정보를 가져왔습니다.
2012/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069510의 재무정보를 가져왔습니다.
2013/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054180의 재무정보를 가져왔습니다.
2014/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
950140의 재무정보를 가져왔습니다.
2015/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024950의 재무정보를 가져왔습니다.
2016/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
171090의 재무정보를 가져왔습니다.
2017/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027710의 재무정보를 가져왔습니다.
2018/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
120240의 재무정보를 가져왔습니다.
2019/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263600의 재무정보를 가져왔습니다.
2020/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036180의 재무정보를 가져왔습니다.
2021/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033170의 재무정보를 가져왔습니다.
2022/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
028040의 재무정보를 가져왔습니다.
2023/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
141020의 재무정보를 가져왔습니다.
2024/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036010의 재무정보를 가져왔습니다.
2025/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096240의 재무정보를 가져왔습니다.
2026/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047920의 재무정보를 가져왔습니다.
2027/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046070의 재무정보를 가져왔습니다.
2028/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
061970의 재무정보를 가져왔습니다.
2029/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
197210의 재무정보를 가져왔습니다.
2030/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065350의 재무정보를 가져왔습니다.
2031/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049480의 재무정보를 가져왔습니다.
2032/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
057540의 재무정보를 가져왔습니다.
2033/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096690의 재무정보를 가져왔습니다.
2034/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036810의 재무정보를 가져왔습니다.
2035/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071670의 재무정보를 가져왔습니다.
2036/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043650의 재무정보를 가져왔습니다.
2037/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123330의 재무정보를 가져왔습니다.
2038/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032850의 재무정보를 가져왔습니다.
2039/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079190의 재무정보를 가져왔습니다.
2040/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011320의 재무정보를 가져왔습니다.
2041/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131100의 재무정보를 가져왔습니다.
2042/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
040160의 재무정보를 가져왔습니다.
2043/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038870의 재무정보를 가져왔습니다.
2044/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033560의 재무정보를 가져왔습니다.
2045/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047820의 재무정보를 가져왔습니다.
2046/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065150의 재무정보를 가져왔습니다.
2047/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079940의 재무정보를 가져왔습니다.
2048/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
158310의 재무정보를 가져왔습니다.
2049/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139050의 재무정보를 가져왔습니다.
2050/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215380의 재무정보를 가져왔습니다.
2051/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214310의 재무정보를 가져왔습니다.
2052/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043710의 재무정보를 가져왔습니다.
2053/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
130580의 재무정보를 가져왔습니다.
2054/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099440의 재무정보를 가져왔습니다.
2055/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033540의 재무정보를 가져왔습니다.
2056/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027830는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2057/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138610의 재무정보를 가져왔습니다.
2058/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
056730의 재무정보를 가져왔습니다.
2059/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
238090의 재무정보를 가져왔습니다.
2060/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
087260의 재무정보를 가져왔습니다.
2061/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047080의 재무정보를 가져왔습니다.
2062/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
088910의 재무정보를 가져왔습니다.
2063/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
059120의 재무정보를 가져왔습니다.
2064/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092870의 재무정보를 가져왔습니다.
2065/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065560의 재무정보를 가져왔습니다.
2066/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023760는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2067/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
170920의 재무정보를 가져왔습니다.
2068/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045520의 재무정보를 가져왔습니다.
2069/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045660의 재무정보를 가져왔습니다.
2070/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
250000의 재무정보를 가져왔습니다.
2071/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038070의 재무정보를 가져왔습니다.
2072/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
102120의 재무정보를 가져왔습니다.
2073/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104540의 재무정보를 가져왔습니다.
2074/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066130의 재무정보를 가져왔습니다.
2075/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014190의 재무정보를 가져왔습니다.
2076/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
059210의 재무정보를 가져왔습니다.
2077/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043200의 재무정보를 가져왔습니다.
2078/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039010의 재무정보를 가져왔습니다.
2079/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900040의 재무정보를 가져왔습니다.
2080/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041920의 재무정보를 가져왔습니다.
2081/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
206400의 재무정보를 가져왔습니다.
2082/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060370의 재무정보를 가져왔습니다.
2083/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045970의 재무정보를 가져왔습니다.
2084/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052420의 재무정보를 가져왔습니다.
2085/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222420의 재무정보를 가져왔습니다.
2086/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
088390의 재무정보를 가져왔습니다.
2087/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039980의 재무정보를 가져왔습니다.
2088/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038160의 재무정보를 가져왔습니다.
2089/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039420의 재무정보를 가져왔습니다.
2090/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089230의 재무정보를 가져왔습니다.
2091/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050120의 재무정보를 가져왔습니다.
2092/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031510의 재무정보를 가져왔습니다.
2093/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
056090의 재무정보를 가져왔습니다.
2094/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241520는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2095/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046120의 재무정보를 가져왔습니다.
2096/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065940의 재무정보를 가져왔습니다.
2097/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
208350의 재무정보를 가져왔습니다.
2098/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
196490의 재무정보를 가져왔습니다.
2099/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
189300의 재무정보를 가져왔습니다.
2100/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073490의 재무정보를 가져왔습니다.
2101/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043340의 재무정보를 가져왔습니다.
2102/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
057880의 재무정보를 가져왔습니다.
2103/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
220260의 재무정보를 가져왔습니다.
2104/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013310의 재무정보를 가져왔습니다.
2105/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122350의 재무정보를 가져왔습니다.
2106/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080000의 재무정보를 가져왔습니다.
2107/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065130의 재무정보를 가져왔습니다.
2108/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036170의 재무정보를 가져왔습니다.
2109/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
057680의 재무정보를 가져왔습니다.
2110/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101330의 재무정보를 가져왔습니다.
2111/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
238490의 재무정보를 가져왔습니다.
2112/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048430의 재무정보를 가져왔습니다.
2113/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067900의 재무정보를 가져왔습니다.
2114/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066360의 재무정보를 가져왔습니다.
2115/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004780의 재무정보를 가져왔습니다.
2116/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101160의 재무정보를 가져왔습니다.
2117/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065950의 재무정보를 가져왔습니다.
2118/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080010의 재무정보를 가져왔습니다.
2119/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131090의 재무정보를 가져왔습니다.
2120/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
184230의 재무정보를 가져왔습니다.
2121/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095500의 재무정보를 가져왔습니다.
2122/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072520의 재무정보를 가져왔습니다.
2123/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080520의 재무정보를 가져왔습니다.
2124/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079650의 재무정보를 가져왔습니다.
2125/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
106190의 재무정보를 가져왔습니다.
2126/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214680의 재무정보를 가져왔습니다.
2127/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094820의 재무정보를 가져왔습니다.
2128/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068930의 재무정보를 가져왔습니다.
2129/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900080의 재무정보를 가져왔습니다.
2130/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
149980의 재무정보를 가져왔습니다.
2131/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
208370의 재무정보를 가져왔습니다.
2132/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
111820의 재무정보를 가져왔습니다.
2133/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079950의 재무정보를 가져왔습니다.
2134/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038680의 재무정보를 가져왔습니다.
2135/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
061040의 재무정보를 가져왔습니다.
2136/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060310의 재무정보를 가져왔습니다.
2137/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053620의 재무정보를 가져왔습니다.
2138/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083450의 재무정보를 가져왔습니다.
2139/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100090의 재무정보를 가져왔습니다.
2140/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
159910의 재무정보를 가져왔습니다.
2141/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101490의 재무정보를 가져왔습니다.
2142/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053280의 재무정보를 가져왔습니다.
2143/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078130의 재무정보를 가져왔습니다.
2144/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
095910의 재무정보를 가져왔습니다.
2145/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099660의 재무정보를 가져왔습니다.
2146/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033230의 재무정보를 가져왔습니다.
2147/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073570의 재무정보를 가져왔습니다.
2148/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069410의 재무정보를 가져왔습니다.
2149/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
085810의 재무정보를 가져왔습니다.
2150/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036480의 재무정보를 가져왔습니다.
2151/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092600의 재무정보를 가져왔습니다.
2152/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036670의 재무정보를 가져왔습니다.
2153/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033600의 재무정보를 가져왔습니다.
2154/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
228340의 재무정보를 가져왔습니다.
2155/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
246690는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2156/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024800의 재무정보를 가져왔습니다.
2157/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045510의 재무정보를 가져왔습니다.
2158/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060230의 재무정보를 가져왔습니다.
2159/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064520의 재무정보를 가져왔습니다.
2160/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
147760의 재무정보를 가져왔습니다.
2161/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225650의 재무정보를 가져왔습니다.
2162/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079960의 재무정보를 가져왔습니다.
2163/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
241790의 재무정보를 가져왔습니다.
2164/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138080의 재무정보를 가져왔습니다.
2165/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052860의 재무정보를 가져왔습니다.
2166/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
040300의 재무정보를 가져왔습니다.
2167/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
134780의 재무정보를 가져왔습니다.
2168/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
106240의 재무정보를 가져왔습니다.
2169/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
126600의 재무정보를 가져왔습니다.
2170/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058630의 재무정보를 가져왔습니다.
2171/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066110의 재무정보를 가져왔습니다.
2172/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030350의 재무정보를 가져왔습니다.
2173/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006920의 재무정보를 가져왔습니다.
2174/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036690의 재무정보를 가져왔습니다.
2175/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
127120의 재무정보를 가져왔습니다.
2176/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
196450의 재무정보를 가져왔습니다.
2177/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
234920의 재무정보를 가져왔습니다.
2178/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
208860의 재무정보를 가져왔습니다.
2179/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900280의 재무정보를 가져왔습니다.
2180/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
178780의 재무정보를 가져왔습니다.
2181/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027040의 재무정보를 가져왔습니다.
2182/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043220의 재무정보를 가져왔습니다.
2183/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053260의 재무정보를 가져왔습니다.
2184/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
081970의 재무정보를 가져왔습니다.
2185/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123040의 재무정보를 가져왔습니다.
2186/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066590의 재무정보를 가져왔습니다.
2187/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033130의 재무정보를 가져왔습니다.
2188/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
140520의 재무정보를 가져왔습니다.
2189/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096640의 재무정보를 가져왔습니다.
2190/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
111870의 재무정보를 가져왔습니다.
2191/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065710의 재무정보를 가져왔습니다.
2192/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043290의 재무정보를 가져왔습니다.
2193/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092460의 재무정보를 가져왔습니다.
2194/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007370의 재무정보를 가져왔습니다.
2195/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
126880의 재무정보를 가져왔습니다.
2196/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083550의 재무정보를 가져왔습니다.
2197/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
218150의 재무정보를 가져왔습니다.
2198/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093320의 재무정보를 가져왔습니다.
2199/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042940의 재무정보를 가져왔습니다.
2200/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067570의 재무정보를 가져왔습니다.
2201/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217820의 재무정보를 가져왔습니다.
2202/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200710의 재무정보를 가져왔습니다.
2203/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054340의 재무정보를 가져왔습니다.
2204/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006140의 재무정보를 가져왔습니다.
2205/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037070의 재무정보를 가져왔습니다.
2206/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
109820의 재무정보를 가져왔습니다.
2207/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060900의 재무정보를 가져왔습니다.
2208/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069920의 재무정보를 가져왔습니다.
2209/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094170의 재무정보를 가져왔습니다.
2210/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115310의 재무정보를 가져왔습니다.
2211/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066910의 재무정보를 가져왔습니다.
2212/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
056360의 재무정보를 가져왔습니다.
2213/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046110의 재무정보를 가져왔습니다.
2214/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025950의 재무정보를 가져왔습니다.
2215/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043100의 재무정보를 가져왔습니다.
2216/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039340의 재무정보를 가져왔습니다.

2217/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049470의 재무정보를 가져왔습니다.
2218/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046940의 재무정보를 가져왔습니다.
2219/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052290의 재무정보를 가져왔습니다.
2220/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138360의 재무정보를 가져왔습니다.
2221/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900120의 재무정보를 가져왔습니다.
2222/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058220의 재무정보를 가져왔습니다.
2223/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025550의 재무정보를 가져왔습니다.
2224/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
040610의 재무정보를 가져왔습니다.
2225/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051490의 재무정보를 가져왔습니다.
2226/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065450의 재무정보를 가져왔습니다.
2227/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017650의 재무정보를 가져왔습니다.
2228/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089850의 재무정보를 가져왔습니다.
2229/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032800의 재무정보를 가져왔습니다.
2230/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263810의 재무정보를 가져왔습니다.
2231/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094190의 재무정보를 가져왔습니다.
2232/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048470의 재무정보를 가져왔습니다.
2233/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
119850의 재무정보를 가져왔습니다.
2234/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086670의 재무정보를 가져왔습니다.
2235/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006580의 재무정보를 가져왔습니다.
2236/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046390의 재무정보를 가져왔습니다.
2237/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048770의 재무정보를 가져왔습니다.
2238/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017680의 재무정보를 가져왔습니다.
2239/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032960의 재무정보를 가져왔습니다.
2240/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
207760의 재무정보를 가져왔습니다.
2241/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024880의 재무정보를 가져왔습니다.
2242/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114630의 재무정보를 가져왔습니다.
2243/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
160600의 재무정보를 가져왔습니다.
2244/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
097870의 재무정보를 가져왔습니다.
2245/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054210의 재무정보를 가져왔습니다.
2246/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066670의 재무정보를 가져왔습니다.
2247/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014970의 재무정보를 가져왔습니다.
2248/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
143160의 재무정보를 가져왔습니다.
2249/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049430의 재무정보를 가져왔습니다.
2250/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037370의 재무정보를 가져왔습니다.
2251/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036260의 재무정보를 가져왔습니다.
2252/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058530의 재무정보를 가져왔습니다.
2253/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042110의 재무정보를 가져왔습니다.
2254/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
208140의 재무정보를 가져왔습니다.
2255/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005860의 재무정보를 가져왔습니다.
2256/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
175140의 재무정보를 가져왔습니다.
2257/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
265560의 재무정보를 가져왔습니다.
2258/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
137950의 재무정보를 가져왔습니다.
2259/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131180의 재무정보를 가져왔습니다.
2260/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226350의 재무정보를 가져왔습니다.
2261/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080470의 재무정보를 가져왔습니다.
2262/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090410의 재무정보를 가져왔습니다.
2263/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069540의 재무정보를 가져왔습니다.
2264/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089010의 재무정보를 가져왔습니다.
2265/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041520의 재무정보를 가져왔습니다.
2266/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
138070의 재무정보를 가져왔습니다.
2267/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036710의 재무정보를 가져왔습니다.
2268/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036640의 재무정보를 가져왔습니다.
2269/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066900의 재무정보를 가져왔습니다.
2270/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
085670의 재무정보를 가져왔습니다.
2271/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900090의 재무정보를 가져왔습니다.
2272/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064820의 재무정보를 가져왔습니다.
2273/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
097800의 재무정보를 가져왔습니다.
2274/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
190510의 재무정보를 가져왔습니다.
2275/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052220의 재무정보를 가져왔습니다.
2276/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043590의 재무정보를 가져왔습니다.
2277/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068050의 재무정보를 가져왔습니다.
2278/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122690의 재무정보를 가져왔습니다.
2279/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042600의 재무정보를 가져왔습니다.
2280/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
255220의 재무정보를 가져왔습니다.
2281/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049120의 재무정보를 가져왔습니다.
2282/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024840의 재무정보를 가져왔습니다.
2283/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001810의 재무정보를 가져왔습니다.
2284/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101400의 재무정보를 가져왔습니다.
2285/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263860의 재무정보를 가져왔습니다.
2286/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
001000의 재무정보를 가져왔습니다.
2287/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
189980의 재무정보를 가져왔습니다.
2288/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104040의 재무정보를 가져왔습니다.
2289/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073110의 재무정보를 가져왔습니다.
2290/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123410의 재무정보를 가져왔습니다.
2291/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101000의 재무정보를 가져왔습니다.
2292/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071280의 재무정보를 가져왔습니다.
2293/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094970의 재무정보를 가져왔습니다.
2294/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
222980의 재무정보를 가져왔습니다.
2295/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017480의 재무정보를 가져왔습니다.
2296/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093520의 재무정보를 가져왔습니다.
2297/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039290의 재무정보를 가져왔습니다.
2298/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041930의 재무정보를 가져왔습니다.
2299/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050090의 재무정보를 가져왔습니다.
2300/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
087600의 재무정보를 가져왔습니다.
2301/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024120의 재무정보를 가져왔습니다.
2302/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019590는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2303/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
127710의 재무정보를 가져왔습니다.
2304/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053590의 재무정보를 가져왔습니다.
2305/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217620의 재무정보를 가져왔습니다.
2306/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078940의 재무정보를 가져왔습니다.
2307/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099830의 재무정보를 가져왔습니다.
2308/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
142210의 재무정보를 가져왔습니다.
2309/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035480의 재무정보를 가져왔습니다.
2310/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033830의 재무정보를 가져왔습니다.
2311/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065570의 재무정보를 가져왔습니다.
2312/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054220의 재무정보를 가져왔습니다.
2313/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054090의 재무정보를 가져왔습니다.
2314/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066430의 재무정보를 가져왔습니다.
2315/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
238120의 재무정보를 가져왔습니다.
2316/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037230의 재무정보를 가져왔습니다.
2317/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101390의 재무정보를 가져왔습니다.
2318/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052770의 재무정보를 가져왔습니다.
2319/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
264660의 재무정보를 가져왔습니다.
2320/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
124500의 재무정보를 가져왔습니다.
2321/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
208710의 재무정보를 가져왔습니다.
2322/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
187870의 재무정보를 가져왔습니다.
2323/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043910의 재무정보를 가져왔습니다.
2324/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263800의 재무정보를 가져왔습니다.
2325/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064510의 재무정보를 가져왔습니다.
2326/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
269620의 재무정보를 가져왔습니다.
2327/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049550의 재무정보를 가져왔습니다.
2328/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
177350의 재무정보를 가져왔습니다.
2329/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032820의 재무정보를 가져왔습니다.
2330/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
030270의 재무정보를 가져왔습니다.
2331/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
004590의 재무정보를 가져왔습니다.
2332/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065500의 재무정보를 가져왔습니다.
2333/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115440의 재무정보를 가져왔습니다.
2334/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054920의 재무정보를 가져왔습니다.
2335/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123570의 재무정보를 가져왔습니다.
2336/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065690의 재무정보를 가져왔습니다.
2337/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018620의 재무정보를 가져왔습니다.
2338/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047560의 재무정보를 가져왔습니다.
2339/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
237750의 재무정보를 가져왔습니다.
2340/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
198440의 재무정보를 가져왔습니다.
2341/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101240의 재무정보를 가져왔습니다.
2342/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033200의 재무정보를 가져왔습니다.
2343/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
213090의 재무정보를 가져왔습니다.
2344/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
161570의 재무정보를 가져왔습니다.
2345/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900070의 재무정보를 가져왔습니다.
2346/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037440의 재무정보를 가져왔습니다.
2347/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031860의 재무정보를 가져왔습니다.
2348/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226400의 재무정보를 가져왔습니다.
2349/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
159580의 재무정보를 가져왔습니다.
2350/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052300의 재무정보를 가져왔습니다.
2351/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050540의 재무정보를 가져왔습니다.
2352/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
154040의 재무정보를 가져왔습니다.
2353/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
200470의 재무정보를 가져왔습니다.
2354/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050960의 재무정보를 가져왔습니다.
2355/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
003310의 재무정보를 가져왔습니다.
2356/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044960의 재무정보를 가져왔습니다.
2357/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900110의 재무정보를 가져왔습니다.
2358/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032540의 재무정보를 가져왔습니다.
2359/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019990의 재무정보를 가져왔습니다.
2360/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072770의 재무정보를 가져왔습니다.
2361/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
087730의 재무정보를 가져왔습니다.
2362/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
056700의 재무정보를 가져왔습니다.
2363/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215100의 재무정보를 가져왔습니다.
2364/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094840의 재무정보를 가져왔습니다.
2365/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
063440의 재무정보를 가져왔습니다.
2366/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
071850의 재무정보를 가져왔습니다.
2367/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
214870의 재무정보를 가져왔습니다.
2368/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052670의 재무정보를 가져왔습니다.
2369/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045060의 재무정보를 가져왔습니다.
2370/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
148250의 재무정보를 가져왔습니다.
2371/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
119500의 재무정보를 가져왔습니다.
2372/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024910의 재무정보를 가져왔습니다.
2373/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
041020의 재무정보를 가져왔습니다.

2374/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
106520의 재무정보를 가져왔습니다.
2375/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
109860의 재무정보를 가져왔습니다.
2376/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024830의 재무정보를 가져왔습니다.
2377/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049830의 재무정보를 가져왔습니다.
2378/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
081580의 재무정보를 가져왔습니다.
2379/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054540의 재무정보를 가져왔습니다.
2380/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009730의 재무정보를 가져왔습니다.
2381/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012860의 재무정보를 가져왔습니다.
2382/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
042500의 재무정보를 가져왔습니다.
2383/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
076080의 재무정보를 가져왔습니다.
2384/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019010의 재무정보를 가져왔습니다.
2385/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054630의 재무정보를 가져왔습니다.
2386/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
224110의 재무정보를 가져왔습니다.
2387/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037330의 재무정보를 가져왔습니다.
2388/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037760의 재무정보를 가져왔습니다.
2389/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263920의 재무정보를 가져왔습니다.
2390/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051780의 재무정보를 가져왔습니다.
2391/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
191410의 재무정보를 가져왔습니다.
2392/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
195440의 재무정보를 가져왔습니다.
2393/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010470의 재무정보를 가져왔습니다.
2394/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
205470의 재무정보를 가져왔습니다.
2395/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
136510의 재무정보를 가져왔습니다.
2396/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054040의 재무정보를 가져왔습니다.
2397/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099220의 재무정보를 가져왔습니다.
2398/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
221980의 재무정보를 가져왔습니다.
2399/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
092300의 재무정보를 가져왔습니다.
2400/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017250의 재무정보를 가져왔습니다.
2401/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
133750의 재무정보를 가져왔습니다.
2402/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032750의 재무정보를 가져왔습니다.
2403/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
170030의 재무정보를 가져왔습니다.
2404/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
076610의 재무정보를 가져왔습니다.
2405/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023460는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2406/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032940의 재무정보를 가져왔습니다.
2407/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078860의 재무정보를 가져왔습니다.
2408/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016670의 재무정보를 가져왔습니다.
2409/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094360의 재무정보를 가져왔습니다.
2410/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
143540의 재무정보를 가져왔습니다.
2411/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
028080의 재무정보를 가져왔습니다.
2412/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066410의 재무정보를 가져왔습니다.
2413/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
171010의 재무정보를 가져왔습니다.
2414/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091340의 재무정보를 가져왔습니다.
2415/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
256940의 재무정보를 가져왔습니다.
2416/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105740의 재무정보를 가져왔습니다.
2417/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215480의 재무정보를 가져왔습니다.
2418/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
263540의 재무정보를 가져왔습니다.
2419/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053290의 재무정보를 가져왔습니다.
2420/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
189690의 재무정보를 가져왔습니다.
2421/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050860의 재무정보를 가져왔습니다.
2422/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
084180의 재무정보를 가져왔습니다.
2423/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046970의 재무정보를 가져왔습니다.
2424/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086060의 재무정보를 가져왔습니다.
2425/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
250060의 재무정보를 가져왔습니다.
2426/2713이 완료되었습니다.

총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226360의 재무정보를 가져왔습니다.
2427/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
031310의 재무정보를 가져왔습니다.
2428/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039240의 재무정보를 가져왔습니다.
2429/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
082850의 재무정보를 가져왔습니다.
2430/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033790의 재무정보를 가져왔습니다.
2431/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039610의 재무정보를 가져왔습니다.
2432/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101170의 재무정보를 가져왔습니다.
2433/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060540의 재무정보를 가져왔습니다.
2434/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064480의 재무정보를 가져왔습니다.
2435/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
068940의 재무정보를 가져왔습니다.
2436/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094940의 재무정보를 가져왔습니다.
2437/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
082800의 재무정보를 가져왔습니다.
2438/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044060의 재무정보를 가져왔습니다.
2439/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
049720의 재무정보를 가져왔습니다.
2440/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
182360의 재무정보를 가져왔습니다.
2441/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105550의 재무정보를 가져왔습니다.
2442/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073640의 재무정보를 가져왔습니다.
2443/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024740의 재무정보를 가져왔습니다.
2444/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
011080의 재무정보를 가져왔습니다.
2445/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
177830의 재무정보를 가져왔습니다.
2446/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053160의 재무정보를 가져왔습니다.
2447/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045300의 재무정보를 가져왔습니다.
2448/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
064290의 재무정보를 가져왔습니다.
2449/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
148140의 재무정보를 가져왔습니다.
2450/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013810의 재무정보를 가져왔습니다.
2451/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
075130의 재무정보를 가져왔습니다.
2452/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010240의 재무정보를 가져왔습니다.
2453/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
018700의 재무정보를 가져왔습니다.
2454/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066310의 재무정보를 가져왔습니다.
2455/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115500의 재무정보를 가져왔습니다.
2456/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
006050의 재무정보를 가져왔습니다.
2457/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
106080의 재무정보를 가져왔습니다.
2458/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
070300의 재무정보를 가져왔습니다.
2459/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012340의 재무정보를 가져왔습니다.
2460/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
026150의 재무정보를 가져왔습니다.
2461/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
150900의 재무정보를 가져왔습니다.
2462/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019540의 재무정보를 가져왔습니다.
2463/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101930의 재무정보를 가져왔습니다.
2464/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044180의 재무정보를 가져왔습니다.
2465/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079000의 재무정보를 가져왔습니다.
2466/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096040의 재무정보를 가져왔습니다.
2467/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039020의 재무정보를 가져왔습니다.
2468/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
017000의 재무정보를 가져왔습니다.
2469/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
062860의 재무정보를 가져왔습니다.
2470/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033110의 재무정보를 가져왔습니다.
2471/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033310의 재무정보를 가져왔습니다.
2472/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100660의 재무정보를 가져왔습니다.
2473/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
128660의 재무정보를 가져왔습니다.
2474/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123260의 재무정보를 가져왔습니다.
2475/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
005670의 재무정보를 가져왔습니다.
2476/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
016920의 재무정보를 가져왔습니다.
2477/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
153490의 재무정보를 가져왔습니다.
2478/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.

총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
036620의 재무정보를 가져왔습니다.
2479/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115480의 재무정보를 가져왔습니다.
2480/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008370의 재무정보를 가져왔습니다.
2481/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019770의 재무정보를 가져왔습니다.
2482/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
900180의 재무정보를 가져왔습니다.
2483/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067920의 재무정보를 가져왔습니다.
2484/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053050의 재무정보를 가져왔습니다.
2485/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089890의 재무정보를 가져왔습니다.
2486/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
215090의 재무정보를 가져왔습니다.
2487/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038620의 재무정보를 가져왔습니다.
2488/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052900의 재무정보를 가져왔습니다.
2489/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
021880는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2490/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052460의 재무정보를 가져왔습니다.
2491/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039310의 재무정보를 가져왔습니다.
2492/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054940의 재무정보를 가져왔습니다.
2493/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
109080의 재무정보를 가져왔습니다.
2494/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
066790의 재무정보를 가져왔습니다.
2495/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
046310의 재무정보를 가져왔습니다.
2496/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033430의 재무정보를 가져왔습니다.
2497/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008470의 재무정보를 가져왔습니다.
2498/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
085910의 재무정보를 가져왔습니다.
2499/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
189860의 재무정보를 가져왔습니다.
2500/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
027580의 재무정보를 가져왔습니다.
2501/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
126640의 재무정보를 가져왔습니다.
2502/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078650의 재무정보를 가져왔습니다.
2503/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
203450의 재무정보를 가져왔습니다.
2504/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038950의 재무정보를 가져왔습니다.
2505/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089530의 재무정보를 가져왔습니다.
2506/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
081150의 재무정보를 가져왔습니다.
2507/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
187270의 재무정보를 가져왔습니다.
2508/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
130500의 재무정보를 가져왔습니다.
2509/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
059100의 재무정보를 가져왔습니다.
2510/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
057030의 재무정보를 가져왔습니다.
2511/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035200의 재무정보를 가져왔습니다.
2512/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093640의 재무정보를 가져왔습니다.
2513/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060480의 재무정보를 가져왔습니다.
2514/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025880의 재무정보를 가져왔습니다.
2515/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
012620의 재무정보를 가져왔습니다.
2516/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002680의 재무정보를 가져왔습니다.
2517/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
048830의 재무정보를 가져왔습니다.
2518/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
075970의 재무정보를 가져왔습니다.
2519/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
020180의 재무정보를 가져왔습니다.
2520/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225590의 재무정보를 가져왔습니다.
2521/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045890의 재무정보를 가져왔습니다.
2522/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
192390의 재무정보를 가져왔습니다.
2523/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024060의 재무정보를 가져왔습니다.
2524/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007770의 재무정보를 가져왔습니다.
2525/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
174880의 재무정보를 가져왔습니다.
2526/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050320의 재무정보를 가져왔습니다.
2527/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072950의 재무정보를 가져왔습니다.
2528/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089150의 재무정보를 가져왔습니다.
2529/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
187790의 재무정보를 가져왔습니다.
2530/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131220의 재무정보를 가져왔습니다.
2531/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
212560의 재무정보를 가져왔습니다.
2532/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
002290의 재무정보를 가져왔습니다.
2533/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065770의 재무정보를 가져왔습니다.
2534/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060260의 재무정보를 가져왔습니다.
2535/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
121850의 재무정보를 가져왔습니다.
2536/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
072990의 재무정보를 가져왔습니다.
2537/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052190의 재무정보를 가져왔습니다.
2538/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
181340의 재무정보를 가져왔습니다.
2539/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
170790의 재무정보를 가져왔습니다.
2540/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038340의 재무정보를 가져왔습니다.
2541/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
219130의 재무정보를 가져왔습니다.
2542/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032580의 재무정보를 가져왔습니다.
2543/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065420의 재무정보를 가져왔습니다.
2544/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032860의 재무정보를 가져왔습니다.
2545/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
014940의 재무정보를 가져왔습니다.
2546/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
037400의 재무정보를 가져왔습니다.
2547/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051390의 재무정보를 가져왔습니다.
2548/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
056000의 재무정보를 가져왔습니다.
2549/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
044780의 재무정보를 가져왔습니다.
2550/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
035460의 재무정보를 가져왔습니다.
2551/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083500의 재무정보를 가져왔습니다.
2552/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054930의 재무정보를 가져왔습니다.
2553/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038110의 재무정보를 가져왔습니다.
2554/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
258610의 재무정보를 가져왔습니다.
2555/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131400의 재무정보를 가져왔습니다.
2556/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123750의 재무정보를 가져왔습니다.
2557/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
141070의 재무정보를 가져왔습니다.
2558/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
176440의 재무정보를 가져왔습니다.
2559/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096610의 재무정보를 가져왔습니다.
2560/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
220180의 재무정보를 가져왔습니다.
2561/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051980의 재무정보를 가져왔습니다.
2562/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
131760의 재무정보를 가져왔습니다.
2563/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039670의 재무정보를 가져왔습니다.
2564/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
104460의 재무정보를 가져왔습니다.
2565/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
2566/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032080의 재무정보를 가져왔습니다.
2567/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038530의 재무정보를 가져왔습니다.
2568/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058450의 재무정보를 가져왔습니다.
2569/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
114190의 재무정보를 가져왔습니다.
2570/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079170의 재무정보를 가져왔습니다.
2571/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053270의 재무정보를 가져왔습니다.
2572/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
000440의 재무정보를 가져왔습니다.
2573/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090740의 재무정보를 가져왔습니다.
2574/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
038010의 재무정보를 가져왔습니다.
2575/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
154030의 재무정보를 가져왔습니다.
2576/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101670의 재무정보를 가져왔습니다.
2577/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
021650의 재무정보를 가져왔습니다.
2578/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078350의 재무정보를 가져왔습니다.
2579/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115570의 재무정보를 가져왔습니다.
2580/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
065440의 재무정보를 가져왔습니다.
2581/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080530의 재무정보를 가져왔습니다.
2582/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
230980의 재무정보를 가져왔습니다.
2583/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067010의 재무정보를 가져왔습니다.
2584/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
033050의 재무정보를 가져왔습니다.
2585/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
234100의 재무정보를 가져왔습니다.
2586/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032280의 재무정보를 가져왔습니다.
2587/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
079810의 재무정보를 가져왔습니다.
2588/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
094860의 재무정보를 가져왔습니다.
2589/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
100030의 재무정보를 가져왔습니다.
2590/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
052600의 재무정보를 가져왔습니다.
2591/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
039740의 재무정보를 가져왔습니다.
2592/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
093380의 재무정보를 가져왔습니다.
2593/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
196700의 재무정보를 가져왔습니다.
2594/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023440의 재무정보를 가져왔습니다.
2595/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073540의 재무정보를 가져왔습니다.
2596/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
098120의 재무정보를 가져왔습니다.
2597/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058110의 재무정보를 가져왔습니다.
2598/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
122800의 재무정보를 가져왔습니다.
2599/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
113810의 재무정보를 가져왔습니다.
2600/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
091440의 재무정보를 가져왔습니다.
2601/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054300의 재무정보를 가져왔습니다.
2602/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069330의 재무정보를 가져왔습니다.
2603/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
077280의 재무정보를 가져왔습니다.
2604/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
082660의 재무정보를 가져왔습니다.
2605/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051380의 재무정보를 가져왔습니다.
2606/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
032040의 재무정보를 가져왔습니다.
2607/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
060380의 재무정보를 가져왔습니다.
2608/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
010280의 재무정보를 가져왔습니다.
2609/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
134580의 재무정보를 가져왔습니다.
2610/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
050760의 재무정보를 가져왔습니다.
2611/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
130740의 재무정보를 가져왔습니다.
2612/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
153460의 재무정보를 가져왔습니다.
2613/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067730의 재무정보를 가져왔습니다.
2614/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096350의 재무정보를 가져왔습니다.
2615/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024850의 재무정보를 가져왔습니다.
2616/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080440의 재무정보를 가져왔습니다.
2617/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
045340의 재무정보를 가져왔습니다.
2618/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
105330의 재무정보를 가져왔습니다.
2619/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
221610의 재무정보를 가져왔습니다.
2620/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043360의 재무정보를 가져왔습니다.
2621/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099410의 재무정보를 가져왔습니다.
2622/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
043260의 재무정보를 가져왔습니다.
2623/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
029480의 재무정보를 가져왔습니다.
2624/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
080580의 재무정보를 가져왔습니다.
2625/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
083470의 재무정보를 가져왔습니다.
2626/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
054410의 재무정보를 가져왔습니다.
2627/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073010의 재무정보를 가져왔습니다.
2628/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115610의 재무정보를 가져왔습니다.
2629/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
058420의 재무정보를 가져왔습니다.
2630/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023790의 재무정보를 가져왔습니다.
2631/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008800의 재무정보를 가져왔습니다.
2632/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217190의 재무정보를 가져왔습니다.
2633/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
026260의 재무정보를 가져왔습니다.
2634/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
232270는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2635/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
024940의 재무정보를 가져왔습니다.
2636/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
023770의 재무정보를 가져왔습니다.
2637/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
073190의 재무정보를 가져왔습니다.
2638/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
123010의 재무정보를 가져왔습니다.
2639/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
194610의 재무정보를 가져왔습니다.
2640/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
078590의 재무정보를 가져왔습니다.
2641/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
047440의 재무정보를 가져왔습니다.
2642/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
103230의 재무정보를 가져왔습니다.
2643/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
119830의 재무정보를 가져왔습니다.
2644/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
009620의 재무정보를 가져왔습니다.
2645/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
019570는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2646/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
067770의 재무정보를 가져왔습니다.
2647/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
051160의 재무정보를 가져왔습니다.
2648/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
070590의 재무정보를 가져왔습니다.
2649/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
026910의 재무정보를 가져왔습니다.
2650/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
115530의 재무정보를 가져왔습니다.
2651/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
139670의 재무정보를 가져왔습니다.
2652/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053660의 재무정보를 가져왔습니다.
2653/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
134060의 재무정보를 가져왔습니다.
2654/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
008830의 재무정보를 가져왔습니다.
2655/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
069140의 재무정보를 가져왔습니다.
2656/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
020400의 재무정보를 가져왔습니다.
2657/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
182690의 재무정보를 가져왔습니다.
2658/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
090150의 재무정보를 가져왔습니다.
2659/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
098660의 재무정보를 가져왔습니다.
2660/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
089790의 재무정보를 가져왔습니다.
2661/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
025870의 재무정보를 가져왔습니다.
2662/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
099520의 재무정보를 가져왔습니다.
2663/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
053060의 재무정보를 가져왔습니다.
2664/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
121890의 재무정보를 가져왔습니다.
2665/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
155960의 재무정보를 가져왔습니다.
2666/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
096870의 재무정보를 가져왔습니다.
2667/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
088290의 재무정보를 가져왔습니다.
2668/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226850는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2669/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
101680의 재무정보를 가져왔습니다.
2670/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
013720의 재무정보를 가져왔습니다.
2671/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
087220의 재무정보를 가져왔습니다.
2672/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
007530의 재무정보를 가져왔습니다.
2673/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
086250의 재무정보를 가져왔습니다.
2674/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
230240는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2675/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
227950는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2676/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
273060는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2677/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
242040는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2678/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
256630는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2679/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
221200는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2680/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
256840는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2681/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226340는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2682/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
217500는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2683/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
277480는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2684/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
240540는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2685/2713이 완료되었습니다.
총 6개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 6개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 6개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
253590는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2686/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.

총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
230490는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2687/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
250930는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2688/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
262830는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2689/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
265480는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2690/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
235010는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2691/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
239340는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2692/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
281740는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2693/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225430는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2694/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
254120는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2695/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
264850는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2696/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
270520는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2697/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
226440는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2698/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
281410는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2699/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
265920는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2700/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
261200는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2701/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
225440는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2702/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
267320는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2703/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
271740는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2704/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
257730는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2705/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
276920는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2706/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
232330는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2707/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
279410는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2708/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
2709/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
258790는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2710/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
264290는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2711/2713이 완료되었습니다.
총 5개의 연도에 해당하는 com_income 정보를 가져왔습니다.
총 5개의 연도에 해당하는 fin_position 정보를 가져왔습니다.
총 5개의 연도에 해당하는 cash_flow 정보를 가져왔습니다.
277410는 은행, 보험업의 재무정보이기 때문에 가져올 수 없습니다.
2712/2713이 완료되었습니다.
----------재무정보가 존재하지 않는 종목번호입니다.--------------
2713/2713이 완료되었습니다.
2713개의 크롤이 완료되고 저장되었습니다.

([('KB금융', '105560'),
  ('삼성생명', '032830'),
  ('신한지주', '055550'),
  ('하나금융지주', '086790'),
  ('삼성화재', '000810'),
  ('우리은행', '000030'),
  ('기업은행', '024110'),
  ('미래에셋대우', '006800'),
  ('한화생명', '088350'),
  ('한국금융지주', '071050'),
  ('DB손해보험', '005830'),
  ('삼성카드', '029780'),
  ('NH투자증권', '005940'),
  ('BNK금융지주', '138930'),
  ('현대해상', '001450'),
  ('삼성증권', '016360'),
  ('아이엔지생명', '079440'),
  ('맥쿼리인프라', '088980'),
  ('메리츠종금증권', '008560'),
  ('키움증권', '039490'),
  ('메리츠화재', '000060'),
  ('메리츠금융지주', '138040'),
  ('DGB금융지주', '139130'),
  ('코리안리', '003690'),
  ('동양생명', '082640'),
  ('JB금융지주', '175330'),
  ('미래에셋생명', '085620'),
  ('한화손해보험', '000370'),
  ('유안타증권', '003470'),
  ('한국토지신탁', '034830'),
  ('대신증권', '003540'),
  ('한국자산신탁', '123890'),
  ('광주은행', '192530'),
  ('신영증권', '001720'),
  ('한화투자증권', '003530'),
  ('아주캐피탈', '033660'),
  ('롯데손해보험', '000400'),
  ('우리종금', '010050'),
  ('흥국화재', '000540'),
  ('SK증권', '001510'),
  ('맵스리얼티1', '094800'),
  ('교보증권', '030610'),
  ('유진투자증권', '001200'),
  ('KTB투자증권', '030210'),
  ('현대차투자증권', '001500'),
  ('부국증권', '001270'),
  ('한국패러랠', '168490'),
  ('DB금융투자', '016610'),
  ('유화증권', '003460'),
  ('제주은행', '006220'),
  ('골든브릿지증권', '001290'),
  ('한국ANKOR유전', '152550'),
  ('한양증권', '001750'),
  ('베트남개발1', '096300'),
  ('하나니켈1호', '099340'),
  ('하나니켈2호', '099350'),
  ('이베스트투자증권', '078020'),
  ('우리기술투자', '041190'),
  ('SBI인베스트먼트', '019550'),
  ('에이티넘인베스트', '021080'),
  ('큐캐피탈', '016600'),
  ('린드먼아시아', '277070'),
  ('푸른저축은행', '007330'),
  ('대성창투', '027830'),
  ('한국캐피탈', '023760'),
  ('DSC인베스트먼트', '241520'),
  ('티에스인베스트먼트', '246690'),
  ('엠벤처투자', '019590'),
  ('CNH', '023460'),
  ('메이슨캐피탈', '021880'),
  ('케이비제9호스팩', '232270'),
  ('제미니투자', '019570'),
  ('키움스팩4호', '226850'),
  ('하나금융7호스팩', '230240'),
  ('골든브릿지제4호스팩', '227950'),
  ('엔에이치스팩12호', '273060'),
  ('교보비엔케이스팩', '242040'),
  ('엔에이치스팩10호', '256630'),
  ('유진스팩3호', '221200'),
  ('엔에이치스팩11호', '256840'),
  ('에이치엠씨3호스팩', '226340'),
  ('하이제3호스팩', '217500'),
  ('신한제4호스팩', '277480'),
  ('한국4호스팩', '240540'),
  ('대신밸런스제3호스팩', '253590'),
  ('동부제4호스팩', '230490'),
  ('케이비제10호스팩', '250930'),
  ('대신밸런스제4호스팩', '262830'),
  ('미래에셋대우스팩1호', '265480'),
  ('하이에이아이1호스팩', '235010'),
  ('미래에셋제5호스팩', '239340'),
  ('동부스팩5호', '281740'),
  ('IBKS제3호스팩', '225430'),
  ('IBKS제5호스팩', '254120'),
  ('IBKS제6호스팩', '264850'),
  ('하나금융10호스팩', '270520'),
  ('동부스팩3호', '226440'),
  ('한국제6호스팩', '281410'),
  ('한화수성스팩', '265920'),
  ('하나금융9호스팩', '261200'),
  ('이베스트스팩3호', '225440'),
  ('교보7호스팩', '267320'),
  ('한국제5호스팩', '271740'),
  ('신한제3호스팩', '257730'),
  ('IBKS제7호스팩', '276920'),
  ('SK3호스팩', '232330'),
  ('한화에이스스팩4호', '279410'),
  ('케이비제11호스팩', '258790'),
  ('한화에이스스팩3호', '264290'),
  ('IBKS제8호스팩', '277410')],
 [{'book_value_1': 1500160.1,
   'book_value_2': 1460354.1,
   'capital_expenditure': 231575.87,
   'cashflow_operations': 467074.4,
   'code': '005930',
   'cogs': 1376963.09,
   'cont_operating_income': 304747.64,
   'current_assets': 1107602.71,
   'current_liabilities': 513154.09,
   'domestic_sales': None,
   'ebit': 375223.28,
   'ebitda': 539677.41,
   'equity_owers': 1444426.16,
   'export_sales': None,
   'extraordinary_items_income': 8155.03,
   'gross_profit': 909963.58,
   'intangible_assets': 39806.0,
   'inventories': 191348.68,
   'long_term_borrowings': 9027.15,
   'net_income': 304747.64,
   'non_current_assets': 1033147.47,
   'non_current_liabilities': 127435.99,
   'operating_income': 367850.13,
   'short_term_borrowings': 64385.17,
   'stock_issued': 170133.0,
   'tangible_assets': 754963.88,
   'total_assets': 2140750.18,
   'total_equity': 1500160.1,
   'total_liabilities': 640590.08,
   'total_sales': 2286926.67,
   'year': '2013'},
  {'book_value_1': 1680881.88,
   'book_value_2': 1633027.15,
   'capital_expenditure': 220429.43,
   'cashflow_operations': 369753.89,
   'code': '005930',
   'cogs': 1282788.0,
   'cont_operating_income': 233943.58,
   'current_assets': 1151460.26,
   'current_liabilities': 520139.13,
   'domestic_sales': 207289.17,
   'ebit': 266346.13,
   'ebitda': 446880.34,
   'equity_owers': 1621817.25,
   'export_sales': 1854770.7,
   'extraordinary_items_income': 15416.2,
   'gross_profit': 779271.87,
   'intangible_assets': 47854.73,
   'inventories': 173175.04,
   'long_term_borrowings': 239.89,
   'net_income': 233943.58,
   'non_current_assets': 1152769.32,
   'non_current_liabilities': 103208.57,
   'operating_income': 250250.71,
   'short_term_borrowings': 80292.99,
   'stock_issued': 170133.0,
   'tangible_assets': 808729.5,
   'total_assets': 2304229.58,
   'total_equity': 1680881.88,
   'total_liabilities': 623347.7,
   'total_sales': 2062059.87,
   'year': '2014'},
  {'book_value_1': 1790598.05,
   'book_value_2': 1736634.94,
   'capital_expenditure': 258802.22,
   'cashflow_operations': 400617.61,
   'code': '005930',
   'cogs': 1234821.18,
   'cont_operating_income': 190601.44,
   'current_assets': 1248147.25,
   'current_liabilities': 505029.09,
   'domestic_sales': 208278.22,
   'ebit': 249763.49,
   'ebitda': 459072.06,
   'equity_owers': 1728767.67,
   'export_sales': 1798256.6,
   'extraordinary_items_income': -20374.87,
   'gross_profit': 771713.64,
   'intangible_assets': 53963.11,
   'inventories': 188117.94,
   'long_term_borrowings': 1935.98,
   'net_income': 190601.44,
   'non_current_assets': 1173647.96,
   'non_current_liabilities': 126168.07,
   'operating_income': 264134.42,
   'short_term_borrowings': 111554.25,
   'stock_issued': 170133.0,
   'tangible_assets': 864771.1,
   'total_assets': 2421795.21,
   'total_equity': 1790598.05,
   'total_liabilities': 631197.16,
   'total_sales': 2006534.82,
   'year': '2015'},
  {'book_value_1': 1929630.33,
   'book_value_2': 1876190.13,
   'capital_expenditure': 241429.73,
   'cashflow_operations': 473856.44,
   'code': '005930',
   'cogs': 1202777.15,
   'cont_operating_income': 227260.92,
   'current_assets': 1414297.04,
   'current_liabilities': 547040.95,
   'domestic_sales': None,
   'ebit': 297971.65,
   'ebitda': 505101.3,
   'equity_owers': 1864243.28,
   'export_sales': None,
   'extraordinary_items_income': 7744.47,
   'gross_profit': 815890.3,
   'intangible_assets': 53440.2,
   'inventories': 183535.03,
   'long_term_borrowings': 11791.11,
   'net_income': 227260.92,
   'non_current_assets': 1207446.2,
   'non_current_liabilities': 145071.96,
   'operating_income': 292406.72,
   'short_term_borrowings': 127467.89,
   'stock_issued': 161193.0,
   'tangible_assets': 914730.41,
   'total_assets': 2621743.24,
   'total_equity': 1929630.33,
   'total_liabilities': 692112.91,
   'total_sales': 2018667.45,
   'year': '2016'},
  {'book_value_1': 2144914.28,
   'book_value_2': 1997309.45,
   'capital_expenditure': 427922.34,
   'cashflow_operations': 621620.41,
   'code': '005930',
   'cogs': 1292906.61,
   'cont_operating_income': 421867.47,
   'current_assets': 1469824.64,
   'current_liabilities': 671751.14,
   'domestic_sales': None,
   'ebit': 552371.46,
   'ebitda': 773545.38,
   'equity_owers': 2072134.16,
   'export_sales': None,
   'extraordinary_items_income': 15910.09,
   'gross_profit': 1102847.15,
   'intangible_assets': 147604.83,
   'inventories': 249833.55,
   'long_term_borrowings': 17569.08,
   'net_income': 421867.47,
   'non_current_assets': 1547696.26,
   'non_current_liabilities': 200855.48,
   'operating_income': 536450.38,
   'short_term_borrowings': 157676.19,
   'stock_issued': 161193.0,
   'tangible_assets': 1116656.48,
   'total_assets': 3017520.9,
   'total_equity': 2144914.28,
   'total_liabilities': 872606.62,
   'total_sales': 2395753.76,
   'year': '2017'},
  {'book_value_1': 130668.59,
   'book_value_2': 119564.56,
   'capital_expenditure': 32057.97,
   'cashflow_operations': 63720.56,
   'code': '000660',
   'cogs': 88645.87,
   'cont_operating_income': 28728.57,
   'current_assets': 66531.24,
   'current_liabilities': 30782.39,
   'domestic_sales': None,
   'ebit': 32651.38,
   'ebitda': 63436.59,
   'equity_owers': 130672.43,
   'export_sales': None,
   'extraordinary_items_income': -1373.57,
   'gross_profit': 53005.15,
   'intangible_assets': 11104.03,
   'inventories': 11783.0,
   'long_term_borrowings': 17301.83,
   'net_income': 28728.57,
   'non_current_assets': 141441.74,
   'non_current_liabilities': 46522.0,
   'operating_income': 33797.85,
   'short_term_borrowings': 1379.79,
   'stock_issued': 710201.0,
   'tangible_assets': 121297.97,
   'total_assets': 207972.98,
   'total_equity': 130668.59,
   'total_liabilities': 77304.39,
   'total_sales': 141651.02,
   'year': '2013'},
  {'book_value_1': 180363.03,
   'book_value_2': 166996.23,
   'capital_expenditure': 48007.22,
   'cashflow_operations': 58666.91,
   'code': '000660',
   'cogs': 94617.25,
   'cont_operating_income': 41951.69,
   'current_assets': 103635.14,
   'current_liabilities': 57653.04,
   'domestic_sales': None,
   'ebit': 51659.11,
   'ebitda': 86098.91,
   'equity_owers': 180364.53,
   'export_sales': None,
   'extraordinary_items_income': 362.6,
   'gross_profit': 76638.41,
   'intangible_assets': 13366.8,
   'inventories': 14975.63,
   'long_term_borrowings': 12627.72,
   'net_income': 41951.69,
   'non_current_assets': 165197.64,
   'non_current_liabilities': 30816.71,
   'operating_income': 51094.66,
   'short_term_borrowings': 7341.65,
   'stock_issued': 728002.0,
   'tangible_assets': 140903.34,
   'total_assets': 268832.78,
   'total_equity': 180363.03,
   'total_liabilities': 88469.75,
   'total_sales': 171255.66,
   'year': '2014'},
  {'book_value_1': 213877.03,
   'book_value_2': 196828.07,
   'capital_expenditure': 67746.25,
   'cashflow_operations': 93195.2,
   'code': '000660',
   'cogs': 105153.53,
   'cont_operating_income': 43235.95,
   'current_assets': 97600.3,
   'current_liabilities': 48406.98,
   'domestic_sales': None,
   'ebit': 53469.11,
   'ebitda': 93001.47,
   'equity_owers': 213868.63,
   'export_sales': None,
   'extraordinary_items_income': -1084.6,
   'gross_profit': 82826.45,
   'intangible_assets': 17048.96,
   'inventories': 19233.76,
   'long_term_borrowings': 15120.03,
   'net_income': 43235.95,
   'non_current_assets': 199178.76,
   'non_current_liabilities': 34495.05,
   'operating_income': 53361.0,
   'short_term_borrowings': 1479.48,
   'stock_issued': 728002.0,
   'tangible_assets': 169662.52,
   'total_assets': 296779.06,
   'total_equity': 213877.03,
   'total_liabilities': 82902.03,
   'total_sales': 187979.98,
   'year': '2015'},
  {'book_value_1': 240235.3,
   'book_value_2': 221079.39,
   'capital_expenditure': 59563.54,
   'cashflow_operations': 55489.22,
   'code': '000660',
   'cogs': 107871.39,
   'cont_operating_income': 29604.83,
   'current_assets': 98389.82,
   'current_liabilities': 41608.49,
   'domestic_sales': None,
   'ebit': 33024.02,
   'ebitda': 77588.57,
   'equity_owers': 240169.55,
   'export_sales': None,
   'extraordinary_items_income': -516.08,
   'gross_profit': 64108.36,
   'intangible_assets': 19155.91,
   'inventories': 20261.98,
   'long_term_borrowings': 20957.37,
   'net_income': 29604.83,
   'non_current_assets': 223770.44,
   'non_current_liabilities': 40316.47,
   'operating_income': 32767.46,
   'short_term_borrowings': None,
   'stock_issued': 728002.0,
   'tangible_assets': 187774.02,
   'total_assets': 322160.26,
   'total_equity': 240235.3,
   'total_liabilities': 81924.96,
   'total_sales': 171979.75,
   'year': '2016'},
  {'book_value_1': 338209.19,
   'book_value_2': 315736.29,
   'capital_expenditure': 91283.03,
   'cashflow_operations': 146906.14,
   'code': '000660',
   'cogs': 127018.43,
   'cont_operating_income': 106422.19,
   'current_assets': 173104.44,
   'current_liabilities': 81161.33,
   'domestic_sales': None,
   'ebit': 135092.09,
   'ebitda': 185354.44,
   'equity_owers': 338152.8,
   'export_sales': None,
   'extraordinary_items_income': -409.78,
   'gross_profit': 174075.91,
   'intangible_assets': 22472.9,
   'inventories': 26404.39,
   'long_term_borrowings': 20803.33,
   'net_income': 106422.19,
   'non_current_assets': 281080.2,
   'non_current_liabilities': 34814.12,
   'operating_income': 137213.26,
   'short_term_borrowings': 1926.86,
   'stock_issued': 728002.0,
   'tangible_assets': 240626.01,
   'total_assets': 454184.64,
   'total_equity': 338209.19,
   'total_liabilities': 115975.45,
   'total_sales': 301094.34,
   'year': '2017'},
  {'book_value_1': 4000.96,
   'book_value_2': 2658.44,
   'capital_expenditure': 711.73,
   'cashflow_operations': -1035.38,
   'code': '207940',
   'cogs': 755.89,
   'cont_operating_income': -1407.62,
   'current_assets': 1327.49,
   'current_liabilities': 1719.17,
   'domestic_sales': None,
   'ebit': -1449.69,
   'ebitda': -1329.68,
   'equity_owers': 3683.45,
   'export_sales': None,
   'extraordinary_items_income': -0.67,
   'gross_profit': -318.42,
   'intangible_assets': 1342.52,
   'inventories': 163.93,
   'long_term_borrowings': 710.0,
   'net_income': -1407.62,
   'non_current_assets': 5206.76,
   'non_current_liabilities': 814.13,
   'operating_income': -1463.54,
   'short_term_borrowings': 520.09,
   'stock_issued': 11887.0,
   'tangible_assets': 3776.47,
   'total_assets': 6534.26,
   'total_equity': 4000.96,
   'total_liabilities': 2533.3,
   'total_sales': 437.47,
   'year': '2013'},
  {'book_value_1': 6621.14,
   'book_value_2': 3870.18,
   'capital_expenditure': 3659.34,
   'cashflow_operations': -1636.64,
   'code': '207940',
   'cogs': 1193.54,
   'cont_operating_income': -839.39,
   'current_assets': 1790.02,
   'current_liabilities': 2442.25,
   'domestic_sales': None,
   'ebit': -844.79,
   'ebitda': -581.29,
   'equity_owers': 6264.8,
   'export_sales': None,
   'extraordinary_items_income': 586.53,
   'gross_profit': -139.55,
   'intangible_assets': 2750.96,
   'inventories': 356.78,
   'long_term_borrowings': 3771.99,
   'net_income': -839.39,
   'non_current_assets': 11782.93,
   'non_current_liabilities': 4509.56,
   'operating_income': -1051.97,
   'short_term_borrowings': 485.26,
   'stock_issued': 20367.0,
   'tangible_assets': 7612.94,
   'total_assets': 13572.95,
   'total_equity': 6621.14,
   'total_liabilities': 6951.81,
   'total_sales': 1053.99,
   'year': '2014'},
  {'book_value_1': 27748.34,
   'book_value_2': 27605.48,
   'capital_expenditure': 2403.26,
   'cashflow_operations': -2655.14,
   'code': '207940',
   'cogs': 1147.85,
   'cont_operating_income': 19049.46,
   'current_assets': 1928.54,
   'current_liabilities': 19116.69,
   'domestic_sales': None,
   'ebit': 24895.31,
   'ebitda': 25311.59,
   'equity_owers': 27748.34,
   'export_sales': None,
   'extraordinary_items_income': 18.42,
   'gross_profit': -235.07,
   'intangible_assets': 142.86,
   'inventories': 1191.77,
   'long_term_borrowings': 6817.92,
   'net_income': 19049.46,
   'non_current_assets': 57676.4,
   'non_current_liabilities': 12739.9,
   'operating_income': -2036.42,
   'short_term_borrowings': 101.09,
   'stock_issued': 27569.0,
   'tangible_assets': 8902.56,
   'total_assets': 59604.94,
   'total_equity': 27748.34,
   'total_liabilities': 31856.6,
   'total_sales': 912.78,
   'year': '2015'},
  {'book_value_1': 40823.79,
   'book_value_2': 40683.35,
   'capital_expenditure': 1629.92,
   'cashflow_operations': -626.61,
   'code': '207940',
   'cogs': 2680.88,
   'cont_operating_income': -1768.23,
   'current_assets': 14614.25,
   'current_liabilities': 24765.45,
   'domestic_sales': 2946.22,
   'ebit': -2152.86,
   'ebitda': -1551.36,
   'equity_owers': 40823.79,
   'export_sales': None,
   'extraordinary_items_income': 11.79,
   'gross_profit': 265.34,
   'intangible_assets': 140.45,
   'inventories': 1642.2,
   'long_term_borrowings': 3893.63,
   'net_income': -1768.23,
   'non_current_assets': 60715.91,
   'non_current_liabilities': 9740.91,
   'operating_income': -304.23,
   'short_term_borrowings': None,
   'stock_issued': 66165.0,
   'tangible_assets': 10909.6,
   'total_assets': 75330.16,
   'total_equity': 40823.79,
   'total_liabilities': 34506.37,
   'total_sales': 2946.22,
   'year': '2016'},
  {'book_value_1': 39764.51,
   'book_value_2': 39574.52,
   'capital_expenditure': 4941.19,
   'cashflow_operations': 1498.16,
   'code': '207940',
   'cogs': 3328.29,
   'cont_operating_income': -969.72,
   'current_assets': 6209.95,
   'current_liabilities': 22874.42,
   'domestic_sales': None,
   'ebit': -1202.61,
   'ebitda': -503.34,
   'equity_owers': 39764.51,
   'export_sales': None,
   'extraordinary_items_income': 7.54,
   'gross_profit': 1318.0,
   'intangible_assets': 189.99,
   'inventories': 2099.87,
   'long_term_borrowings': 3572.36,
   'net_income': -969.72,
   'non_current_assets': 65620.96,
   'non_current_liabilities': 9191.98,
   'operating_income': 659.79,
   'short_term_borrowings': 400.0,
   'stock_issued': 66165.0,
   'tangible_assets': 15133.33,
   'total_assets': 71830.91,
   'total_equity': 39764.51,
   'total_liabilities': 32066.4,
   'total_sales': 4646.29,
   'year': '2017'},
  {'book_value_1': 10871.32,
   'book_value_2': 5846.31,
   'capital_expenditure': 73.54,
   'cashflow_operations': 1370.81,
   'code': '068270',
   'cogs': 686.86,
   'cont_operating_income': 1024.55,
   'current_assets': 5515.3,
   'current_liabilities': 4977.97,
   'domestic_sales': 2262.08,
   'ebit': 1372.73,
   'ebitda': 1849.84,
   'equity_owers': 10871.32,
   'export_sales': None,
   'extraordinary_items_income': 264.27,
   'gross_profit': 1575.22,
   'intangible_assets': 5025.01,
   'inventories': 1368.4,
   'long_term_borrowings': 1470.43,
   'net_income': 1024.55,
   'non_current_assets': 14269.78,
   'non_current_liabilities': 3935.79,
   'operating_income': 998.45,
   'short_term_borrowings': 2451.09,
   'stock_issued': 100504.0,
   'tangible_assets': 7164.84,
   'total_assets': 19785.08,
   'total_equity': 10871.32,
   'total_liabilities': 8913.76,
   'total_sales': 2262.08,
   'year': '2013'},
  {'book_value_1': 13477.81,
   'book_value_2': 7462.23,
   'capital_expenditure': 314.72,
   'cashflow_operations': 1451.59,
   'code': '068270',
   'cogs': 1299.08,
   'cont_operating_income': 1174.82,
   'current_assets': 7930.36,
   'current_liabilities': 4939.37,
   'domestic_sales': 4710.46,
   'ebit': 1772.9,
   'ebitda': 2535.69,
   'equity_owers': 12473.94,
   'export_sales': None,
   'extraordinary_items_income': -67.25,
   'gross_profit': 3411.38,
   'intangible_assets': 6015.58,
   'inventories': 2236.17,
   'long_term_borrowings': 1987.71,
   'net_income': 1174.82,
   'non_current_assets': 15293.49,
   'non_current_liabilities': 4806.67,
   'operating_income': 2014.69,
   'short_term_borrowings': 2638.96,
   'stock_issued': 103570.0,
   'tangible_assets': 8982.29,
   'total_assets': 23223.85,
   'total_equity': 13477.81,
   'total_liabilities': 9746.04,
   'total_sales': 4710.46,
   'year': '2014'},
  {'book_value_1': 18098.41,
   'book_value_2': 11120.67,
   'capital_expenditure': 505.85,
   'cashflow_operations': 775.67,
   'code': '068270',
   'cogs': 2345.69,
   'cont_operating_income': 1582.82,
   'current_assets': 10968.37,
   'current_liabilities': 6657.51,
   'domestic_sales': None,
   'ebit': 1857.68,
   'ebitda': 2679.42,
   'equity_owers': 16942.34,
   'export_sales': None,
   'extraordinary_items_income': -648.75,
   'gross_profit': 3688.44,
   'intangible_assets': 6977.74,
   'inventories': 2337.66,
   'long_term_borrowings': 1575.82,
   'net_income': 1582.82,
   'non_current_assets': 16513.93,
   'non_current_liabilities': 2726.39,
   'operating_income': 2589.54,
   'short_term_borrowings': 3247.26,
   'stock_issued': 112432.0,
   'tangible_assets': 8976.05,
   'total_assets': 27482.31,
   'total_equity': 18098.41,
   'total_liabilities': 9383.9,
   'total_sales': 6034.13,
   'year': '2015'},
  {'book_value_1': 21989.67,
   'book_value_2': 13506.44,
   'capital_expenditure': 141.47,
   'cashflow_operations': 2508.88,
   'code': '068270',
   'cogs': 2739.78,
   'cont_operating_income': 1804.52,
   'current_assets': 12540.69,
   'current_liabilities': 6102.53,